### ISSUE TITLE
Minimize From Title Bar Not Working For Some Applications

### ISSUE THREAD

**Issue by haoxiangliew** [pop-os/shell#401] opened 2020-05-30 02:07 UTC
```
NAME="Pop!_OS"
VERSION="20.04 LTS"
ID=pop
ID_LIKE="ubuntu debian"
PRETTY_NAME="Pop!_OS 20.04 LTS"
VERSION_ID="20.04"
HOME_URL="https://system76.com/pop"
SUPPORT_URL="http://support.system76.com"
BUG_REPORT_URL="https://github.com/pop-os/pop/issues"
PRIVACY_POLICY_URL="https://system76.com/privacy"
VERSION_CODENAME=focal
UBUNTU_CODENAME=focal
LOGO=distributor-logo-pop-os
```
```
pop-shell:
  Installed: 0.1.0~1589925465~20.04~ff5f374
  Candidate: 0.1.0~1589925465~20.04~ff5f374
  Version table:
 *** 0.1.0~1589925465~20.04~ff5f374 1001
       1001 http://ppa.launchpad.net/system76/pop/ubuntu focal/main amd64 Packages
       1001 http://ppa.launchpad.net/system76/pop/ubuntu focal/main i386 Packages
        100 /var/lib/dpkg/status
```
## Issue

Adding a minimize shortcut to the titlebar with GNOME Tweaks, and using that minimize button will not cause popOS tiling to respond to the change in space.

However, setting a keyboard shortcut (Super + H) to hide window (disabled by default), or right clicking and minimizing on the titlebar gives me the expected behavior from popOS tiling.

## Steps to Reproduce
1. Install gnome-tweaks
2. Add minimize button to titlebar
3. Open 2 windows with popOS tiling enabled
4. Minimize Window 1 with the titlebar shortcut, and Window 2 will not expand to fill screen

## Expected Behavior
1. Install gnome-tweaks
2. Add minimize button to titlebar
3. Open 2 windows with popOS tiling enabled
4. Minimize Window 1 with the titlebar shortcut, and Window 2 expands to fill screen

**Comment by haoxiangliew** [comment] 2020-05-30 02:55
## Updates
Chrome + Terminal give me the expected behavior

Apps like Discord and Spotify cause this problem

**Comment by cansozbir** [comment] 2020-06-02 13:46
since this is the same issue with #309, I would recommend closing this and reading @jmmaranan 's [comment](https://github.com/pop-os/shell/issues/309#issuecomment-627056307).

**Comment by mmstick** [comment] 2020-06-03 20:55
Duplicate of #309

**Closed by mmstick** 2020-06-03 20:55 UTC
Labels: bug
