### ISSUE TITLE
Press 'Super' to show activities overview not working with German keyboard layout

### ISSUE THREAD

**Issue by eichholz** [pop-os/shell#289] opened 2020-05-05 08:15 UTC
**Distribution (run `cat /etc/os-release`):**
NAME="Pop!_OS"
VERSION="20.04 LTS"
ID=pop
ID_LIKE="ubuntu debian"
PRETTY_NAME="Pop!_OS 20.04 LTS"
VERSION_ID="20.04"
HOME_URL="https://system76.com/pop"
SUPPORT_URL="http://support.system76.com"
BUG_REPORT_URL="https://github.com/pop-os/pop/issues"
PRIVACY_POLICY_URL="https://system76.com/privacy"
VERSION_CODENAME=focal
UBUNTU_CODENAME=focal
LOGO=distributor-logo-pop-os
 
**Related Application and/or Package Version (run `apt policy pop-shell` or provide the latest commit if building locally):**
pop-shell:
  Installiert:           0.1.0~1588624471~20.04~dfb378c
  Installationskandidat: 0.1.0~1588624471~20.04~dfb378c
  Versionstabelle:
 *** 0.1.0~1588624471~20.04~dfb378c 1001
       1001 http://ppa.launchpad.net/system76/pop/ubuntu focal/main amd64 Packages
       1001 http://ppa.launchpad.net/system76/pop/ubuntu focal/main i386 Packages
        100 /var/lib/dpkg/status

**Issue/Bug Description:**
After upgrading from Pop!_OS 19.10, it is not possible anymore to press the Super key to show the activities overview when using a German keyboard layout. After switching to the US layout it works as before.

**Comment by leviport** [comment] 2020-05-05 18:10
Duplicate of https://github.com/pop-os/beta/issues/98

**Closed by leviport** 2020-05-05 18:10 UTC
