### ISSUE TITLE
"Show Active Hint" border remains even after closing all windows (confirmed on multiple machines)

### ISSUE THREAD

**Issue by zahidkhawaja** [pop-os/shell#469] opened 2020-07-28 16:18 UTC
**Distribution (run `cat /etc/os-release`):**

> NAME="Pop!_OS"
> VERSION="20.04 LTS"
> ID=pop
> ID_LIKE="ubuntu debian"
> PRETTY_NAME="Pop!_OS 20.04 LTS"
> VERSION_ID="20.04"
> HOME_URL="https://pop.system76.com"
> SUPPORT_URL="https://support.system76.com"
> BUG_REPORT_URL="https://github.com/pop-os/pop/issues"
> PRIVACY_POLICY_URL="https://system76.com/privacy"
> VERSION_CODENAME=focal
> UBUNTU_CODENAME=focal
> LOGO=distributor-logo-pop-os

**Related Application and/or Package Version (run `apt policy pop-shell` or provide the latest commit if building locally):**

0.1.0~1593273798~20.04~9e8ab29

**Issue/Bug Description:**

Even after closing all windows, the "Show Active Hint" border is still on the screen for no reason.

**Steps to reproduce (if you know):**

Here are the steps. Make sure both "Tile Windows" and "Show Active Hint" are enabled. Close everything and start with a clean desktop.

1) Open a Terminal on Workspace 1.

2) Switch to Workspace 2. Open a Terminal.

3) Switch to Workpace 1. Close the Terminal.

4) Switch to Workspace 2. Close the Terminal.

5) The "Show Active Hint" border is still on the screen, even though no windows are open.

**Expected behavior:**

The "Show Active Hint" border should go away when all windows are closed.

**Other Notes:**

I have confirmed this on **3 machines** (clean installed Pop!_OS 20.04). All 3 machines have either Intel/AMD graphics. No Nvidia.

Machines are up-to-date. No Gnome extensions or customizations of any kind. "Vanilla" Pop!_OS (what you get right out the box).

**Comment by jmmaranan** [comment] 2020-07-31 20:14
Duplicate of #366 or #365

**Closed** 2020-08-10 17:57 UTC
