### ISSUE TITLE
Applications are not closing unless I refresh shell, system crashes 

### ISSUE THREAD

**Issue by Bookingyo** [pop-os/shell#224] opened 2020-04-25 20:39 UTC
**Distribution**
NAME="Ubuntu"
VERSION="20.04 LTS (Focal Fossa)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 20.04 LTS"
VERSION_ID="20.04"
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
VERSION_CODENAME=focal
UBUNTU_CODENAME=focal

**Related Application and/or Package Version**
Using the latest commit: 4d85c31

**Issue/Bug Description:**
Applications remain active in pop-shell after being closed. In addition to the desired application opening, an alternate application will launch and show as active in the shell.  If I right-click the 'ghost' application on the dock to use the Quit function, pop-shell completely freezes and I need to Ctrl+Alt+F3, login and reboot the computer. For example, I open the terminal and VLC opens the dock, if I right-click on the VLC icon my system will freeze up.
 
The only thing that seems to remove these 'ghost' applications as by Alt+F2 + r (refreshing pop-shell).

**Expected behavior:**
No additional application should open when opening the desired application. Programs should close correctly and should not remain active in the shells instance.

**Other Notes:**
This bug happens at random. Since I uninstalled the pop shell extension I have experienced no other issues. It may be conflicting with another extension that I have installed, such as dash-to-dock or maybe Impatience.

Installed shell extensions
activities-config@nls1729
noannoyance@daase.net
caffeine@patapon.info
pop-shell@system76.com
dash-to-dock@micxgx.gmail.com
remove-dropdown-arrows@mpdeimos.com
drive-menu@gnome-shell-extensions.gcampax.github.com
sound-output-device-chooser@kgshank.net
drop-down-terminal-x@bigbn.pro
status-area-horizontal-spacing@mathe...ffee.gmail.com
gnome-shell-screenshot@ttll.de
transparent-window-moving@noobsai.github.com
impatience@gfxmonk.net

**Comment by jannikbuhr** [comment] 2020-04-27 21:55
I can confirm these ghost applications with similar extensions active (dash-to-panel instead of dash-to-dock). Sometimes they occur without the extensions with the regular dash and leave me unable to close or open a new window of said application.

**Comment by AdamoPrincipe** [comment] 2020-04-28 03:37
I can confirm too, but I'm on PopOS 20.04 beta.

**Comment by Dark-Matter7232** [comment] 2020-04-28 04:07
I can confirm but I am on fedora 32

**Comment by ishan9299** [comment] 2020-04-28 05:28
If you are using Dash to panel there is a conflicting keybinding with Super q .(Under Action -> hotkey preferences)

To fix (more of like better out of box experience) changing the shortcut to Super w would be better imo.

**Comment by mmstick** [comment] 2020-04-29 14:50
Duplicate of #220

**Closed** 2020-04-29 14:51 UTC

**Comment by algom** [comment] 2020-05-09 15:12
Issue still persist in Pop OS 20.04 (Fresh install) up to date.
How to replicate: Open Firefox, open a new Firefox window, close both windows from Dash (Quit both windows) the application seems to continue running and no other window can be open unless launched from the Terminal.
Disable/re-enable Pop-shell extension does not do anything. Can only be "rescued" by Alt+F2, r.
The same happens with Chrome.

Moreover, doing a right click on the icon (Firefox or Chrome) freezes my computer for a several seconds, mouse can be moved but no commands can be executed with the keyboard. Afterwards it recovers and Alt+F2, r, puts everything back to normal.
