### ISSUE TITLE
Can't type password in authentication mode 

### ISSUE THREAD

**Issue by Neo-29** [pop-os/shell#1392] opened 2022-04-07 19:34 UTC
**(1) Issue/Bug Description:**

Can't type password in authentication mode 

**(2) Steps to reproduce (if you know):**

open for example pamac, preferences , then comes the authentication 

**(3) Expected behavior:**
possible to enter password

**(4) Distribution (run `cat /etc/os-release`):**
 
archlinux with popshell git

**(5) Gnome Shell version:**

**(6) Pop Shell version (run `apt policy pop-shell` or provide the latest commit if building locally):**

**(7) Where was Pop Shell installed from:**

**(8) Monitor Setup (2 x 1080p, 4K, Primary(Horizontal), Secondary(Vertical), etc):**

**(9) Other Installed/Enabled Extensions:**

**(10) Other Notes:**

**Comment by nicklozon** [comment] 2022-04-08 15:43
What's the gnome shell version? `gnome-shell --version`

**Comment by nicklozon** [comment] 2022-04-08 16:00
I had the same issue but that's because the AUR package is outdated and not using `master_jammy` branch.

Do you know what commit of pop-shell you have installed? Is it installed through pacman?

I modified the PKGBUILD of the AUR package to use the latest branch and the issue has been resolved:
```sh
$ pacman -Q | grep pop-shell
gnome-shell-extension-pop-shell-git r860.cb76a4c-1
```

```sh
pkgname=gnome-shell-extension-pop-shell-git
pkgdesc="Pop Shell - Tiling window management in Gnome (WIP)"
pkgver=r860.cb76a4c # changed this
pkgrel=1
_gitorg=pop-os
_gitname=shell
_gitbranch=master_jammy # changed this
arch=(any)
url="https://github.com/pop-os/shell"
license=("GPLv3")
install="pop-shell.install"
optdepends=('gnome-shell-extensions: native-window extension for improved window placement')
conflicts=("gnome-shell-extension-pop-shell")
makedepends=("typescript" "git")
depends=("gnome-shell" "pop-shell-shortcuts-git" "pop-launcher-git" "fd")


_dir="${_gitname}"
source=("${_dir}::git+https://github.com/${_gitorg}/${_gitname}.git#branch=${_gitbranch}")
sha256sums=("SKIP")


pkgver() {
    cd "${srcdir}/${_dir}"
    printf "r%s.%s" "$(git rev-list --count HEAD)" "$(git rev-parse --short HEAD)"
}


build() {
    cd "${srcdir}/${_dir}"
    make all
}


package() {
    cd "${srcdir}/${_dir}"
    make DESTDIR="${pkgdir}/" install

	install -Dm644 schemas/org.gnome.shell.extensions.pop-shell.gschema.xml -t \
		"$pkgdir/usr/share/glib-2.0/schemas"
	install -Dm644 keybindings/*.xml -t \
		"$pkgdir/usr/share/gnome-control-center/keybindings"
    install -Dm755 scripts/configure.sh "${pkgdir}/usr/share/gnome-shell/extensions/pop-shell@system76.com/scripts/configure.sh"
}
```

**Comment by Neo-29** [comment] 2022-04-08 16:03
Tks for the quick answer.
I used the git version of pop-shell.
Can't tell which commit is taken.
Maybe the pkgbuild is outdated.
Should I use the pkgbuild you posted above?

**Comment by nicklozon** [comment] 2022-04-08 16:16
If you feel comfortable - as a good rule of thumb, don't trust anyone who gives you random code.

You can compare this PKGBUILD to the popular AUR repo to determine it's not malicious.

I have also pushed an AUR package until that upstream repo is updated: https://aur.archlinux.org/packages/gnome-shell-extension-pop-shell-git-master_jammy#comment-860344

`yay gnome-shell-extension-pop-shell-git-master_jammy` if you use yay

**Comment by Neo-29** [comment] 2022-04-08 16:58
Of course. As primary rule.. Always compare and decide.
Tks

**Comment by Neo-29** [comment] 2022-04-08 20:33
It's been pushed... No issues...
Some glitches but I'm sure it will be fixed along the way.

Tks again for your help.

All the best.

**Comment by jacobgkau** [comment] 2022-04-08 20:39
Closing because it sounds like the issue is no longer occurring on the latest version, making this a packaging issue.

**Closed by jacobgkau** 2022-04-08 20:39 UTC
