### ISSUE TITLE
Gnome 47: TypeError when attempting to enable pop shell

### ISSUE THREAD

**Issue by CodeAndGin** [pop-os/shell#1732] opened 2024-09-19 15:13 UTC
**(1) Issue/Bug Description:**
Just upgraded to Gnome 47, Pop Shell encounters "TypeError: window.is_client_decorated is not a function" when I try to enable the extension from the extensions menu.

**(2) Steps to reproduce (if you know):**

**(3) Expected behavior:**

**(4) Distribution (run `cat /etc/os-release`):**
Arch Linux

**(5) Gnome Shell version:**
Gnome 47

**(6) Pop Shell version (run `apt policy pop-shell` or provide the latest commit if building locally):**

Commit [ced5442](https://github.com/pop-os/shell/commit/ced54427487905f42447a07dabff7101b700b5c9)

**(7) Where was Pop Shell installed from:**
Git

**(8) Monitor Setup (2 x 1080p, 4K, Primary(Horizontal), Secondary(Vertical), etc):**
1 x 2K

**(9) Other Installed/Enabled Extensions:**
*[Arch Linux Updates Indicator](https://extensions.gnome.org/extension/1010/archlinux-updates-indicator/)
*[Auto Move Windows](https://extensions.gnome.org/extension/16/auto-move-windows/)
*[Blur My Shell](https://extensions.gnome.org/extension/3193/blur-my-shell/)
*[Caffeine](https://extensions.gnome.org/extension/517/caffeine/)
*[Dash to Dock](https://extensions.gnome.org/extension/307/dash-to-dock/)
*[Launch New Instance](https://extensions.gnome.org/extension/600/launch-new-instance/)
*[Native Window Placement](https://extensions.gnome.org/extension/18/native-window-placement/)
*[Removable Drive Menu](https://extensions.gnome.org/extension/7/removable-drive-menu/)
*[Rounded Window Corners Reborn](https://extensions.gnome.org/extension/7048/rounded-window-corners-reborn/) (slightly modified by me for an extra colour option)
*[Screenshot Window Sizer](https://extensions.gnome.org/extension/881/screenshot-window-sizer/)
*[Transparent Window Moving](https://extensions.gnome.org/extension/1446/transparent-window-moving/)
*[User Themes](https://extensions.gnome.org/extension/19/user-themes/)

I also tried disabling all of these and logging out and in, before attempting to start pop shell, same issue.

**(10) Other Notes:**

**Comment by CodeAndGin** [comment] 2024-09-20 12:03
Update; a power cycle seems to have resolved the issue, unsure why.

**Comment by HideyoshiNakazone** [comment] 2024-09-20 12:32
The problem is on the [`Meta.Window`](https://github.com/pop-os/shell/blob/ced54427487905f42447a07dabff7101b700b5c9/src/mod.d.ts#L260) interface, in Meta 15 the Window interface has switched from the `is_client_decorated` method to the `decorated`.

**Comment by mgamigo** [comment] 2024-09-21 08:23
I am having the same issue, but it is not getting resolved by power cycle. When I reboot the extension appears as activated, but is not working. If I disable it (in order to restart the extension), I get the error back:

"TypeError: window.is_client_decorated is not a function"

**Comment by McCio** [comment] 2024-09-21 13:07
> The problem is on the [`Meta.Window`](https://github.com/pop-os/shell/blob/ced54427487905f42447a07dabff7101b700b5c9/src/mod.d.ts#L260) interface, in Meta 15 the Window interface has switched from the `is_client_decorated` method to the `decorated`.

I executed `sed -i 's/is_client_decorated/decorated/g' src/*.ts` before `make` and now it works wonderfully again!
As I understand that change is not backward compatible for Gnome 45 and 46, so I won't submit a PR, as I guess it will require more testing.

**Comment by mgamigo** [comment] 2024-09-21 14:18
Thanks for the hint @McCio. I am currently installing it via the AUR and I would like to continue that way. I hope that the fix it soon.

**Comment by CodeAndGin** [comment] 2024-09-21 14:55
further update; power cycling stopped the error from occurring, but tiling doesn't work, and if I rebuild with either the original or with @McCio's modification, both seem to throw the TypeError (but "window.decoration is not a function" with the mod). This is not the sort of thing I'm particularly good at troubleshooting unfortunately =/

**Comment by lutzseverino** [comment] 2024-09-24 15:22
Same as @mgamigo here. I use the AUR and the extension doesn't work right now. Prefer to just uninstall until this problem is resolved.

**Comment by mgamigo** [comment] 2024-09-29 19:46
@McCio I tried doing that, with `make local-install` and I am getting this error

`TypeError: window.decorated is not a function`

Did you change anything else? Gnome 47?

**Comment by GlobalRepos** [comment] 2024-09-30 22:24
I'm facing the same Problem here, specially after installing Gnome 47 in Arch !

**Comment by wojciech-zurek** [comment] 2024-10-01 10:34
I have the same problem on Arch: window.is_client_decorated / window.decorated  is not a function.
The fix from @McCio not working for me.
I'm using latest git version.

**Comment by McCio** [comment] 2024-10-01 13:21
Hi all, I'm not sure how but after the first restart it stopped working for the same reasons you all pointed out (windows.decorated is not a function). Probably some other package was updated in the meantime.
Since I'm too used to the pop-shell tiling, I resorted to changing `is_client_decorated()` to `is_client_decorated` (yes, just removed the parentheses, so it resolves to true if it is defined, false if it is not).
A very ugly change, but I'm not seeing any obvious issue for now (even if looking at the code the function result was used once negated, and once not, so something _must_ be different).

**Comment by CodeAndGin** [comment] 2024-10-01 13:55
I think i've figured it out, thanks to @McCio's hints for where to look: Meta.Window.decorated is a property instead of a function now (for whatever reason). 

Switching `if (!window.is_client_decorated()) {` on line 106 of window.ts to `if (!window.decorated) {`, `if (window.meta.is_client_decorated()) continue;` to `if (window.meta.decorated) continue;` on line 1674 of extension.ts and adding `decorated: Readonly<boolean>;` below line 263 of mod.d.ts got it to build without error and re-enabled tiling for me. 

Think I'll fork and PR a bit later, unless someone else beats me to the punch.

(edit: i reckon the declaration of is_client_decorated() can be removed without incident in this case but I'm not sure yet, and am too busy with house cleaning to do more rigorous testing rn)

**Comment by wojciech-zurek** [comment] 2024-10-02 06:09
@CodeAndGin Thanks.
Your fix is only partially working for me. Yes, the extension starts and tiling works. But the window decorations cannot be removed for some apps.

**Comment by CodeAndGin** [comment] 2024-10-04 19:12
@wojciech-zurek yep it seems I naively assumed decorated and is_client_decorated() were doing the same thing (they weren't, my bad). There's a newer fix that _seems_ to work fine in #1734 that I figured out earlier, basically replicating what is_client_decorated() _was_ doing.

**Comment by wojciech-zurek** [comment] 2024-10-05 12:47
@CodeAndGin Everything is working great now. Thank you! 🍺

**Closed as completed** 2024-10-09 16:58 UTC
