### ISSUE TITLE
weird artifacts or glitches on gnome shell

### ISSUE THREAD

**Issue by ffarps** [pop-os/shell#1525] opened 2022-09-28 22:26 UTC
**(1) Issue/Bug Description:**

weird artifacts or glitches on gnome shell

image bellow(it happens on **all** text and images, not just in the arcMenu):

![unknown](https://user-images.githubusercontent.com/73230223/192899547-72d085f3-c55e-4bbb-89b8-cee95a5e4516.png)

**(2) Steps to reproduce (if you know):**
 happening **after** suspending mostly
the only way that can be resolved is doing **alt+f2**, to run a command and input **r** to restart the shell, 3-5 seconds later the glicthes disappear

**(3) Expected behavior:**

no artifacts and glitches

**(4) Distribution (run `cat /etc/os-release`):**
 NAME="Pop!_OS"
VERSION="20.04 LTS"
ID=pop
ID_LIKE="ubuntu debian"
PRETTY_NAME="Pop!_OS 20.04 LTS"
VERSION_ID="20.04"
HOME_URL="https://pop.system76.com"
SUPPORT_URL="https://support.system76.com"
BUG_REPORT_URL="https://github.com/pop-os/pop/issues"
PRIVACY_POLICY_URL="https://system76.com/privacy"
VERSION_CODENAME=focal
UBUNTU_CODENAME=focal
LOGO=distributor-logo-pop-os

**(5) Gnome Shell version:**
GNOME Shell 3.36.7

**(6) Pop Shell version (run `apt policy pop-shell` or provide the latest commit if building locally):**

```pop-shell:
  Installed: 1.1.0~1651771371~20.04~aa8f35d
  Candidate: 1.1.0~1651771371~20.04~aa8f35d
  Version table:
 *** 1.1.0~1651771371~20.04~aa8f35d 1001
       1001 http://ppa.launchpad.net/system76/pop/ubuntu focal/main amd64 Packages
       1001 http://ppa.launchpad.net/system76/pop/ubuntu focal/main i386 Packages
        100 /var/lib/dpkg/status
```

**(7) Where was Pop Shell installed from:**

pop os 20.04 iso official site

**(8) Monitor Setup (2 x 1080p, 4K, Primary(Horizontal), Secondary(Vertical), etc):**

not a monitor issue

**(9) Other Installed/Enabled Extensions:**

 Always Show Workspaces
ArcMenu
Caffeine
Clipboard Indicator
Dash to Dock
Desktop Icons NG(DING)
Pop Shell
Pop Shell Details
Removable Drive Menu
Remove Dropdown arrows
Sound input & Output Device Chooser
system-monitor
System76 power

**(10) Other Notes:**

being using this pop os install for months now, it keep happening after suspending
I thought that this would disappear after some updates, but no

**Comment by leviport** [comment] 2022-09-28 22:29
This looks like it might be a duplicate of https://github.com/pop-os/nvidia-graphics-drivers/issues/133. Does your machine have Nvidia graphics? If so, the current easiest workaround is to restart Gnome shell when this happens (Alt + F2, `r`, Enter).

**Comment by ffarps** [comment] 2022-09-28 22:31
> This looks like it might be a duplicate of [pop-os/nvidia-graphics-drivers#133](https://github.com/pop-os/nvidia-graphics-drivers/issues/133). Does your machine have Nvidia graphics? If so, the current easiest workaround is to restart Gnome shell when this happens (Alt + F2, `r`, Enter).

yes as I said I already do Alt + F2, `r`, Enter for months now

**Comment by leviport** [comment] 2022-09-28 22:34
Ah sorry, I skimmed over that part. I'll close this as a duplicate of https://github.com/pop-os/nvidia-graphics-drivers/issues/133 then.

**Closed as completed by leviport** 2022-09-28 22:34 UTC

**Comment by ffarps** [comment] 2022-09-28 22:36
al right, thanks for you time @leviport 
appreciated
