### ISSUE TITLE
Gnome 41 Grey Background in Activities

### ISSUE THREAD

**Issue by Sultech** [pop-os/shell#1235] opened 2021-11-03 23:05 UTC
**(1) Issue/Bug Description:**
When restarting gnome shell and going into activities there is just a grey screen with no workspaces.

**(2) Steps to reproduce (if you know):**
With pop shell enabled restart gnome shell and open activities it will show a grey background

![Screenshot from 2021-11-03 23-02-54](https://user-images.githubusercontent.com/30802163/140230071-d5237031-8116-4af6-ac2a-0fa12aa761c4.png)

**(3) Expected behavior:**
Is to be able to see the workspaces after restarting gnome shell

**(4) Distribution (run `cat /etc/os-release`):**
 Manjaro

**(5) Gnome Shell version:**
41

**(6) Pop Shell version (run `apt policy pop-shell` or provide the latest commit if building locally):**
Built from aur pop-shell-git. latest commit: https://github.com/pop-os/shell/commit/1fddaa8953a6554a83038bb5662662eb761eb361

**(7) Where was Pop Shell installed from:**
AUR pop shell git

**(8) Monitor Setup (2 x 1080p, 4K, Primary(Horizontal), Secondary(Vertical), etc):**
Main: 1080p horizontal 
2nd: 900P horizontal

**(9) Other Installed/Enabled Extensions:**
I have enabled only pop-shell for the test

**(10) Other Notes:**

https://user-images.githubusercontent.com/30802163/140230223-72f6e2a0-9d13-4cb4-a14e-bece5bf3644c.mp4

**Comment by leviport** [comment] 2021-11-03 23:17
Duplicate of https://github.com/pop-os/pop/issues/1894

Large changes to the applications overview in COSMIC are [in the works](https://github.com/pop-os/cosmic/pull/218), so we expect this bug to go away once those changes are implemented.

**Closed by leviport** 2021-11-03 23:17 UTC

**Comment by Sultech** [comment] 2021-11-04 01:12
will there be a way to keep the default application viewer in gnome

**Comment by leviport** [comment] 2021-11-04 14:11
Turning off the COSMIC extensions should get you to a more default GNOME, if that's what you really want. I really think you'll like our changes though.
