### ISSUE TITLE
Pop!_Shop doesn't tile properly

### ISSUE THREAD

**Issue by snugglej** [pop-os/shell#125] opened 2020-03-29 03:43 UTC
The pop!_shop on 19.10 doesn't tile properly and either goes outside the bounds of the screen if on the right side or covers over other windows if placed on the right side. I think this is due to the default window size and/or minimum size of the pop!_shop but I'm not 100% sure. *Let me know if I should move this over to the shop repository or if this is already fixed in 20.04*

**Picture of the issue**
![image](https://user-images.githubusercontent.com/17776110/77839733-f7f58900-7144-11ea-97a1-7d4ad0fc2681.png)

**OS INFO**
cat /etc/os-release
NAME="Pop!_OS"
VERSION="19.10"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Pop!_OS 19.10"
VERSION_ID="19.10"
HOME_URL="https://system76.com/pop"
SUPPORT_URL="http://support.system76.com"
BUG_REPORT_URL="https://github.com/pop-os/pop/issues"
PRIVACY_POLICY_URL="https://system76.com/privacy"
VERSION_CODENAME=eoan
UBUNTU_CODENAME=eoan
LOGO=distributor-logo-pop-os

**Comment by mmstick** [comment] 2020-03-30 05:58
Duplicate of #81

**Closed by mmstick** 2020-03-30 05:58 UTC
