### ISSUE TITLE
Empty space left behind after minimizing for some apps

### ISSUE THREAD

**Issue by lucaspallez** [pop-os/shell#411] opened 2020-06-09 18:32 UTC
**Distribution (run `cat /etc/os-release`):**
 Pop!_OS 20.04
 
 
**Related Application and/or Package Version (run `apt policy pop-shell` or provide the latest commit if building locally):**
From apt:
pop-shell: 0.1.0\~1589925465\~20.04~ff5f374

**Issue/Bug Description:**
In tiliing mode, empty space is left behind when minimizing some windows every time when using minimize button in top bar (it works properly when using for example dash to panel to minimize).
This happens with these apps and probably more that I don't know of:

-Spotify (deb)
-Programs using wine (deb)
-Discord (deb)
-Slack (deb)
-Lotion (Notion wrapper: https://github.com/puneetsl/lotion) (from source)
-Vnc Viewer (deb)
-VirtualBox (deb)
-Zoom (flatpak)

Maximizing the windows works, but when back to normal size the problem persists.
Turning tiling mode off and on again solves the problem.
Closing the app instead of minimizing it also removes the empty space.

**Steps to reproduce (if you know):**
Open one of these apps and minimize it, it should work the same as on my machine. Not modifications were made on my part to pop-shell.

**Comment by matguidi** [comment] 2020-06-11 20:37
Another app that has this problem is Enpass.

**Comment by jmmaranan** [comment] 2020-06-14 17:57
Duplicate of #309

**Comment by bvhme** [comment] 2020-06-16 13:33
I see this in Mattermost too. I've made in issue on their list as well: https://github.com/mattermost/desktop/issues/1325

**Comment by jmmaranan** [comment] 2020-06-16 22:03
@bvhme - the Mattermost minimize issue you described is also fixed in the dev_focal branch. Luckily, the reference PR or issue that one of the commenters described in mattermost/desktop#1325 would probably fix the close (x) button issue I am seeing in Mattermost display.

**Comment by jmmaranan** [comment] 2020-06-25 01:46
@lucaspallez - can you pull the latest apt-release and verify if it is fixed on your end?

**Comment by lucaspallez** [comment] 2020-06-25 11:15
It is indeed fixed! @jmmaranan
Thank you.

**Comment by jmmaranan** [comment] 2020-06-25 23:47
@lucaspallez - do you mind closing this issue?

**Comment by matguidi** [comment] 2020-06-26 08:39
> @lucaspallez - can you pull the latest apt-release and verify if it is fixed on your end?

Sorry, for those who use pop-shell in a non-Debian-based environment like me, is the release you refer to the same as the current dev_focal?

**Comment by jmmaranan** [comment] 2020-06-26 11:56
Hey @matguidi, it looks like the latest release package is coming from master_focal. The latest greatest tested QA code is in dev_focal.
```
pop-shell:
  Installed: 0.1.0~1593106249~20.04~f2ab34f
  Candidate: 0.1.0~1593106249~20.04~f2ab34f <-- (f2ab34f is the current master_focal commit as I'm typing this)
  Version table:
 *** 0.1.0~1593106249~20.04~f2ab34f 1001
       1001 http://ppa.launchpad.net/system76/pop/ubuntu focal/main amd64 Packages
       1001 http://ppa.launchpad.net/system76/pop/ubuntu focal/main i386 Packages
        100 /var/lib/dpkg/status
```

**Comment by matguidi** [comment] 2020-06-26 22:54
I have re-compiled pop-shell from the dev_focal branch and the issue seems to be solved, thanks!

**Closed** 2020-06-27 07:53 UTC

**Comment by jmmaranan** [comment] 2020-07-02 21:26
> @bvhme - the Mattermost minimize issue you described is also fixed in the dev_focal branch. Luckily, the reference PR or issue that one of the commenters described in [mattermost/desktop#1325](https://github.com/mattermost/desktop/issues/1325) would probably fix the close (x) button issue I am seeing in Mattermost display. [mattermost/desktop#1279](https://github.com/mattermost/desktop/pull/1279)

@bvhme - just want to follow-up that the flatpak version of mattermost, closing via (x) is fixed. The other windows will occupy its space.

**Comment by bvhme** [comment] 2020-07-03 13:08
It's resolved! The space is now used.

Awesome, thanks for all the great work on the shell. I love it every day! pop_OS is really the first time I ever considered an open source OS for desktop use, and I've not looked back!

**Comment by jmmaranan** [comment] 2020-07-03 14:07
Nice! You might want to help close that ticket too on Mattermost that you had opened? Thanks @bvhme

**Comment by jmmaranan** [comment] 2020-07-03 15:11
@bvhme, been distro-hopping since Breezy Badger (if anyone remembers that, lol) - glad you are enjoying the OS as much as I do. This is all great work from the team at System76! :)
