### ISSUE TITLE
Polish: Turn off stacking when last window is left in stack created by dragging

### ISSUE THREAD

**Issue by ghost** [pop-os/shell#1749] opened 2024-11-08 15:41 UTC
**(1) Issue/Bug Description:**
This is so there is no stack title bar is shown for a single window because then it is redundant (unless I'm missing something about pop-shell that makes it so that it isn't) and takes up space.

**(2) Steps to reproduce (if you know):**
1. Turn tiling mode / Tile Windows toggle on
2. Create a stack of two windows by dragging one window on top of the middle of another.
3. Remove the last window from the stack so that only one window is left in stack, either using the mouse or using shortcuts.

**(3) Expected behavior:**
Stacking mode shouldn't automatically be turned off.

**(4) Distribution (run `cat /etc/os-release`):**
Ultramarine Linux

**(5) Gnome Shell version:**
46

**(6) Pop Shell version (run `apt policy pop-shell` or provide the latest commit if building locally):**

```1.2.0^23.cfa0c55```

**(7) Where was Pop Shell installed from:**
Fedora Linux - updates repository

**(8) Monitor Setup (2 x 1080p, 4K, Primary(Horizontal), Secondary(Vertical), etc):**
Primary (Horizontal): 1600*900

**(9) Other Installed/Enabled Extensions:**
One Thing
AppIndicator and KStatusNotifierItem Support
windowNavigator

**(10) Other Notes:**

**Comment by leviport** [comment] 2024-11-08 16:10
Duplicate of https://github.com/pop-os/shell/issues/1501

**Closed as completed by leviport** 2024-11-08 16:10 UTC
