### ISSUE TITLE
Keyboard shortcuts do not apply after confirmed

### ISSUE THREAD

**Issue by jimpo** [pop-os/shell#924] opened 2021-04-05 13:26 UTC
**(1) Issue/Bug Description:**

When I run `make local-install`, it does not apply the keyboard shortcuts.

**(2) Steps to reproduce (if you know):**

Run `make local-install`, reset system, then do it again.

I believe it's a bug on [this line](https://github.com/pop-os/shell/blame/master/scripts/configure.sh#L9) in the configure script. That should be a 1.

**(3) Expected behavior:**

**(4) Distribution (run `cat /etc/os-release`):**
 
Ubuntu 20.04

**(5) Gnome Shell version:**

3.36.7

**(6) Pop Shell version (run `apt policy pop-shell` or provide the latest commit if building locally):**

**(7) Where was Pop Shell installed from:**

Cloned git, `make local-install`

**(8) Monitor Setup (2 x 1080p, 4K, Primary(Horizontal), Secondary(Vertical), etc):**

**(9) Other Installed/Enabled Extensions:**

**(10) Other Notes:**

**Comment by GeneralPoxter** [comment] 2021-04-07 14:50
I also experienced something similar to this after upgrade to GNOME 40.

Furthermore, it seems that pop shell's command to move windows from workspaces is entirely separate and buggier from GNOME's equivalent command.

**Comment by jmo707** [comment] 2021-04-08 22:19
I can confirm exactly what @GeneralPoxter reported. I'm on Arch Linux with Gnome 40. I'm using the official gnome-unstable repo packages.

**Comment by warber** [comment] 2021-04-09 10:15
Same here. (Ubuntu 20.04.2 LTS). Keyboard Shortcuts are not touched at all after `make local-install`

**Comment by KonstantMan** [comment] 2021-04-10 07:52
I can confirm that after updating to GNOME 40 on Arch most of the shortcuts don't work

**Comment by ChrisKeefe** [comment] 2021-04-18 19:33
OpenSUSE Tumbleweed here. Most shortcuts work on GNOME 40, but some critical ones don't.
- I am _not_ able to move between desktops without moving a window. (Super + Ctrl + up/down)
- I am _not_ able to snap left/right (Super + Ctrl + left/right)

- I am able to move a window to a new desktop (Super + Shift + up/down)
- I am able to move to the first or last desktop (home/end)
- Window size and position adjustments works fine.

**Comment by bertin0** [comment] 2021-04-19 18:03
I am affected by this too. Shortcuts for switching workspaces only work sometimes: I have to run `make local-install` followed by `Alt+f2 restart` multiple times to get them to work. They appear to override the default gnome ones anyways (I have the corresponding ones set in gnome settings), even though I have removed the `Ctrl+Super+J` /  `Ctrl+Super+K` bindings from the schemas file before running make.

**Comment by ChrisKeefe** [comment] 2021-04-19 18:54
It looks like there may be two separate issues here - OP is in regards to Ubuntu 20, while most of the other comments are from users whose Pop-Shell experience has broken with GNOME 40. I'm sorry for contributing to the clutter. 

For the maintainers: do you want me to write up a separate issue for GNOME 40 keyboard shortcut losses?

**Comment by GeneralPoxter** [comment] 2021-04-20 04:07
@ChrisKeefe Seems reasonable, I'll file a separate issue for this so OP can have his problems addressed as well. I was under the impression that the two might be related, but this seems not to be the case.

**Comment by apinter** [comment] 2022-05-03 15:55
The reason for this is that Pop - I think, never used it - is using a different layout for the workspaces. [In the code](https://github.com/pop-os/shell/blob/15e7acfc8d9e52389b251b22e2e596e39607ac2f/scripts/configure.sh#L74) you can see that it goes up and down, instead of left and right as upstream would. Not sure if anyone should expect a "fix" since it is really not broken, just works differently in Pop. You can add the bindings in the keyboard shortcuts yourself or modify the code to your needs, both is fairly simple.

**Comment by ChrisKeefe** [comment] 2022-05-03 21:05
I'd like to politely disagree, @apinter. I haven't checked recently, but at the time this issue was raised, these shortcuts were advertised in the Pop Shell documentation but did not work for GNOME 40 users. Whether you interpret this as a code bug or a documentation bug doesn't much matter - at the end of the day, advertised shortcuts failed to work, impairing the user experience.

Unless I'm mistaken, Pop is still released as a GNOME extension. As such, keyboard shortcut compatibility with GNOME seems like a reasonable expectation.

**Comment by mmstick** [comment] 2022-05-03 21:36
Compatibility is only guaranteed for the Pop session. Others have to run the local build script to have the same same shortcuts set. Anyway, this issue was resolved a year ago.

**Closed by mmstick** 2022-05-03 21:36 UTC
