### ISSUE TITLE
Unable to move windows between monitors with external monitor and tiling enabled

### ISSUE THREAD

**Issue by duboisf** [pop-os/shell#527] opened 2020-06-04 21:30 UTC
Here's an example where if tiling is enabled I can't use `Shift+Super+Right` to move the window to the right monitor (notice in the video that after I disable tiling it works):

![move_window_problem](https://user-images.githubusercontent.com/169247/83656600-bdb5c700-a58d-11ea-918f-c7c3af961781.gif)

```
NAME="Pop!_OS"
VERSION="20.04 LTS"
ID=pop
ID_LIKE="ubuntu debian"
PRETTY_NAME="Pop!_OS 20.04 LTS"
VERSION_ID="20.04"
HOME_URL="https://system76.com/pop"
SUPPORT_URL="http://support.system76.com"
BUG_REPORT_URL="https://github.com/pop-os/pop/issues"
PRIVACY_POLICY_URL="https://system76.com/privacy"
VERSION_CODENAME=focal
UBUNTU_CODENAME=focal
LOGO=distributor-logo-pop-os
```

**Comment by jacobgkau** [comment] 2020-09-02 14:05
Closing as a duplicate of https://github.com/pop-os/shell/issues/522. (This issue was opened earlier, but not in the correct repository.)

**Closed by jacobgkau** 2020-09-02 14:05 UTC
