### ISSUE TITLE
Are there any plans to implement scripting/saving/restoring/customizing window layouts?

### ISSUE THREAD

**Issue by IndianBoy42** [pop-os/shell#1288] opened 2021-12-01 04:57 UTC
I speak especially for the tiling window managers. Especially for power users, ultrawide users and anyone who uses many windows open. It can be hard/annoying to manually open everything and finagle everything into the layout. Even something simple like 3 windows side by side of equal width is nontrivial to achieve right now as window layout is represented by a binary tree, so resizing to get them all the same is pretty wonky, whether by hand or, even worse, by keyboard.

I'm not sure what form this feature should take finally, the most powerful would be a full scripting support (python, lua, something like that) that we can use to control everything about the windows open and the layout.
A more simple solution that would cover a decent amount would be to allow saving and restoring a workspace layout.

A few more related features:
 - Let us configure it to leave certain tiles empty when the window there closes, this may seem to go against TWM philosophy, but often I want to close the window and put a new window in its place, without messing up the window layout. 
     - For now I have to either close it, open a new window then rejig the layout back to where it was or
     - enable stacking on that tile, open the new window, hope it goes there or else i have to rejig anyway, then close the old window
 - More customization for where a new window opens, maybe I have a big stack and I want it to go there no matter what I am focusing now, maybe I would rather it just float as my layout is fine tuned and this window is probably temporary, etc.

I totally understand that you guys have a lot of other things to work on, I guess I just wanted to open up discussion about the design space.

**Comment by jacobgkau** [comment] 2021-12-22 20:48
Thank you for the feature request. I'm closing this as a duplicate of https://github.com/pop-os/shell/issues/735 (and https://github.com/pop-os/shell/issues/735).

**Closed by jacobgkau** 2021-12-22 20:48 UTC
