### ISSUE TITLE
Application menu scales wrong on 4k monitor

### ISSUE THREAD

**Issue by pflanzenandi** [pop-os/shell#1325] opened 2022-01-15 09:15 UTC
Application menu is zoomed in, full screen and missing folders on my 4k monitor (probably doesn't scale correctly).
If I unplug the monitor and use my laptop the application menu looks normal.

**4K monitor**
![1](https://user-images.githubusercontent.com/60046516/149616479-93452d4b-0151-4b68-8291-c3e9d85ea609.png)

**Laptop screen (1920*1200)**
![2](https://user-images.githubusercontent.com/60046516/149616481-23b4ed21-69e8-4287-8aa6-c06799a87ec2.png)

```
NAME="Pop!_OS"
VERSION="21.10"
ID=pop
ID_LIKE="ubuntu debian"
PRETTY_NAME="Pop!_OS 21.10"
VERSION_ID="21.10"
HOME_URL="https://pop.system76.com"
SUPPORT_URL="https://support.system76.com"
BUG_REPORT_URL="https://github.com/pop-os/pop/issues"
PRIVACY_POLICY_URL="https://system76.com/privacy"
VERSION_CODENAME=impish
UBUNTU_CODENAME=impish
LOGO=distributor-logo-pop-os

GNOME=40.4.0
```
```
Installed: 1.1.0~1642182148~21.10~21745c4
  Candidate: 1.1.0~1642182148~21.10~21745c4
  Version table:
 *** 1.1.0~1642182148~21.10~21745c4 1001
       1001 http://apt.pop-os.org/release impish/main amd64 Packages
       1001 http://apt.pop-os.org/release impish/main i386 Packages
        100 /var/lib/dpkg/status
```

**Monitor Setup**

![3](https://user-images.githubusercontent.com/60046516/149616374-6c38b766-d674-4a7d-8c82-c7ac1742c69f.png)

**Other Installed/Enabled Extensions:**
Fresh installation without anything else.

**Comment by leviport** [comment] 2022-01-18 16:16
Duplicate of https://github.com/pop-os/cosmic/issues/290

**Closed by leviport** 2022-01-18 16:16 UTC
