### ISSUE TITLE
Can't click inside IntelliJ in Tiling mode

### ISSUE THREAD

**Issue by dodalovic** [pop-os/shell#1320] opened 2022-01-13 21:39 UTC
Pop OS 21.10

When i tile IntelliJ IDEA with any other app, I can't focus IntelliJ window, either by clicking on it, or pressing shorcut for it (SUPER+H/L)

It works well in non tiling mode

**Comment by leviport** [comment] 2022-01-13 21:41
duplicate of https://github.com/pop-os/shell/issues/1312

**Closed by leviport** 2022-01-13 21:41 UTC
