### ISSUE TITLE
Cant make my dash transparent

### ISSUE THREAD

**Issue by lucianowayand** [pop-os/shell#1097] opened 2021-07-20 03:04 UTC
I recently changed to pop os, i really like every aspect of it except but the grey dash, i tried everything even broke my gnome-shell theme but with no sucess, pls someone help

![Captura de tela de 2021-07-20 00-03-51](https://user-images.githubusercontent.com/36968613/126255678-c14e123e-eefe-4450-af74-c72463646cb3.png)

I got all the other customizations working with no problem but this thing is bugging me so much

**Comment by mmstick** [comment] 2021-07-20 08:58
Duplicate of https://github.com/pop-os/cosmic/issues/143

**Closed by mmstick** 2021-07-20 08:58 UTC
