### ISSUE TITLE
Swiping through workspaces should respect natural scrolling setting

### ISSUE THREAD

**Issue by larsblumberg** [pop-os/shell#1105] opened 2021-07-23 12:44 UTC
**(1) Issue/Bug Description:**

Swiping through workspaces using 4 fingers swipe gesture doesn't respect the natural scrolling setting.

**(2) Steps to reproduce (if you know):**

1. Turn on "natural scrolling" in system settings > mouse & touchpad
2. Swiping with 4 fingers from the bottom to the top of the touchpad reveals the previous (above) workspace.

**(3) Expected behavior:**

2. With natural scrolling turned on, swiping with 4 fingers from the bottom to the top of the touchpad should reveal the next (below) workspace.

**(4) Distribution (run `cat /etc/os-release`):**
 
```ini
NAME="Pop!_OS"
VERSION="21.04"
ID=pop
[...]
```

**(5) Gnome Shell version:**

?

**(6) Pop Shell version (run `apt policy pop-shell` or provide the latest commit if building locally):**

```
pop-shell:
  Installed: 1.1.0~1626728027~21.04~9616931
  Candidate: 1.1.0~1626728027~21.04~9616931
  Version table:
 *** 1.1.0~1626728027~21.04~9616931 1001
       1001 http://ppa.launchpad.net/system76/pop/ubuntu hirsute/main amd64 Packages
       1001 http://ppa.launchpad.net/system76/pop/ubuntu hirsute/main i386 Packages
        100 /var/lib/dpkg/status
```

**(7) Where was Pop Shell installed from:**

Via system settings > os upgrade

**Comment by jacobgkau** [comment] 2021-07-23 13:52
Duplicate of https://github.com/pop-os/cosmic/issues/110.

**Closed by jacobgkau** 2021-07-23 13:52 UTC
