### ISSUE TITLE
When tiling is enabled, application icon still remains on launcher even after the application is closed

### ISSUE THREAD

**Issue by abhishekwl** [pop-os/shell#330] opened 2020-05-11 09:03 UTC
**Distribution (run `cat /etc/os-release`):**
NAME="Pop!_OS"
VERSION="20.04 LTS"
ID=pop
ID_LIKE="ubuntu debian"
PRETTY_NAME="Pop!_OS 20.04 LTS"
VERSION_ID="20.04"
HOME_URL="https://system76.com/pop"
SUPPORT_URL="http://support.system76.com"
BUG_REPORT_URL="https://github.com/pop-os/pop/issues"
PRIVACY_POLICY_URL="https://system76.com/privacy"
VERSION_CODENAME=focal
UBUNTU_CODENAME=focal
LOGO=distributor-logo-pop-os
 
 
**Related Application and/or Package Version (run `apt policy pop-shell` or provide the latest commit if building locally):**
pop-shell:
  Installed: 0.1.0~1588777613~20.04~387bebf
  Candidate: 0.1.0~1588777613~20.04~387bebf
  Version table:
 *** 0.1.0~1588777613~20.04~387bebf 1001
       1001 http://ppa.launchpad.net/system76/pop/ubuntu focal/main amd64 Packages
       1001 http://ppa.launchpad.net/system76/pop/ubuntu focal/main i386 Packages
        100 /var/lib/dpkg/status

**Issue/Bug Description:**
In the launcher, (with tiling enabled) a few applications upon being exit still have a dot below their respective icons indicating they are still running even after closing the application. I've checked if the processes are still active in the system monitor and they are not. However they still remain on the dock.
![Screenshot from 2020-05-11 14-25-04](https://user-images.githubusercontent.com/20264867/81543298-7cb60280-9393-11ea-8e65-54b4c84a7076.png)

**Steps to reproduce (if you know):**
I've encountered this with multiple applications such as Chrome, VirtualBox, Insomnia, MySQL workbench and so on. It's generally applicable to any application.
Steps to reproduce for VirtualBox:
1. Open VirtualBox Manager
2. Run a VM
3. Shut down the VM and close VirtualBox

**Expected behavior:**
Application icon shouldn't be present in the launcher as the application is closed.

**Other Notes:**
Not entirely sure but it sometimes I've observed that this happens when the application window is maximized

**Comment by timrichardson** [comment] 2020-05-12 23:48
I had a Chromium crash, and exactly the same thing happened, although I use dash to panel.

**Comment by lmirguet** [comment] 2020-05-14 16:47
The same problem occurs with the Zoom client.

**Comment by mmstick** [comment] 2020-05-14 22:29
Duplicate of #220

**Closed by mmstick** 2020-05-14 22:29 UTC
