### ISSUE TITLE
Opening two windows of an App and closing them at the same time keeps a ghost App and can freeze the system. Pop OS 20.04

### ISSUE THREAD

**Issue by algom** [pop-os/shell#328] opened 2020-05-09 15:30 UTC
**Distribution (run `cat /etc/os-release`):**
 NAME="Pop!_OS"
VERSION="20.04 LTS"
ID=pop
ID_LIKE="ubuntu debian"
PRETTY_NAME="Pop!_OS 20.04 LTS"
VERSION_ID="20.04"
HOME_URL="https://system76.com/pop"
SUPPORT_URL="http://support.system76.com"
BUG_REPORT_URL="https://github.com/pop-os/pop/issues"
PRIVACY_POLICY_URL="https://system76.com/privacy"
VERSION_CODENAME=focal
UBUNTU_CODENAME=focal
LOGO=distributor-logo-pop-os

Computer: Ryzen 3800X, NVIDIA 1660 Super
 
**Related Application and/or Package Version (run `apt policy pop-shell` or provide the latest commit if building locally):**
pop-shell:
  Installed: 0.1.0~1588777613~20.04~387bebf
  Candidate: 0.1.0~1588777613~20.04~387bebf
  Version table:
 *** 0.1.0~1588777613~20.04~387bebf 1001
       1001 http://ppa.launchpad.net/system76/pop/ubuntu focal/main amd64 Packages
       1001 http://ppa.launchpad.net/system76/pop/ubuntu focal/main i386 Packages
        100 /var/lib/dpkg/status
**Issue/Bug Description:**
Issue #220, #224 still persist in Pop OS 20.04 (Fresh install) up to date.
Having two windows open from a program (have tried it with Firefox, Chrome, Nautilus) and closing them at the same time causes a "ghost" app to remain on the dash (dot below the program). Moreover, right clicking on icon freezes the system for several seconds, up to 1 minute. Mouse can be still moved, but no input can be done with the keyboard, e.g. to terminate the app. After a while the system responds and Alt+F2, r. allows to continue and the "ghost" app dissapear.

**Steps to reproduce (if you know):**
How to replicate: Open Firefox (or Chrome, or Nautilus), open a new Firefox window, close both windows from Dash (Quit both windows) the application seems to continue running and no other window can be open unless launched from the Terminal.
Disable/re-enable Pop-shell extension does not do anything. Can only be "rescued" by Alt+F2, r.
The same happens with Chrome and Nautilus.

Moreover, doing a right click on the icon (Firefox or Chrome) freezes my computer for a several seconds, mouse can be moved but no commands can be executed with the keyboard. Afterwards it recovers and Alt+F2, r, puts everything back to normal.

**Expected behavior:**
Quiting the apps, should quit the apps, and right click should not freeze the system.

**Comment by zeparu** [comment] 2020-05-09 21:35
same here on manjaro, closing them at the same time is not even necessary, sometimes "ghost apps" show up in the dock minutes after i closed the program
happens *very* regularly here

**Comment by leviport** [comment] 2020-05-11 15:17
Duplicate of https://github.com/pop-os/shell/issues/220

**Closed by leviport** 2020-05-11 15:17 UTC
