### ISSUE TITLE
Pop launcher doesn't do anything

### ISSUE THREAD

**Issue by ethanbowering24** [pop-os/shell#1701] opened 2024-02-26 15:21 UTC
**Issue/Bug Description:**
Pop launcher is always empty, can't launch anything.

![Screenshot from 2024-02-26 10-20-08](https://github.com/pop-os/shell/assets/61316561/f9aefe98-dc38-4bb8-938e-20d717a3213d)

**Steps to reproduce (if you know):**
Press super + /, and then try to use launcher

**Expected behaviour:**
Can launch programs and such.

**Distribution:**
 Fedora 39

**Gnome Shell version:**
45.4

**Pop Shell version:**
1.2.0^21.aafc94

**Where was Pop Shell installed from:**
dnf

**Monitor Setup (2 x 1080p, 4K, Primary(Horizontal), Secondary(Vertical), etc):**
1920x1080 laptop 

**Other Installed/Enabled Extensions:**
Clipboard indicator, caffeine

**Other Notes:**
Same issue described in [this thread](https://discussion.fedoraproject.org/t/pop-shell-launcher-not-working-f39-gnome/101296).

**Comment by leviport** [comment] 2024-02-26 15:28
I believe this is a duplicate of https://github.com/pop-os/shell/issues/1693

**Closed as completed by leviport** 2024-02-26 15:28 UTC

**Comment by ethanbowering24** [comment] 2024-02-26 15:58
> I believe this is a duplicate of #1693

Thanks. I swear I did look for a duplicate before posting but couldn't find it.
