### ISSUE TITLE
Tiling per workspace  . Ex . Tile is on workspace 1 . and Tiling is off in workspace 2.

### ISSUE THREAD

**Issue by meliodas1107** [pop-os/shell#1046] opened 2021-07-02 10:24 UTC
**(1) Issue/Bug Description:**
Currently if i enable tiling while using one workspace that I use for coding for instance , and if I switch to a different workspace ,(which I didnt intend to use tiling on )will also be tiled . Ill have to turn off tiling for it to turn back to normal . And then if i switch back to the work i was doing , I will have to manuall enable the tiling again.

**(2) Steps to reproduce (if you know):**
1) Open multiple windows in 2 workspaces . 
2) turn on tiling in one of it .& switch to the other .
3) The other workspace will also be tiled . 

**(3) Expected behavior:**

Tiling happens only in the workspace I invoked it .  Maybe we could make a list with on and off for each workspace , representing the state of tiling ?

**(4) Distribution (run `cat /etc/os-release`):**
 NAME="Pop!_OS"
VERSION="21.04"
ID=pop
ID_LIKE="ubuntu debian"
PRETTY_NAME="Pop!_OS 21.04"
VERSION_ID="21.04"
HOME_URL="https://pop.system76.com"
SUPPORT_URL="https://support.system76.com"
BUG_REPORT_URL="https://github.com/pop-os/pop/issues"
PRIVACY_POLICY_URL="https://system76.com/privacy"
VERSION_CODENAME=hirsute
UBUNTU_CODENAME=hirsute
LOGO=distributor-logo-pop-os

**(5) Gnome Shell version:**
 
3.38.5

**(6) Pop Shell version (run `apt policy pop-shell` or provide the latest commit if building locally):**

pop-shell:
  Installed: 1.1.0~1625023507~21.04~976106e
  Candidate: 1.1.0~1625023507~21.04~976106e
  Version table:
 *** 1.1.0~1625023507~21.04~976106e 1001
       1001 http://ppa.launchpad.net/system76/pop/ubuntu hirsute/main amd64 Packages
       1001 http://ppa.launchpad.net/system76/pop/ubuntu hirsute/main i386 Packages
        100 /var/lib/dpkg/status

**(7) Where was Pop Shell installed from:**

Pop os 

**(8) Monitor Setup (2 x 1080p, 4K, Primary(Horizontal), Secondary(Vertical), etc):**

1x 1920x1080 16:9 Laptop screen 14'

**(9) Other Installed/Enabled Extensions:**

**(10) Other Notes:**

**Comment by Kartonrealista** [comment] 2021-07-02 17:10
#380

**Comment by mmstick** [comment] 2021-07-02 17:11
Duplicate of #380

**Closed by mmstick** 2021-07-02 17:11 UTC
