### ISSUE TITLE
Active Hint frame stays visible when minimizing only window on workspace

### ISSUE THREAD

**Issue by renestalder** [pop-os/shell#485] opened 2020-08-07 08:45 UTC
**Distribution (run `cat /etc/os-release`):**

```
NAME="Pop!_OS"
VERSION="20.04 LTS"
ID=pop
ID_LIKE="ubuntu debian"
PRETTY_NAME="Pop!_OS 20.04 LTS"
VERSION_ID="20.04"
HOME_URL="https://pop.system76.com"
SUPPORT_URL="https://support.system76.com"
BUG_REPORT_URL="https://github.com/pop-os/pop/issues"
PRIVACY_POLICY_URL="https://system76.com/privacy"
VERSION_CODENAME=focal
UBUNTU_CODENAME=focal
LOGO=distributor-logo-pop-os
```
 
**Related Application and/or Package Version (run `apt policy pop-shell` or provide the latest commit if building locally):**

```
pop-shell:
  Installed: 0.1.0~1593273798~20.04~9e8ab29
  Candidate: 0.1.0~1596678676~20.04~990c626
  Version table:
     0.1.0~1596678676~20.04~990c626 1001
       1001 http://ppa.launchpad.net/system76/pop/ubuntu focal/main amd64 Packages
       1001 http://ppa.launchpad.net/system76/pop/ubuntu focal/main i386 Packages
 *** 0.1.0~1593273798~20.04~9e8ab29 100
        100 /var/lib/dpkg/status
```

**Issue/Bug Description:**

When 'Show Active Hint' is activated and the only window on a workspace is minimized, the border of the active hint will stay visible in place where the window was.

**Steps to reproduce (if you know):**

1. Activate 'Tile Windows'
2. Activate 'Show active hint'
3. Open a window, e.g. Firefox browser, on a workspace where currently no other window is visible.
4. Minimize the application

**Expected behavior:**

The active hint border should be hidden/minimized together with the window.

**Other Notes:**

The issue doesn't happen when there are other windows on the workspace as the focus immediately switches to the next window, thus the active hint is moved.

**Comment by jmmaranan** [comment] 2020-08-07 16:18
Duplicate of #469

**Closed** 2020-08-07 16:30 UTC
