### ISSUE TITLE
Tiling Windows toggle will not be switched on/off when using SUPER+Y key kombination

### ISSUE THREAD

**Issue by Spicysauced** [pop-os/shell#868] opened 2021-02-04 14:33 UTC
**Distribution (run `cat /etc/os-release`):**
 
 PopOS 20.10
 
**Related Application and/or Package Version (run `apt policy $PACKAGE NAME`):**

Status bar -> Tiling Windows Miniapp (Dont know how its called)

**Issue/Bug Description:**

Graphical toggle related to tiling windows will not switch on/off when using default key combination

**Steps to reproduce (if you know):**

Press Super + y. Tiling windows is now on.
Press Tiling windows icon in the statusbar.
Observe graphical toggle "Tile Windows" is still off.

**Expected behavior:**

Graphical toggle "Tile Windows" should respond to actual state of the feature.

**Other Notes:**

**Comment by bflanagin** [comment] 2021-02-04 15:07
Duplicate of #856

**Closed by bflanagin** 2021-02-04 15:07 UTC
