### ISSUE TITLE
Tile width changing on tile close.

### ISSUE THREAD

**Issue by shaun-ba** [pop-os/shell#467] opened 2020-07-27 08:52 UTC
**Distribution (run `cat /etc/os-release`):**
 
Ubuntu 20.04
 
 
**Related Application and/or Package Version (run `apt policy pop-shell` or provide the latest commit if building locally):**

4d6bbb6c443349d1199cebe2c02a29a429d3a6d6

**Issue/Bug Description:**

When tile furthest to the right (was a browser window), launches a popup it splits the tile in half horizontally. When the popup is closed the width of the tile changes to make it much smaller, very very annoying!

**Steps to reproduce (if you know):**

As above, I have4 columns of tiles with the furthest right taking up about 33% of the screen

**Expected behavior:**

Tiles (or columns mainly) remain the size you make them!

**Other Notes:**

Screen size 5120 x 1440

**Comment by jmmaranan** [comment] 2020-07-29 00:22
@shaun-ba - do you have a screenshot and what type of browser popup?

**Comment by shaun-ba** [comment] 2020-07-31 11:57
.

**Comment by jmmaranan** [comment] 2020-07-31 18:30
@shaun-ba - I thought the default is always horizontal split. I sometimes drag a window on upper or lower half of another window if I want a vertical split.

Anyway, would you please share your screenshot just to get an idea:
> When the popup is closed the width of the tile changes to make it much smaller,

**Comment by shaun-ba** [comment] 2020-07-31 18:58
.

**Comment by jmmaranan** [comment] 2020-07-31 20:13
@shaun-ba - I re-read your issue description again. Unfortunately, preserving the window state size during re-tile (toggle or closing of one of the windows) is not supported - it will not go back to 33%. It will always try to resize to half of the current split. If you have 4 columns (that would I think be going back to 25% each)

**Comment by shaun-ba** [comment] 2020-08-01 06:22
.

**Comment by jmmaranan** [comment] 2020-08-01 15:38
Thanks for the clip. 

> Windows do not vertically split when dropped on bottom half

Agree, because the default is it will split horizontally. If you already have two windows side by side, dragging a third one on top of either of the two will split just fine. If you only have two windows, use the <Super + O> to toggle the current active window's orientation.

> When you touch the far right border of a window it make a mess of the split, this occurred numerous times for me because of the scrollbar on a browser and slightly missing it, reorganising my whole desktop

If at all possible, since you have a big display, maybe you can change the gap to 3 or 4. Click the Tile icon on the status bar, to bring up a menu to adjust the gap sizes. Hopefully that will help. 

I use the physical scrollbar too at times, to control what I am reading on the screen, but since I just have dual monitors, I cannot replicate this even if I drag the right edges explicitly.

> Not sure if its related to this extension but the dash to dock is buggy with it, I need to do more testing there i guess

Agree, I compensated for that using the Intelligent Autohide sub-settings on Dash-To-Dock as below.
![image](https://user-images.githubusercontent.com/348125/89104928-dce49f80-d3ea-11ea-901b-84bd49d779cc.png)

**Comment by jmmaranan** [comment] 2020-08-01 15:53
I also noticed in your `apt-policy pop-shell` response that you are using the `stacking` branch which is not the one that is released. 

> 4d6bbb6

There might be bugs there.

**Comment by shaun-ba** [comment] 2020-08-02 07:28
.

**Comment by shaun-ba** [comment] 2020-08-02 08:05
.

**Comment by mmstick** [comment] 2020-09-06 06:24
Reopen with instructions to reproduce if this still occurs on master

**Closed by mmstick** 2020-09-06 06:24 UTC
