### ISSUE TITLE
Tiling dont works

### ISSUE THREAD

**Issue by MiF36rus** [pop-os/shell#101] opened 2020-03-24 08:12 UTC
Im install this extention, it runs, but dont tile windows.
What works:
* Show active hint
* Show /Dont show window titles
* Some hot keys works(Maximize,minimize,Files,Lock screen,Close window)
* Window Management Mode(it highlights windows, but does nothing with them)

OS: Pop!_OS 19.10 x86_64 
Kernel: `Linux 5.3.0-7642-generic #34~1584408018~19.10~21df4b1-Ubuntu SMP Tue Mar 17 13:38:51 UTC  x86_64 x86_64 x86_64 GNU/Linux`
DE: GNOME 3.34.3
Resolution: 1920x1080, 2560x1440

**Comment by Gryzor** [comment] 2020-03-24 11:23
How did you install this? Did you run the script?

**Comment by WatchMkr** [comment] 2020-03-24 12:26
This will be fixed soon. Duplicate of #99

**Closed by WatchMkr** 2020-03-24 12:26 UTC
