### ISSUE TITLE
Overlapping default keyshortcuts executing in aribitary order

### ISSUE THREAD

**Issue by jsj1027** [pop-os/shell#286] opened 2020-05-05 04:49 UTC
**Distribution (run `cat /etc/os-release`):**
 NAME="Pop!_OS"
VERSION="20.04 LTS"
ID=pop
ID_LIKE="ubuntu debian"
PRETTY_NAME="Pop!_OS 20.04 LTS"
VERSION_ID="20.04"
HOME_URL="https://system76.com/pop"
SUPPORT_URL="http://support.system76.com"
BUG_REPORT_URL="https://github.com/pop-os/pop/issues"
PRIVACY_POLICY_URL="https://system76.com/privacy"
VERSION_CODENAME=focal
UBUNTU_CODENAME=focal
LOGO=distributor-logo-pop-os 
**_Single Laptop Monitor_**(May be important)
 
**Related Application and/or Package Version (run `apt policy $PACKAGE NAME`):**
Default keyboard shortcuts

**Issue/Bug Description:**
The default keyboard shortcuts for splitting windows on left/right and switching focus to left/right monitor conflict with each other respectively. Leading to a difference in which shortcut is activated. 

For switching focus and splitting on left the shortcut is Ctrl+Super+Left. Activation causes the window to split on left. And does not cause the monitor to shift focus as there is only 1 monitor.

However for switching focus and splitting on right the shortcut is Ctrl+Super+Right. In this case, activation causes the focus to attempt to go to the right window. However there is no right window and it is a weird user experience that it doesn't mirror what happens with Ctrl+Super+Left.

**Steps to reproduce (if you know):**
Upgrade from 19.10 to 20.04 with default shortcuts.
This may also happen with the default shortcuts on 20.04 however I did not install from scratch so I do not know.

**Expected behavior:**
The window splits right when using Ctrl+Super+Right, because that was the behaviour during 19.10.

**Other Notes:**
Changing window focus left and right should be remapped to Ctrl+Alt+Left/Right or Shift+Alt+Left/Right, as from my investigation both key combinations are not in use by default.

**Comment by mmstick** [comment] 2020-05-06 18:16
Duplicate of #241

**Closed by mmstick** 2020-05-06 18:16 UTC
