### ISSUE TITLE
Option to disable stacking

### ISSUE THREAD

**Issue by mbana** [pop-os/shell#1491] opened 2022-07-01 11:20 UTC
**(1) Issue/Bug Description:**

I would like to disable the stack feature. I personally find it annoying and rarely use it.

**(2) Steps to reproduce (if you know):**

Not applicable.

**(3) Expected behavior:**

In system tray icon or in the gnome extension settings dialog, I would like to see an option to disable stacking. Just like there is a way to disable tiling in the system tray icon.

**(4) Distribution (run `cat /etc/os-release`):**
 
```sh
cat /etc/os-release               
NAME="Fedora Linux"
VERSION="36 (Workstation Edition)"
ID=fedora
VERSION_ID=36
VERSION_CODENAME=""
PLATFORM_ID="platform:f36"
PRETTY_NAME="Fedora Linux 36 (Workstation Edition)"
ANSI_COLOR="0;38;2;60;110;180"
LOGO=fedora-logo-icon
CPE_NAME="cpe:/o:fedoraproject:fedora:36"
HOME_URL="https://fedoraproject.org/"
DOCUMENTATION_URL="https://docs.fedoraproject.org/en-US/fedora/f36/system-administrators-guide/"
SUPPORT_URL="https://ask.fedoraproject.org/"
BUG_REPORT_URL="https://bugzilla.redhat.com/"
REDHAT_BUGZILLA_PRODUCT="Fedora"
REDHAT_BUGZILLA_PRODUCT_VERSION=36
REDHAT_SUPPORT_PRODUCT="Fedora"
REDHAT_SUPPORT_PRODUCT_VERSION=36
PRIVACY_POLICY_URL="https://fedoraproject.org/wiki/Legal:PrivacyPolicy"
VARIANT="Workstation Edition"
VARIANT_ID=workstation
```

**(5) Gnome Shell version:**

```
$ gnome-shell --version                
GNOME Shell 42.2
```

**(6) Pop Shell version (run `apt policy pop-shell` or provide the latest commit if building locally):**

```sh
$ dnf info gnome-shell-extension-pop-shell
Installed Packages
Name         : gnome-shell-extension-pop-shell
Version      : 1.2.0^6.af192b4
Release      : 1.fc36
Architecture : noarch
Size         : 400 k
Source       : gnome-shell-extension-pop-shell-1.2.0^6.af192b4-1.fc36.src.rpm
Repository   : @System
From repo    : fedora
Summary      : GNOME Shell extension for advanced tiling window management
URL          : https://github.com/pop-os/shell
License      : GPLv3
Description  : Pop Shell is a keyboard-driven layer for GNOME Shell which allows for quick and
             : sensible navigation and management of windows.  The core feature of Pop Shell
             : is the addition of advanced tiling window management - a feature that has been
             : highly-sought within our community.  For many - ourselves included - i3wm has
             : become the leading competitor to the GNOME desktop.
```

**(7) Where was Pop Shell installed from:**

Fedora 36 repository.

**(8) Monitor Setup (2 x 1080p, 4K, Primary(Horizontal), Secondary(Vertical), etc):**

```sh
$ xrandr --listmonitors                       
Monitors: 2
 0: +*DisplayPort-1 3440/797x1440/334+0+0  DisplayPort-1
 1: +DisplayPort-0 3440/797x1440/334+3440+0  DisplayPort-0
```

**(9) Other Installed/Enabled Extensions:**

Not applicable.

**(10) Other Notes:**

Not applicable.

**Comment by leviport** [comment] 2022-07-01 15:26
I believe this is a duplicate of https://github.com/pop-os/shell/issues/965

**Closed as completed by leviport** 2022-07-01 15:26 UTC
