### ISSUE TITLE
Conflict between dash to panel extension and pop-shell

### ISSUE THREAD

**Issue by protodrew** [pop-os/shell#960] opened 2021-05-01 22:20 UTC
**(1) Issue/Bug Description:**

Conflict between dash to panel extension and pop-shell where if intellihide is enabled and device suspends, sometimes on re-entry the windows will act as if the panel is shown at all times leaving a large gap at the top.

**(2) Steps to reproduce (if you know):**

install the dash to panel extension and enable intellihide

wait for device to suspend

**(3) Expected behavior:**

on re-entry windows take up entirety of screen

**(4) Distribution (run `cat /etc/os-release`):**
 
Pop_OS 20.10

**(5) Gnome Shell version:**

3.38.3

**(6) Pop Shell version (run `apt policy pop-shell` or provide the latest commit if building locally):**

```   1.1.0~1619554528~20.10~42e8ac0 1001
       1001 http://ppa.launchpad.net/system76/pop/ubuntu groovy/main amd64 Packages
       1001 http://ppa.launchpad.net/system76/pop/ubuntu groovy/main i386 Packages
        100 /var/lib/dpkg/status```


**(7) Where was Pop Shell installed from:**

came with distro

**(8) Monitor Setup (2 x 1080p, 4K, Primary(Horizontal), Secondary(Vertical), etc):**

2x1080p 15 in

**(9) Other Installed/Enabled Extensions:**

Dash to panel (tested to ensure this is what's causing the conflict)

**Comment by ccwky11** [comment] 2021-05-02 23:19
Seconded, this issue also occurs in Manjaro Linux (both unstable and stable branches) this will occur anytime the windows need to be arranged and the panel may appear (on suspend, hibernate, or when switching display orientation for example) this is occuring with the AUR git version of pop-shell. It also occurs in both Wayland and X11 instances on gnome shell 40 down to at least 3.36. My current device is a single display, so it does not appear to be dependent on multiple displays. This issue will also occur with the on screen keyboard, but adding caribou to the floating window exceptions does solve the issue, finding a way to do so for dash to panel may similarly solve the issue.

**Comment by philmmanjaro** [comment] 2021-05-14 07:01
See here: https://gitlab.com/hrdwrrsk/AdwMod-theme/-/merge_requests/9

**Comment by mmstick** [comment] 2021-06-07 21:38
Duplicate of #880

**Closed by mmstick** 2021-06-07 21:38 UTC
