### ISSUE TITLE
Launcher: doesn't show photogimp or xampp

### ISSUE THREAD

**Issue by antoniocbarbosa** [pop-os/shell#1017] opened 2021-06-21 13:53 UTC
**(1) Issue/Bug Description:** After pop-shell update, if you search for photogimp or xampp, it doesn't show the programs. But if searching in the app menu shows.

The gimp was installed via flatpak and I added the photogimp patch to it, xampp was installed with the command sudo ./"installer_name" in the opt/lampp directory.

[Photogimp](https://github.com/Diolinux/PhotoGIMP)

**(2) Steps to reproduce (if you know):** Have the gimp with the photogimp patch and xampp, then search for photogimp or xampp.

After update:

![Screenshot from 2021-06-21 10-45-55](https://user-images.githubusercontent.com/50782838/122773153-78d6fe00-d27e-11eb-91f0-72d9d481d91e.png)

![Screenshot from 2021-06-21 10-45-59](https://user-images.githubusercontent.com/50782838/122773162-7bd1ee80-d27e-11eb-95fc-027b8c63e223.png)

**(3) Expected behavior:**

Before update:

![Screenshot from 2021-06-21 10-38-39](https://user-images.githubusercontent.com/50782838/122773200-84c2c000-d27e-11eb-99e8-9bd49c4de388.png)

![Screenshot from 2021-06-21 10-38-55](https://user-images.githubusercontent.com/50782838/122773209-87251a00-d27e-11eb-99e7-1294e7314d64.png)

**(4) Distribution (run `cat /etc/os-release`):** Pop!_OS 20.10

**(5) Gnome Shell version:** 3.38.3

**(6) Pop Shell version (run `apt policy pop-shell` or provide the latest commit if building locally):** ```1.1.0-1624036583-20.10-93634d6```

**(7) Where was Pop Shell installed from:** Pop!_OS PPA

**(8) Monitor Setup (2 x 1080p, 4K, Primary(Horizontal), Secondary(Vertical), etc):** 1x 720p

**(9) Other Installed/Enabled Extensions:**

![Screenshot from 2021-06-21 09-35-15](https://user-images.githubusercontent.com/50782838/122773602-de2aef00-d27e-11eb-9f62-23633dd36041.png)

**(10) Other Notes:** pop-shell version before upgrade `1.1.0~1623101914~20.10~df8b27b`

**Comment by leviport** [comment] 2021-06-21 15:52
I believe this may be a duplicate of https://github.com/pop-os/shell/issues/997

A fix for that was made and is still undergoing regression testing. It should be available pretty soon.

**Comment by jacobgkau** [comment] 2021-06-21 16:03
> I believe this may be a duplicate of #997

I think you meant #1008?

**Comment by leviport** [comment] 2021-06-21 16:06
Yep, you're right. I got mixed up since #997 uses gimp as an example. Thanks

**Comment by leviport** [comment] 2021-06-21 20:05
@antoniocbarbosa the fix is being worked on here: https://github.com/pop-os/shell/pull/1018

**Comment by jacobgkau** [comment] 2021-06-21 20:22
Fixed by https://github.com/pop-os/shell/pull/1018.

**Closed by jacobgkau** 2021-06-21 20:22 UTC
