### ISSUE TITLE
Ignore preferred sizes when in tiling mode

### ISSUE THREAD

**Issue by akainth015** [pop-os/shell#440] opened 2020-06-28 19:48 UTC
**Distribution (run `cat /etc/os-release`):**
~~~
NAME="Pop!_OS"
VERSION="20.04 LTS"
ID=pop
ID_LIKE="ubuntu debian"
PRETTY_NAME="Pop!_OS 20.04 LTS"
VERSION_ID="20.04"
HOME_URL="https://system76.com/pop"
SUPPORT_URL="http://support.system76.com"
BUG_REPORT_URL="https://github.com/pop-os/pop/issues"
PRIVACY_POLICY_URL="https://system76.com/privacy"
VERSION_CODENAME=focal
UBUNTU_CODENAME=focal
LOGO=distributor-logo-pop-os
~~~
 
 
 
**Related Application and/or Package Version (run `apt policy pop-shell` or provide the latest commit if building locally):**
~~~
pop-shell:
  Installed: 0.1.0~1593106249~20.04~f2ab34f
  Candidate: 0.1.0~1593106249~20.04~f2ab34f
  Version table:
 *** 0.1.0~1593106249~20.04~f2ab34f 1001
       1001 http://ppa.launchpad.net/system76/pop/ubuntu focal/main amd64 Packages
       1001 http://ppa.launchpad.net/system76/pop/ubuntu focal/main i386 Packages
        100 /var/lib/dpkg/status
~~~

**Issue/Bug Description:**
When using applications like the GNOME terminal, the suggested size they provide is used, leading to an inconsistent size among adjacently tiled windows. I have also noticed this with the settings panel in some applications, where the size is configurable but a contextually awkward dimension is chosen instead.

**Steps to reproduce (if you know):**
Open at least 2 windows next to each other (I use Firefox and Terminal)

**Expected behaviour:**
The tiled windows should have consistent sizes, and the window's preferred size should be ignored. If this turns out to be controversial behaviour, it may be preferable to make it an option to ignore the size suggested by the window.

**Other Notes:**
I [opened a similar issue on the GNOME terminal repository](https://gitlab.gnome.org/GNOME/gnome-terminal/-/issues/282), which clarified that the source of the issue is how the shell is respecting the preferred size even though it shouldn't.

**Comment by mmstick** [comment] 2020-06-28 20:55
I'm not aware of any way to do this with GNOME Shell's extension API, without creating patches for GNOME Shell to do this.

**Comment by akainth015** [comment] 2020-07-01 03:59
@mmstick would it instead be possible to adapt the tiling to the window's preferred size? That is, instead of the terminal window expanding to fill the extra space, the application below (or to the right, wherever the extra space may be) can be moved closer to the terminal, and made taller (or wider) as appropriate.

I am not familiar with the GNOME Shell Extensions API, can you please explain why windows without a preferred size can be coerced to a different dimension, but ones with a preferred size defined cannot? Is it a special case explicitly disallowed by the shell?

**Comment by mmstick** [comment] 2020-07-01 04:41
There is already an open issue for this, but it still won't solve every case. Applications will inevitably ask for more than could be allotted to either branch of a fork at a certain point. Compensations only work if there is there some slack to compensate with. So it's always going to be ideal for developers to create applications which work well in constrained environments, and tiling window managers at large.

Closing as this is a duplicate of issues #85 and #66 

As for the other thing:

GNOME Shell gives us access to `Meta.Window` objects representing each window on the desktop. The `Meta.Window` class has two methods for moving and resizing windows: `move_frame(user_op: bool, x: number, y: number)` and `move_resize_frame(user_op: bool, x: number, y: number, width: number, height: number)`.

GNOME Shell will automatically adjust your inputs to adhere to WM hints defined by the application. There's no guarantee that a window will be the same size or position as was requested. There are no parameters to control this behavior. So the problem isn't in how Pop Shell calculates rectangles of each fork and their branches, but whether or not GNOME can do what we ask it to do.

In the case of GNOME Terminal, the problem is that it defines a WM_HINT stating that the height and width must be in increments of a certain number of pixels. A calculated area for a window is very rarely going to coincide with this behavior.

**Closed by mmstick** 2020-07-01 04:41 UTC

**Comment by akainth015** [comment] 2020-07-01 17:10
Thanks @mmstick, that makes it much clearer for me! Do you think it would be a good idea to make an issue [upstream](https://gitlab.gnome.org/GNOME/gnome-shell) to add an optional flag to the `resize_frame` method (assuming one exists) to ignore all hints provided by the window?
