### ISSUE TITLE
Steam window is taking too much space with auto-tilling on

### ISSUE THREAD

**Issue by Booteille** [pop-os/shell#261] opened 2020-05-03 16:06 UTC
**Distribution (run `cat /etc/os-release`):**
 NAME="Pop!_OS"
VERSION="20.04 LTS"
ID=pop
ID_LIKE="ubuntu debian"
PRETTY_NAME="Pop!_OS 20.04 LTS"
VERSION_ID="20.04"
HOME_URL="https://system76.com/pop"
SUPPORT_URL="http://support.system76.com"
BUG_REPORT_URL="https://github.com/pop-os/pop/issues"
PRIVACY_POLICY_URL="https://system76.com/privacy"
VERSION_CODENAME=focal
UBUNTU_CODENAME=focal
LOGO=distributor-logo-pop-os
 
 
**Related Application and/or Package Version (run `apt policy pop-shell` or provide the latest commit if building locally):**
pop-shell:
  Installé : 0.1.0~1588274983~20.04~586efcc
  Candidat : 0.1.0~1588274983~20.04~586efcc
 Table de version :
 *** 0.1.0~1588274983~20.04~586efcc 1001
       1001 http://ppa.launchpad.net/system76/pop/ubuntu focal/main amd64 Packages
       1001 http://ppa.launchpad.net/system76/pop/ubuntu focal/main i386 Packages
        100 /var/lib/dpkg/status

**Issue/Bug Description:**
The steam window is always truncated when auto-tilling is on and the window is on the right side.
Here are screenshots:

When on the left of the screen:
![Capture d’écran de 2020-05-03 18-05-17](https://user-images.githubusercontent.com/2203721/80919132-af934180-8d68-11ea-9068-b1337377904a.png)

When on the right of the screen:
![Capture d’écran de 2020-05-03 17-59-42](https://user-images.githubusercontent.com/2203721/80919025-0b10ff80-8d68-11ea-8e82-de0599d62208.png)

**Steps to reproduce (if you know):**
Just open steam and activate auto-tilling.
Then open a second window.

**Expected behavior:**
Steam should not take more than the half width of the screen.

**Other Notes:**

**Comment by mmstick** [comment] 2020-05-04 13:17
Duplicate of #85

**Closed by mmstick** 2020-05-04 13:17 UTC
