### ISSUE TITLE
"Launch and Switch applications" shortcut is not configurable

### ISSUE THREAD

**Issue by rodrigoreyes79** [pop-os/shell#322] opened 2020-05-08 15:26 UTC
**Distribution (run `cat /etc/os-release`):**
NAME="Pop!_OS"
VERSION="20.04 LTS"
ID=pop
ID_LIKE="ubuntu debian"
PRETTY_NAME="Pop!_OS 20.04 LTS"
VERSION_ID="20.04"
HOME_URL="https://system76.com/pop"
SUPPORT_URL="http://support.system76.com"
BUG_REPORT_URL="https://github.com/pop-os/pop/issues"
PRIVACY_POLICY_URL="https://system76.com/privacy"
VERSION_CODENAME=focal
UBUNTU_CODENAME=focal
LOGO=distributor-logo-pop-os
 
**Related Application and/or Package Version (run `apt policy pop-shell` or provide the latest commit if building locally):**
op-shell:
  Installed: 0.1.0\~1588777613\~20.04\~387bebf
  Candidate: 0.1.0\~1588777613\~20.04\~387bebf
  Version table:
 *** 0.1.0\~1588777613\~20.04\~387bebf 1001
       1001 http://ppa.launchpad.net/system76/pop/ubuntu focal/main amd64 Packages
       1001 http://ppa.launchpad.net/system76/pop/ubuntu focal/main i386 Packages
        100 /var/lib/dpkg/status

**Issue/Bug Description:**
Launcher shortcut does not appear in the shortcut configuration.

**Steps to reproduce (if you know):**
![image](https://user-images.githubusercontent.com/3924426/81420766-0fe20480-9116-11ea-9723-67b99f55704a.png)

**Expected behavior:**
"Launch and Switch applications" option should appear in the Navigate applications and Windows section of the shortcuts configuration.

**Comment by alpakaxaxa** [comment] 2020-05-09 23:22
Do you know a workaround for this issue? I tried to find out the terminal command to start the application launcher so I could make a custom command but I was unable to find it.

**Comment by koylio** [comment] 2020-05-12 08:56
The keybinding is set in the schema, and can modified with dconf. I set it to "Super" and "-" since it's in the same physical location as english keyboard has the slash, and easy to access. With my keyboard layout the slash is under shift, so using launcher doesn't work at all with default keybinding. Running command below worked for me, not running Pop!_OS though. If Pop!_OS has the schema installed, you should find it it dconf-editor too.

`dconf write /org/gnome/shell/extensions/pop-shell/search "['<Super>minus']"`

Note that this doesn't change the shortcut shown in extension menu, as it seems to be coded in, but it's just cosmetics. You should be able to edit any keybinding defined in the schema with same method.

**Comment by rodrigoreyes79** [comment] 2020-05-12 16:36
@koylio That worked great. I was able to change the keyboard shortcut. Thank you!!! 

Nevertheless, the shortcut is still not showing up in the Shortcut configuration. That bug remains :/

**Comment by UltraSalem** [comment] 2020-05-13 21:19
dconf editor isn't showing me entries for things like super-L (currently mapped to super-<right arrow> which is a window navigation). I want super-L to be lockscreen like I am used to, but setting it in standard keyboard settings doesn't work as pop shell seems to be taking the key combo instead. Is there a general method for modifying pop shell keyboard shortcuts? (Pop OS 20.04)

**Comment by Osa1989** [comment] 2020-05-15 09:08
@koylio That worked for me. Thanks a lot

**Comment by miltoncandelero** [comment] 2020-05-17 03:45
Similar problem to @UltraSalem here. any way to unbind/change the bindings for Pop!_shell?
What it is bound to "Launch and Switch applications" I need it to be my terminal shortcut :(

**Comment by koylio** [comment] 2020-05-18 15:30
> dconf editor isn't showing me entries for things like super-L (currently mapped to super- which is a window navigation).

Devs might not appreciate issue tracker being used as a support forum. I'll try to explain this in enough detail so anybody guided here by google can help them selfs. If you still have questions, please post eg. on reddit at r/pop_os or some other forum of your choice.

Keyboard shortcuts are defined in schema:
https://github.com/pop-os/shell/blob/master_focal/schemas/org.gnome.shell.extensions.pop-shell.gschema.xml

From there you can look up the keybinding you want to change, in your case:
```
<key type="as" name="focus-right">
            <default><![CDATA[['<Super>Right','<Super>l']]]></default>
            <summary>Focus right window</summary>
</key>
```
Part after "name=" tells the key to edit with dconf:

`dconf write /org/gnome/shell/extensions/pop-shell/focus-right "['<Super>Right']"`

This should remove the Vim style keybinding Super+l, but didn't test it.

**Comment by UltraSalem** [comment] 2020-05-19 01:50
> Devs might not appreciate issue tracker being used as a support forum.

good point, and apologies for treating it as such. I guess for the purposes of this issue, the fact that these schema keys are not exposed in the standard system keybindings section is the bug we are hoping is fixed/feature added.

> `dconf write /org/gnome/shell/extensions/pop-shell/focus-right "['<Super>Right']"`
tested and working for my issue (freeing the keybind of super-L to do it's settings keybinding of lock the screen). Thank you.

**Comment by ids1024** [comment] 2020-06-22 22:23
This is indeed a bug, in some form or another.

Closing as a duplicate of https://github.com/pop-os/gnome-control-center/issues/93.

**Closed by ids1024** 2020-06-22 22:23 UTC

**Comment by Elinvention** [comment] 2020-11-02 17:39
Just pointing out that with recent pop shell extension, the launcher shortcut has been renamed and has to be set with:
`dconf write /org/gnome/shell/extensions/pop-shell/activate-launcher "['<Super>minus']"`

**Comment by masonmark** [comment] 2021-09-30 08:34
For the benefit of people like me who find this ticket because they want to assign Super-A to something other than showing the applications list, but using a macro program like AutoKey, I found an arguably simpler workaround. (Definitely simpler to explain to your dad on the phone.)

1. Using the Keyboard Shortcuts settings pane in the Settings app, assign Super-A to "Launch calculator". In Pop!_OS 21.04, this will show a dialog warning you that doing this will disable the existing shortcut.
2. Click OK to create the shortcut
3. Press Super-A to launch the calculator
4. Go back to Keyboard Shortcuts and delete the launch calculator shortcut
5. Press Super-A and note that it now does nothing
6. Now you can bind scripts/commands to Super-A using AutoKey or similar programs.
