### ISSUE TITLE
Occasional freeze of desktop

### ISSUE THREAD

**Issue by qnm** [pop-os/shell#398] opened 2020-05-28 04:26 UTC
**Distribution (run `cat /etc/os-release`):**
 
```
 > cat /etc/os-release
NAME="Pop!_OS"
VERSION="20.04 LTS"
ID=pop
ID_LIKE="ubuntu debian"
PRETTY_NAME="Pop!_OS 20.04 LTS"
VERSION_ID="20.04"
HOME_URL="https://system76.com/pop"
SUPPORT_URL="http://support.system76.com"
BUG_REPORT_URL="https://github.com/pop-os/pop/issues"
PRIVACY_POLICY_URL="https://system76.com/privacy"
VERSION_CODENAME=focal
UBUNTU_CODENAME=focal
LOGO=distributor-logo-pop-os
```
 
**Related Application and/or Package Version (run `apt policy pop-shell` or provide the latest commit if building locally):**

```
> apt policy pop-shell
pop-shell:
  Installed: 0.1.0~1589925465~20.04~ff5f374
  Candidate: 0.1.0~1589925465~20.04~ff5f374
  Version table:
 *** 0.1.0~1589925465~20.04~ff5f374 1001
       1001 http://ppa.launchpad.net/system76/pop/ubuntu focal/main amd64 Packages
       1001 http://ppa.launchpad.net/system76/pop/ubuntu focal/main i386 Packages
        100 /var/lib/dpkg/status
```

**Issue/Bug Description:**
Seeing occasional freezes in the desktop, including mouse. System usually comes back after less than 30 seconds.

My syslog has many entries like this:

```
May 28 14:19:53 ryzen gnome-shell[4249]: pop-shell: [ERROR] mismatch on grab op entity
May 28 14:19:53 ryzen gnome-shell[4249]: error: Pop Shell Error: mismatch on grab op entity
May 28 14:19:53 ryzen gnome-shell[4249]: ../../../gobject/gsignal.c:2696: handler '117350' of instance '0x55d4729c7680' is not blocked
May 28 14:19:53 ryzen gnome-shell[4249]: ../../../gobject/gsignal.c:2696: handler '117351' of instance '0x55d4729c7680' is not blocked
May 28 14:19:53 ryzen gnome-shell[4249]: ../../../gobject/gsignal.c:2696: handler '117352' of instance '0x55d4729c7680' is not blocked
May 28 14:19:53 ryzen gnome-shell[4249]: ../../../gobject/gsignal.c:2696: handler '117353' of instance '0x55d4729c7680' is not blocked
```

I then see notifications from pop-shell in-app with the same `mismatch on grab op entity` error as small dialogs.

**Steps to reproduce (if you know):**
Not sure, sorry.

**Expected behavior:**
I don't expect my desktop to freeze!

**Other Notes:**

**Comment by dontlaugh** [comment] 2020-05-30 16:20
Not sure if this is related, but I was having poor performance and it was due to syslog being filled up. There are a lot of `gnome-shell` messages going to syslog.

**Comment by qnm** [comment] 2020-06-01 06:50
> Not sure if this is related, but I was having poor performance and it was due to syslog being filled up. There are a lot of `gnome-shell` messages going to syslog.

How did you resolve it?

**Comment by dontlaugh** [comment] 2020-06-01 14:11
Since it's my personal machine, I was okay with just deleting the giant log file.

```
rm /var/log/syslog
```

**Comment by mmstick** [comment] 2020-06-03 13:42
Closing because this isn't specifically caused by Pop Shell

**Closed by mmstick** 2020-06-03 13:42 UTC

**Comment by Justin00015** [comment] 2020-06-04 21:41
> Closing because this isn't specifically caused by Pop Shell

Just curious, are we sure it isn't caused by Pop Shell? I have gotten this same error, and the notification clearly says "Pop Shell Error"
![Screenshot from 2020-06-04 17-39-55](https://user-images.githubusercontent.com/26168814/83813059-a14b8480-a68a-11ea-95e0-7e5c87cb86d1.png)

**Comment by renanredel** [comment] 2020-06-05 00:43
I'm having the same issue. 
Only occur when I try to use the gestures on touchpad.

![Screenshot from 2020-06-04 21-41-21](https://user-images.githubusercontent.com/14296403/83824210-38750400-a6ac-11ea-87ae-79ff12797822.png)

**Comment by verenion** [comment] 2020-06-22 13:26
I'm also seeing this same issue. Tried clearing the syslog, but to no avail.

**Comment by risalfajar** [comment] 2020-07-10 12:50
I also have this issue, it's often happened when I run Android Studio and Chrome at once. The system will almost freezes and I should close Chrome or AS as fast as possible before it completely freezes, when I succeed in doing this lots of notification will appear like this:
![image](https://user-images.githubusercontent.com/28381124/87156277-a2ee1500-c2e6-11ea-888f-2596a1ffbc11.png)

**Comment by Alpha-T30** [comment] 2020-08-19 02:43
So what is the solution ??
