### ISSUE TITLE
Outer gaps not respected with only one window

### ISSUE THREAD

**Issue by cclamb** [pop-os/shell#1723] opened 2024-07-23 21:40 UTC
**(1) Issue/Bug Description:**
If I use the launcher to launch an application, and there's only one window on the display, there is no outer gap around the window. Works as expected with more than one window.

**(2) Steps to reproduce (if you know):**
Open a single window in a workspace.

**(3) Expected behavior:**
Expect to have gaps around the outside of the single window, but no gaps appear.

**(4) Distribution (run `cat /etc/os-release`):**
NAME="BlackArch Linux"
ID=blackarch
PRETTY_NAME="BlackArch Linux"
ANSI_COLOR="0;31"
HOME_URL="https://www.blackarch.org/"
SUPPORT_URL="https://www.blackarch.org/"
BUG_REPORT_URL="https://www.blackarch.org/"

**(5) Gnome Shell version:**

**(6) Pop Shell version (run `apt policy pop-shell` or provide the latest commit if building locally):**

**(7) Where was Pop Shell installed from:**
gnome extensions website

**(8) Monitor Setup (2 x 1080p, 4K, Primary(Horizontal), Secondary(Vertical), etc):**
Single integrated laptop on HP Zbook, 1920x1200, normal orientation

**(9) Other Installed/Enabled Extensions:**
OpenBar
Simple Workspaces Bar
PopShell
User Themes

**(10) Other Notes:**

**Comment by leviport** [comment] 2024-07-23 21:46
I believe this is a duplicate of https://github.com/pop-os/shell/issues/470

If you enable smart gaps in the pop-shell extension's settings (use the "Extensions" app), I believe it will behave as you describe.

**Comment by cclamb** [comment] 2024-07-23 23:46
This fixes thanks - I guess I just like dumb gaps :-)

**Comment by cclamb** [comment] 2024-07-23 23:46
Closing as it is a duplicate of fixed issue

**Closed as completed** 2024-07-23 23:46 UTC
