### ISSUE TITLE
Tiling feels Laggy when starting windows

### ISSUE THREAD

**Issue by Geigerkind** [pop-os/shell#1114] opened 2021-07-30 06:37 UTC
**Distribution (run `cat /etc/os-release`):**
```
NAME="Pop!_OS"
VERSION="21.04"
ID=pop
ID_LIKE="ubuntu debian"
PRETTY_NAME="Pop!_OS 21.04"
VERSION_ID="21.04"
HOME_URL="https://pop.system76.com"
SUPPORT_URL="https://support.system76.com"
BUG_REPORT_URL="https://github.com/pop-os/pop/issues"
PRIVACY_POLICY_URL="https://system76.com/privacy"
VERSION_CODENAME=hirsute
UBUNTU_CODENAME=hirsute
LOGO=distributor-logo-pop-os
``` 

**Issue/Bug Description:**
When I start an application it feels very laggy compared to I3/Sway. Even with gnome animations turned off, its still laggy. It seeems like it first starts it as floating window, places it to some default position and then relocates it.

**Steps to reproduce (if you know):**
Open several terminals or other applications

**Expected behavior:**
It should be butter smooth!

Pop-Shell Version: Installed: 1.1.0~1627383380~21.04~475b49d
Gnome-Shell Version: Installed: 3.38.4-1ubuntu3~21.04.1ubuntu1pop1~1623339707~21.04~2a1865d

This bug occurs with default Pop OS extensions.

**Comment by jmmaranan** [comment] 2021-08-06 16:46
The `window-entered-monitor` event immediately triggers `focus` event so the hint I think immediately kicks in - so you are seeing the first-frame prior to pop-shell rendering the tree.

**Comment by Geigerkind** [comment] 2021-08-06 16:54
Sounds good, can we remove that issue?
But what I wanted to mainly point out, that it requires significant more time to show me a rendered frame of the terminal compared to i3/sway. Maybe this is due to the pop shell hooking in, but it feels like an eternity, coming from these window managers.

**Comment by mmstick** [comment] 2021-08-06 18:37
Duplicate of #129

**Closed by mmstick** 2021-08-06 18:37 UTC
