### ISSUE TITLE
Cannot Manage Tiling With Mouse on GNOME 44

### ISSUE THREAD

**Issue by CaffeinatedLinux** [pop-os/shell#1615] opened 2023-04-16 04:27 UTC
**(1) Issue/Bug Description:**

Unable to manage tiling with mouse on GNOME 44. When I hit super to grab a window I can "move" it on screen, but when I let go it just goes back into it's original position. This also means I'm unable to stack windows using my mouse.

**(2) Steps to reproduce (if you know):**

- Press Super
- Grab Window 
- Move window in an attempt to re-arrange the tiling or stack on top of another window 

**(3) Expected behavior:**

It should let me move that window to another place on the screen or stack that window on top of another.

**(4) Distribution (run `cat /etc/os-release`):**
 
```
   cat /etc/os-release 
NAME="Fedora Linux"
VERSION="38 (Workstation Edition)"
ID=fedora
VERSION_ID=38
VERSION_CODENAME=""
PLATFORM_ID="platform:f38"
PRETTY_NAME="Fedora Linux 38 (Workstation Edition)"
ANSI_COLOR="0;38;2;60;110;180"
LOGO=fedora-logo-icon
CPE_NAME="cpe:/o:fedoraproject:fedora:38"
DEFAULT_HOSTNAME="fedora"
HOME_URL="https://fedoraproject.org/"
DOCUMENTATION_URL="https://docs.fedoraproject.org/en-US/fedora/f38/system-administrators-guide/"
SUPPORT_URL="https://ask.fedoraproject.org/"
BUG_REPORT_URL="https://bugzilla.redhat.com/"
REDHAT_BUGZILLA_PRODUCT="Fedora"
REDHAT_BUGZILLA_PRODUCT_VERSION=38
REDHAT_SUPPORT_PRODUCT="Fedora"
REDHAT_SUPPORT_PRODUCT_VERSION=38
SUPPORT_END=2024-05-14
VARIANT="Workstation Edition"
VARIANT_ID=workstation
```

**(5) Gnome Shell version:**

GNOME 44

**(6) Pop Shell version (run `apt policy pop-shell` or provide the latest commit if building locally):**

a3a1b7bb832838fec2ea875954d33443fc680912

**(7) Where was Pop Shell installed from:**

Git

**(8) Monitor Setup (2 x 1080p, 4K, Primary(Horizontal), Secondary(Vertical), etc):**

3440x1440 (Horizontal) (Primary), 1080x1920 (Vertical, Secondary)

**(9) Other Installed/Enabled Extensions:**

Installed: 
- Blur my Shell (Disabled)
- Burn My Windows (Disabled)
- GSConnect (Disabled)
- Unite (Enabled)
- User Themes (Disabled)
- AppIndicator and KStatusNotifierItem Support (Disabled)
- Applications Menu (Disabled)
- Background Logo (Disabled)
- GameMode (Disabled)
- Launch new Instance (Disabled)
- Places Status Indicator (Enabled)
- Window List (Disabled)

**(10) Other Notes:**

**Comment by emko** [comment] 2023-04-17 21:04
same, any alternative extensions you using? until this is fixed?

**Comment by flokli** [comment] 2023-04-18 08:29
pop shell was marked as supported for GNOME 44 with https://github.com/pop-os/shell/commit/dcf17f345856476bf1401c690fbdc3fe8dcbb650:

> I was able to set org.gnome.shell.disable-extension-version-validation
to true and install the extension on GNOME shell 44 beta.  Everything
appears to work as expected.

@carlwgeorge, can you reproduce this?

**Comment by flokli** [comment] 2023-04-18 08:59
I was able to reproduce. See the attached video - I'm not able to move the "C" terminal window up to the topright corner (and swap with B), it snaps back:

[Screencast from 2023-04-18 10-57-20.webm](https://user-images.githubusercontent.com/183879/232727375-5f7ef0c0-b062-441f-99dd-a7f2a6dbc3d6.webm)

It also seems to be missing the orange "squares" that normally show how things would be tiled if released here.

**Comment by mooey5775** [comment] 2023-04-20 16:27
This seems to be broken due to the major Clutter Grab changes in GNOME 44.0 (described in this merge request https://gitlab.gnome.org/GNOME/mutter/-/merge_requests/2683), and specifically because the grab op emitted by mutter is now different (https://gitlab.gnome.org/GNOME/mutter/-/commit/12773cf8e2954082f346dee300af624b25baf23c).

Will push a PR to fix this in a bit

**Closed as completed** 2023-04-27 17:33 UTC
Labels: GNOME 44
