### ISSUE TITLE
Pressing Super key does not show Activities Overview if input language is not Latin based.

### ISSUE THREAD

**Issue by AlfredTs** [pop-os/shell#295] opened 2020-05-05 21:35 UTC
**Distribution (run `cat /etc/os-release`):**
 NAME="Pop!_OS"
VERSION="20.04 LTS"
ID=pop
ID_LIKE="ubuntu debian"
PRETTY_NAME="Pop!_OS 20.04 LTS"
VERSION_ID="20.04"
HOME_URL="https://system76.com/pop"
SUPPORT_URL="http://support.system76.com"
BUG_REPORT_URL="https://github.com/pop-os/pop/issues"
PRIVACY_POLICY_URL="https://system76.com/privacy"
VERSION_CODENAME=focal
UBUNTU_CODENAME=focal
LOGO=distributor-logo-pop-os

 
 
**Related Application and/or Package Version (run `apt policy pop-shell` or provide the latest commit if building locally):**
pop-shell:
  Installed: 0.1.0~1588624471~20.04~dfb378c
  Candidate: 0.1.0~1588624471~20.04~dfb378c
  Version table:
 *** 0.1.0~1588624471~20.04~dfb378c 1001
       1001 http://ppa.launchpad.net/system76/pop/ubuntu focal/main amd64 Packages
       1001 http://ppa.launchpad.net/system76/pop/ubuntu focal/main i386 Packages
        100 /var/lib/dpkg/status

**Issue/Bug Description:**
Super key (Win-key) does not activate Activities Overview when  input language is set to a language with non-latin alphabet. I tested with Russian, Georgian and Chinese. All other shortcuts seem to be working though.
The shortcut did work with English or German as input language. Thus my suspicion that it's specific to non-latin alphabets.

**Steps to reproduce (if you know):**
1. Set input source to at least one of these languages Russian, Georgian and Chinese.
2. Press Super key

**Expected behavior:**
Pressing Super key should cause Activities Overview no matter the input language.

**Other Notes:**
Device: Razer Blade 14 Early 2016

**Comment by leviport** [comment] 2020-05-05 21:45
Duplicate of https://github.com/pop-os/beta/issues/98

**Closed by leviport** 2020-05-05 21:45 UTC
