### ISSUE TITLE
"Tile Windows" Option on top bar does not reflect tiling state when tiling is activated using the shorcut

### ISSUE THREAD

**Issue by suryanisaac** [pop-os/shell#902] opened 2021-03-11 09:39 UTC
**Distribution (run `cat /etc/os-release`):** Pop!_OS 20.10
 
 
 
**Related Application and/or Package Version (run `apt policy $PACKAGE NAME`):**

**Issue/Bug Description:**
When tiling is enabled with the keyboard shortcut (Super+Y), the "Tile Windows" toggle in the top bar menu remains off. When clicked in this state, tiling windows turns off, and the state of the toggle button does not change.

**Steps to reproduce (if you know):**
1. Turn on tiling windows using the keyboard shortcut
2. Observe "Tile Windows" in the top bar

**Expected behavior:**
The "Tile Windows" Toggle should be enabled if tiling windows is turned on using the shortcut

**Other Notes:**

**Comment by bflanagin** [comment] 2021-03-11 18:02
duplicate of https://github.com/pop-os/shell/issues/856

**Closed by bflanagin** 2021-03-11 18:02 UTC
