### ISSUE TITLE
The possibility to change Super+/ Shortcut for the Launcher

### ISSUE THREAD

**Issue by Diolinux** [pop-os/shell#392] opened 2020-05-25 13:41 UTC
Hi, the new launcher feature on Pop!_OS 20.04 (Pop-Shel) is great, but the only way to active it is by pressing a specific combination of keys, nowadays is Super+/.

Since Pop!_OS is used by people from all of the world, i like to suggestion a modification on this feature.

**Why**?

Well, keyboards are different, specially when you look at models made for another language than English.  The position of the key "/" may vary a lot according to which model you are using.

My personal example: I use a keyboard with an English physical layout, but, since a regularly write in Portuguese, I simply add a virtual layout to this keyboard, knew as ABNT2. This layout is kind of similar to the physical English, but it has some differences, for example, I can write letters like "Ç,Ã" and so on. 

In order to type this: Ç
I need to type in the keyboard the key: ;

This means, when i tried to use the / key for the Super+/ keybinding, i end up to typing: ;
This made the launcher inaccessible. Of course, in the keyboard, even with a different layout, i can type the / character, but for that i need to perform AltDir+Shift+', and that key combination doesn't launch the Pop-Shell Launcher.

**How it can be fixed?**

I think the easy way would be adding the option to customize this shortcut on GNOME Settings, just like we have some of the most common Pop!_OS shortcuts. This way, no matter what key combination you like the most for this feature, you can have it.

Another discussion, if this is to complicated for some reason, is changing the default shortcut (Super+/) to something that any keyboard has in the same place, just like the "Super Key", and that key is the space bar.

Working like a macOS Spotlight, by pressing Super+Space you can open the launcher and start typing. Since the Space bar is, regularly, a very prominent key, is easy to new users to find it without look, and make an easy transition for those who come to Pop from an Apple computer.

Thanks for your work guys.

Greetings from Brazil.

**Comment by folke** [comment] 2020-05-26 14:44
A work around for now, is to change it in the code and then rebuild it.

You want to change the following line: 
https://github.com/pop-os/shell/blob/21361f5b7f983957e62689869eb6b54d4a29e3a0/schemas/org.gnome.shell.extensions.pop-shell.gschema.xml#L69

After you've changed this line, execute the following:
```shell
$ make clean

$ ./rebuild.sh
```

Be aware, that this will again reset all your gnome keyboard shortcuts as when installing pop-os shell.

**Comment by TomFaulkner** [comment] 2020-05-27 15:31
It would be great to have access to change all of these shortcut keys. Preferably in a dotfile.

I suppose saving a patch and pulling/rebuilding on every update works too, but definitely not as convenient.

**Comment by mmstick** [comment] 2020-06-03 14:25
Duplicate of #322

**Closed by mmstick** 2020-06-03 14:25 UTC

**Comment by gregorriegler** [comment] 2020-12-24 16:54
> A work around for now, is to change it in the code and then rebuild it.
> 
> You want to change the following line:
> https://github.com/pop-os/shell/blob/21361f5b7f983957e62689869eb6b54d4a29e3a0/schemas/org.gnome.shell.extensions.pop-shell.gschema.xml#L69
> 
> After you've changed this line, execute the following:
> 
> ```shell
> $ make clean
> 
> $ ./rebuild.sh
> ```
> 
> Be aware, that this will again reset all your gnome keyboard shortcuts as when installing pop-os shell.

this is the only thing that works un ubuntu. no setting, no dconf, only this. was a pain to change the keybind

**Comment by ids1024** [comment] 2020-12-24 17:28
> this is the only thing that works un ubuntu. no setting, no dconf, only this. was a pain to change the keybind

You don't see it under `/org/gnome/shell/extensions/pop-shell` in dconf-editor? Or in the commandline with `gsettings get org.gnome.shell.extensions.pop-shell activate-launcher` (it can then be set with the `set` command).

**Comment by gregorriegler** [comment] 2020-12-24 20:44
> > this is the only thing that works un ubuntu. no setting, no dconf, only this. was a pain to change the keybind
> 
> You don't see it under `/org/gnome/shell/extensions/pop-shell` in dconf-editor? Or in the commandline with `gsettings get org.gnome.shell.extensions.pop-shell activate-launcher` (it can then be set with the `set` command).

no. not at all.
i'm using Ubuntu 20.04.1 LTS though
