### ISSUE TITLE
Mouse-Down + Super freezes desktop

### ISSUE THREAD

**Issue by pzfl** [pop-os/shell#1457] opened 2022-05-26 22:38 UTC
Pressing and holding the left mouse button and pressing super to open the Cosmic Launcher freezes my desktop, such that I can still move the cursor, but any other subsequent input from mouse and keyboard are ignored. This appears to be a global issue, as I can trigger the bug consistently regardless of the currently focused application.

Steps to reproduce:

 1. Hold down left mouse button or touch pad (tested both on pang11)
      - on the desktop (i.e. draw a box to select desktop icons)
      - in text editors like gedit or VS Code, maybe select some text
      - in Firefox anywhere on a webpage
 2. Do not release left mouse button
 3. Press Super/Windows on your keyboard to bring up the Cosmic Launcher
 4. Release left mouse button
 5. You should be able to move the mouse, but the desktop should be otherwise unresponsive
 6. Use `Ctrl+Alt+F3` to restart gdm or your system to regain control

**Comment by leviport** [comment] 2022-05-26 23:23
Interesting, that looks like the same sort of lockup I noticed in https://github.com/pop-os/gnome-shell/issues/112

Do you have multiple displays connected when you see this happen? If so, does turning one off (or unplugging it) and then turning it back on (or plugging it back in) fix the issue?

**Comment by pzfl** [comment] 2022-05-26 23:48
Were you able to reproduce the issue?

The bug can be triggered in any configuration of internal display only, HDMI display only, internal+HDMI extended. Unplugging and plugging the screen back does not unfreeze the desktop.

I should also note, that when pressing super to open the Launcher, I get the "Active Hint" (the one where you configure the color in the tile windows menu) overlay for the currently focused window. It seems like the desktop is trying to open the launcher where it disables input to other windows on the desktop (such that while the launcher is open and you click onto a different window that is not the launcher, the launcher is closed, rather than forwarding the input to the application that is at that position). However, holding down left mouse button prevents the actual launcher window from opening and you end up in a state where the desktop thinks the launcher is open, when it's actually closed.

Edit: Reading https://github.com/pop-os/gnome-shell/issues/112 it seems like you get stuck in a similar state with the active window overlay but sound and everything working, although I cannot reproduce that bug (or maybe am too slow in mashing Super)

**Comment by dawaltconley** [comment] 2022-05-27 04:51
Was able to reproduce this. Have been experiencing similar freezes without touching the mouse as well (not sure how to reproduce them yet) but this explains what's happening there as well I think (system is unresponsive but not frozen, launcher active hint remains up).

**Comment by vishesh-sarinDXB** [comment] 2022-05-27 07:01
I am fairly certain this is specific to pop-shell as it isn't  a problem  with pop-shell  disabled (have to restart gdm)

**Comment by leviport** [comment] 2022-05-27 15:10
Might be fixed by https://github.com/pop-os/gnome-shell/pull/110

**Closed as completed** 2022-05-27 18:54 UTC

**Comment by colans** [comment] 2022-05-27 20:31
This restores the session:
> Switching to another TTY and `killall -9 gnome-shell`
