### ISSUE TITLE
Launcher defaults to calculator when entering 1Password

### ISSUE THREAD

**Issue by mkleehammer** [pop-os/shell#1553] opened 2022-12-05 18:35 UTC
**(1) Issue/Bug Description:**

I'd like the launcher to highlight the 1Password program when I enter "1password" or "1Password", but the first result is a calculator result.

**(2) Steps to reproduce (if you know):**

Open the launcher, enter "1Password".  When 1Password is not running, I get this:

![image](https://user-images.githubusercontent.com/27421/205714422-e0c27491-71c8-4239-b46e-0fbbed2119cf.png)

If 1Password is running, it does choose it first.

**(3) Expected behavior:**

I would expect an exact match to choose 1Password instead of the calculator.  

I also thought that an equals sign prefix was required to enable the calculator.

Is there a way to require the equals or to disable the calculator functionality completly.

**(4) Distribution (run `cat /etc/os-release`):**
 
Pop!_OS 22.04 LTS

**(5) Gnome Shell version:**

GNOME 42.3.1

**(6) Pop Shell version (run `apt policy pop-shell` or provide the latest commit if building locally):**

```
pop-shell:
  Installed: 1.1.0~1667482449~22.04~30bf682
  Candidate: 1.1.0~1667482449~22.04~30bf682
  Version table:
 *** 1.1.0~1667482449~22.04~30bf682 1001
       1001 http://apt.pop-os.org/release jammy/main amd64 Packages
       1001 http://apt.pop-os.org/release jammy/main i386 Packages
        100 /var/lib/dpkg/status
```

**(7) Where was Pop Shell installed from:**

Pop OS installer.

**(8) Monitor Setup (2 x 1080p, 4K, Primary(Horizontal), Secondary(Vertical), etc):**

2560x2880 horizontal (laptop closed)

**(9) Other Installed/Enabled Extensions:**

**(10) Other Notes:**

**Comment by leviport** [comment] 2022-12-05 18:37
I believe this is a duplicate of https://github.com/pop-os/launcher/issues/60

**Closed as completed by leviport** 2022-12-05 18:37 UTC
