### ISSUE TITLE
"Grouped" windows

### ISSUE THREAD

**Issue by ezhang7423** [pop-os/shell#1347] opened 2022-02-07 20:55 UTC
In pop-shell, is it possible to tile windows in a stack? In essence, I want to "group" multiple windows together so that they behave like one window. I'm a bit confused on whether this is possible, since #273 seems to indicate it is and #626 seems to indicate it isn't.

**Comment by jacobgkau** [comment] 2022-02-07 21:24
> In pop-shell, is it possible to tile windows in a stack?

No, as Levi told you in Mattermost, it's a neat idea but is not currently implemented.

Is there a difference between this issue and https://github.com/pop-os/shell/issues/626, or is this a duplicate/did you not see that one until opening this one?

> I'm a bit confused on whether this is possible, since https://github.com/pop-os/shell/issues/273 seems to indicate it is and https://github.com/pop-os/shell/issues/626 seems to indicate it isn't.

https://github.com/pop-os/shell/issues/273 was for "grouping in tiling," not tiling in grouping. That's why it was closed as a duplicate of https://github.com/pop-os/shell/issues/150, which was a feature request for stacking.

**Comment by mmstick** [comment] 2022-02-07 22:08
Windows already supporting being grouped together as one window in a stack

**Closed by mmstick** 2022-02-07 22:08 UTC
