### ISSUE TITLE
Mouse points to the top left corner of selected window after pressing Super key from top bar

### ISSUE THREAD

**Issue by donielix** [pop-os/shell#851] opened 2021-01-23 11:32 UTC
**Distribution:**
 
 NAME="Pop!_OS"
VERSION="20.10"
ID=pop
ID_LIKE="ubuntu debian"
PRETTY_NAME="Pop!_OS 20.10"
VERSION_ID="20.10"
HOME_URL="https://pop.system76.com"
SUPPORT_URL="https://support.system76.com"
BUG_REPORT_URL="https://github.com/pop-os/pop/issues"
PRIVACY_POLICY_URL="https://system76.com/privacy"
VERSION_CODENAME=groovy
UBUNTU_CODENAME=groovy
LOGO=distributor-logo-pop-os

 
**Related Application and/or Package Version:**

pop-shell:
  Instalados: 1.1.0~1611349201~20.10~2b9e4a4
  Candidato:  1.1.0~1611349201~20.10~2b9e4a4
  Tabla de versión:
 *** 1.1.0~1611349201~20.10~2b9e4a4 1001
       1001 http://ppa.launchpad.net/system76/pop/ubuntu groovy/main amd64 Packages
       1001 http://ppa.launchpad.net/system76/pop/ubuntu groovy/main i386 Packages
        100 /var/lib/dpkg/status

**Issue/Bug Description:**

When I press super key, or click over activities button from the top bar, immediately the mouse pointer goes to the top left current selected window. I reckon this might be a bug related to pop-shell, because that started happening since it last update.

**Expected behavior:**

Mouse pointer should keep its current position

**Comment by donielix** [comment] 2021-01-25 21:17
> @donielix ,
> 
> Are you using pop-shell's tilling option or the standard window management style? Regardless to the answer, does it exhibit the same issue in both modes?

Yes, it exhibit the same behavior in both modes.

**Comment by leviport** [comment] 2022-05-04 18:01
@dennisjun I believe that fits better in this feature request: https://github.com/pop-os/shell/issues/1188

This issue report is quite old, and I don't believe I've seen it happen for quite a while. I'm going to close it for now, but let me know if the bug is still present and I need to reopen it.

**Closed by leviport** 2022-05-04 18:01 UTC

**Comment by dennisjun** [comment] 2022-05-04 18:04
@leviport yes it's still present. Should I open a fresh issue? It only started happening to me last night after an update.

**Comment by leviport** [comment] 2022-05-04 20:06
@dennisjun as I said, what you described is intended behavior, so an ability to override that intended default behavior would be a feature request, which is described in #1188. I'm asking about the issue that was originally reported.
