### ISSUE TITLE
Tile Windows: All Shortcuts Visual Incorrect

### ISSUE THREAD

**Issue by Kabuki-kai** [pop-os/shell#310] opened 2020-05-06 23:58 UTC
**Distribution (run `cat /etc/os-release`):** Pop!_OS 20.04 LTS
 
 
 
**Related Application and/or Package Version (run `apt policy pop-shell` or provide the latest commit if building locally):** 0.1.0-1588624471-20.04-dfb378c

**Issue/Bug Description:** The "Pop!_Shell Keyboard Shortcuts" visual is incorrect.

**Steps to reproduce (if you know):** If you select `View All` from the Tile Windows menu on the toolbar, the area "Move, resize and swap windows in adjustment mode" states that `Shift` + `Up Arrow` decreases the window size. This is not the case. `Shift` + `Up Arrow` increases the window size and `Shift` + `Down Arrow` decreases the size.

**Expected behavior:** The up arrow graphic should be on the "Increase Window Size" row, and the down arrow graphic should be on the "Decrease Window Size" of the "Pop!_Shell Keyboard Shortcuts" visual.

**Other Notes:**
![image](https://user-images.githubusercontent.com/45097495/81239676-20d22f00-8fcb-11ea-8531-750eebad64d5.png)

**Comment by jannikbuhr** [comment] 2020-05-07 12:21
I noticed that this behavior seems to depend on the side the window is on in tiling mode. When the window is on the left side, Shit+right will make it smaller, when it is on the right side, Shift+right makes it larger. Swapping this would make it more intuitive because it would correlate with the movement of the window separator.

**Comment by mmstick** [comment] 2020-05-07 14:44
Duplicate of #238

**Closed by mmstick** 2020-05-07 14:44 UTC
