### ISSUE TITLE
[Feature request] Option to set tiling/stacking per workspace

### ISSUE THREAD

**Issue by hliebert** [pop-os/shell#860] opened 2021-01-29 12:30 UTC
It would be great if tiling/stacking could be enabled on a per workspace (or per display) basis, or to select  some workspaces that are exempt from the selection. I generally use tiling mode, but typically have a single workspace that has a library database and a lot of pdf research papers open where stacking mode is more convenient. 

This is somewhat related to #606, but I'd prefer to have pdfs tile on other displays or when moving them around.

**Comment by jacobgkau** [comment] 2021-01-29 15:17
Closing as a duplicate of https://github.com/pop-os/shell/issues/380.

**Closed by jacobgkau** 2021-01-29 15:17 UTC

**Comment by hliebert** [comment] 2021-01-29 16:27
Sorry, didn't see that one.
