### ISSUE TITLE
JetBrains IDE (PyCharm, PHPStorm etc) does not receive keyboard input when using tiling and gnome-terminal window is visible.

### ISSUE THREAD

**Issue by aquatix** [pop-os/shell#1312] opened 2022-01-11 12:47 UTC
**(1) Issue/Bug Description:**

I have a strange issue while using JetBrains PyCharm on the primary screen and a gnome terminal on a secondary screen: keyboard input does not go to the PyCharm window, but instead appears inside the terminal.

Tiling is enabled, but it seems to also happen when disabling tiling for those windows.

Maybe related: when I stacked a terminal window and PyCharm, I was not able to interact with the IDE at all, all input - including mouse - seemed to go to the terminal instead. Stacking two PyCharm windows works fine, introducing a terminal makes all keyboard input go to the terminal. Same when having the terminal somewhere else on the primary or secondary screen.

I have the latest versions of Pop!_OS packages as of now (there were a bunch of updates a few hours ago).

**(2) Steps to reproduce (if you know):**

Open PyCharm/a JetBrains IDE. Also open a Gnome-Terminal window on one of the visible monitors.

**(3) Expected behavior:**

Focused window receives keyboard input, so PyCharm works like the editor it is :)

**(4) Distribution (run `cat /etc/os-release`):**
 
```
NAME="Pop!_OS"
VERSION="21.10"
ID=pop
ID_LIKE="ubuntu debian"
PRETTY_NAME="Pop!_OS 21.10"
VERSION_ID="21.10"
HOME_URL="https://pop.system76.com"
SUPPORT_URL="https://support.system76.com"
BUG_REPORT_URL="https://github.com/pop-os/pop/issues"
PRIVACY_POLICY_URL="https://system76.com/privacy"
VERSION_CODENAME=impish
UBUNTU_CODENAME=impish
LOGO=distributor-logo-pop-os
```

**(5) Gnome Shell version:**

Shipped with 21.10: 40.4.0

**(6) Pop Shell version (run `apt policy pop-shell` or provide the latest commit if building locally):**

```1.1.0~1641595320~21.10~c3d93f8```

**(7) Where was Pop Shell installed from:**

Pop!_OS installation medium (usb).

**(8) Monitor Setup (2 x 1080p, 4K, Primary(Horizontal), Secondary(Vertical), etc):**

1080p laptop screen to the left, primary 4k monitor landscape, secondary 4k monitor in portrait to the right.

**(9) Other Installed/Enabled Extensions:**

- AppIndicator
- Caffeine
- Desktop Icons NG
- GSConnect
- Jiggle
- OpenWeather
- Sound Input & Output Device Chooser
- system-monitor
- Transparent Top Bar (Adjustable transparency)
- User Themes

And the built-in ones, all enabled.

**(10) Other Notes:**

Thanks for fixing the transparent top bar/panel functionality :)

**Comment by aquatix** [comment] 2022-01-11 14:06
OK, I reproduced it with Evolution too, instead of Gnome-Terminal. It seems like the PyCharm window is some special case.

**Comment by amenophis** [comment] 2022-01-11 14:52
Same issue with intellij PHPStorm

**Comment by ThaRising** [comment] 2022-01-11 18:15
I am having the same issue since updating this morning.
I can reproduce this error consistently by opening PyCharm, tabbing the window and then opening another project in a new window in the same group. At that point its no longer possible to switch to the newly opened tab, I can only use the one I opened first.
Trying to switch to the new window either does not work or instantly brings me back to the winow I opened first.
Using Super + Enter to select and swap the windows, causes everything to glitch out completely. Using any of the PyCharm windows after anything of the above, temporarily causes the entire UI to lag (animations, e.g. when switching workspaces or just using Pop-Shell keyboard shortcuts).
Disabling tiling seems to be the only fix for this problem currently.

**Comment by wojciech-zurek** [comment] 2022-01-12 06:21
intellij idea - same problem

**Comment by Sroka** [comment] 2022-01-12 08:04
Yep, started happening after yesterday's updates

**Comment by amenophis** [comment] 2022-01-12 10:23
Hi,
Is there a way to rollback manually to a previous version of pop-shell package ?

`apt-cache` show me only the actual version ...
 ```
$ apt-cache madison pop-shell
 pop-shell | 1.1.0~1641595320~21.10~c3d93f8 | http://apt.pop-os.org/release impish/main amd64 Packages
 pop-shell | 1.1.0~1641595320~21.10~c3d93f8 | http://apt.pop-os.org/release impish/main i386 Packages
 pop-shell | 1.1.0~1641595320~21.10~c3d93f8 | http://apt.pop-os.org/release impish/main Sources
```

**Comment by kruthoff** [comment] 2022-01-12 10:53
While working in idea, all of a sudden my system/GUI was unresponsive. Switching to an open terminal was possible. My syslog was flooded(!) with such messages. I rebooted the system. Restarting pop-shell or the window manager would have worked, too, I think.

```
Jan 12 11:38:10 gazelle-akr gnome-shell[3448]: == Stack trace for context 0x55a362762170 ==
Jan 12 11:38:10 gazelle-akr gnome-shell[3448]: message repeated 2 times: [ == Stack trace for context 0x55a362762170 ==]
Jan 12 11:38:10 gazelle-akr gnome-shell[3448]: Attempting to run a JS callback during garbage collection. This is most likely caused by destroying a Clutter actor or GTK widget with ::destroy signal connected, or using the destroy(), dispose(), or remove() vfuncs. Because it would crash the application, it has been blocked.
Jan 12 11:38:10 gazelle-akr gnome-shell[3448]: == Stack trace for context 0x55a362762170 ==
Jan 12 11:38:10 gazelle-akr gnome-shell[3448]: == Stack trace for context 0x55a362762170 ==
Jan 12 11:38:10 gazelle-akr gnome-shell[3448]: The offending callback was SourceFunc().
Jan 12 11:38:10 gazelle-akr gnome-shell[3448]: == Stack trace for context 0x55a362762170 ==
Jan 12 11:38:10 gazelle-akr gnome-shell[3448]: Attempting to run a JS callback during garbage collection. This is most likely caused by destroying a Clutter actor or GTK widget with ::destroy signal connected, or using the destroy(), dispose(), or remove() vfuncs. Because it would crash the application, it has been blocked.
Jan 12 11:38:10 gazelle-akr gnome-shell[3448]: == Stack trace for context 0x55a362762170 ==
Jan 12 11:38:10 gazelle-akr gnome-shell[3448]: == Stack trace for context 0x55a362762170 ==
Jan 12 11:38:10 gazelle-akr gnome-shell[3448]: The offending callback was SourceFunc().
Jan 12 11:38:10 gazelle-akr gnome-shell[3448]: Attempting to run a JS callback during garbage collection. This is most likely caused by destroying a Clutter actor or GTK widget with ::destroy signal connected, or using the destroy(), dispose(), or remove() vfuncs. Because it would crash the application, it has been blocked.
Jan 12 11:38:10 gazelle-akr gnome-shell[3448]: == Stack trace for context 0x55a362762170 ==
Jan 12 11:38:10 gazelle-akr gnome-shell[3448]: == Stack trace for context 0x55a362762170 ==
Jan 12 11:38:10 gazelle-akr gnome-shell[3448]: The offending callback was SourceFunc().
Jan 12 11:38:10 gazelle-akr gnome-shell[3448]: Attempting to run a JS callback during garbage collection. This is most likely caused by destroying a Clutter actor or GTK widget with ::destroy signal connected, or using the destroy(), dispose(), or remove() vfuncs. Because it would crash the application, it has been blocked.
Jan 12 11:38:10 gazelle-akr gnome-shell[3448]: == Stack trace for context 0x55a362762170 ==
Jan 12 11:38:10 gazelle-akr gnome-shell[3448]: == Stack trace for context 0x55a362762170 ==
Jan 12 11:38:10 gazelle-akr gnome-shell[3448]: The offending callback was SourceFunc().

...

Jan 12 11:38:10 gazelle-akr gnome-shell[3448]: Attempting to run a JS callback during garbage collection. This is most likely caused by destroying a Clutter actor or GTK widget with ::destroy signal connected, or using the destroy(), dispose(), or remove() vfuncs. Because it would crash the application, it has been blocked.
Jan 12 11:38:10 gazelle-akr gnome-shell[3448]: The offending callback was SourceFunc().
Jan 12 11:38:10 gazelle-akr gnome-shell[3448]: Attempting to run a JS callback during garbage collection. This is most likely caused by destroying a Clutter actor or GTK widget with ::destroy signal connected, or using the destroy(), dispose(), or remove() vfuncs. Because it would crash the application, it has been blocked.
Jan 12 11:38:10 gazelle-akr gnome-shell[3448]: The offending callback was SourceFunc().
Jan 12 11:38:10 gazelle-akr gnome-shell[3448]: Attempting to run a JS callback during garbage collection. This is most likely caused by destroying a Clutter actor or GTK widget with ::destroy signal connected, or using the destroy(), dispose(), or remove() vfuncs. Because it would crash the application, it has been blocked.
Jan 12 11:38:10 gazelle-akr gnome-shell[3448]: The offending callback was SourceFunc().
Jan 12 11:38:10 gazelle-akr gnome-shell[3448]: Attempting to run a JS callback during garbage collection. This is most likely caused by destroying a Clutter actor or GTK widget with ::destroy signal connected, or using the destroy(), dispose(), or remove() vfuncs. Because it would crash the application, it has been blocked.
Jan 12 11:38:10 gazelle-akr gnome-shell[3448]: The offending callback was SourceFunc().
Jan 12 11:38:10 gazelle-akr gnome-shell[3448]: Attempting to run a JS callback during garbage collection. This is most likely caused by destroying a Clutter actor or GTK widget with ::destroy signal connected, or using the destroy(), dispose(), or remove() vfuncs. Because it would crash the application, it has been blocked.
Jan 12 11:38:10 gazelle-akr gnome-shell[3448]: The offending callback was SourceFunc().

...
```

**Comment by tunix** [comment] 2022-01-12 12:42
I have a similar issue with Intellij IDEA. When I have tiling enabled and open 2 or more projects in stacked tabs, it randomly jumps between tabs by itself and cause huge CPU spikes until I close all tabs until only 1 window is left. This behavior usually stops when IDEA is done with its background tasks. I believe this has something to do with focusing. I don't see flooding error messages in syslog. This behavior persists even if I downgrade to a previous commit of the flatpak package.

**Closed** 2022-01-12 19:18 UTC

**Comment by tunix** [comment] 2022-01-12 21:29
@mmstick - when will this update be released?

**Comment by jacobgkau** [comment] 2022-01-12 21:30
> @mmstick - thank you for the quick fix! when will this update be released?

This was answered here: https://github.com/pop-os/shell/pull/1314#issuecomment-1011433719

**Comment by aquatix** [comment] 2022-01-12 21:30
Cool, good stuff. Thanks for the quick fix!
