### ISSUE TITLE
Desktop background not updating  on wallpaper change

### ISSUE THREAD

**Issue by rysteph** [pop-os/shell#1276] opened 2021-12-17 02:35 UTC
After upgrading to 21.10, the desktop background does not update to reflect a change in wallpaper. It does appear to have changed when showing all workspaces, but then reverts to the previous background when a workspace is selected.

**Comment by StarpTech** [comment] 2022-01-09 15:44
Hi, I can reproduce it too. Any fix?

**Comment by rysteph** [comment] 2022-01-09 15:59
I have the problem on an older Acer laptop, but not on a gateway of about the same age. I haven't found a fix. If I do switch background using Settings->Background, I then switch to Settings->Displays and toggle the 'Fraction Scaling' button off and back on again which seems to fix things up. I wish there was an easier way like F5 to refresh the desktop or something. A proper fix would be better.

**Comment by jacobgkau** [comment] 2022-01-10 15:45
This is a duplicate of https://github.com/pop-os/pop/issues/2066.

If the issue stops after disabling the Pop Shell extension, please leave a comment on that issue so we can transfer it to the appropriate repository.

**Closed by jacobgkau** 2022-01-10 15:45 UTC

**Comment by rysteph** [comment] 2022-01-11 04:38
That did it. Thanks!

**Comment by rysteph** [comment] 2022-01-21 14:09
Pop Shell extension is still disabled and the issue is happening again :(

**Comment by Daasin** [comment] 2022-02-08 21:03
> Pop Shell extension is still disabled and the issue is happening again :(

Same for me 🤔
