### ISSUE TITLE
The hint remains active after minimizing all windows

### ISSUE THREAD

**Issue by Stup0r38** [pop-os/shell#365] opened 2020-05-18 13:16 UTC
**Distribution (run `cat /etc/os-release`):**
NAME=Fedora
VERSION="32 (Workstation Edition)"
ID=fedora
VERSION_ID=32
VERSION_CODENAME=""
PLATFORM_ID="platform:f32"
PRETTY_NAME="Fedora 32 (Workstation Edition)"
ANSI_COLOR="0;34"
LOGO=fedora-logo-icon
CPE_NAME="cpe:/o:fedoraproject:fedora:32"
HOME_URL="https://fedoraproject.org/"
Xorg
 

**Issue/Bug Description:**
Even after all the windows have been minimized, the hint around the last windows remains active

**Steps to reproduce (if you know):**
1)Open any app
2)Minimize it
3)The hint is still present

**Expected behavior:**
The hint should disappear and appear again only when the app is visible

![Schermata da 2020-05-18 15-15-06](https://user-images.githubusercontent.com/65513091/82217263-79ce8b00-991a-11ea-9945-2ae55171a31a.png)
![Schermata da 2020-05-18 15-15-10](https://user-images.githubusercontent.com/65513091/82217276-7e933f00-991a-11ea-8fe8-c5514c869827.png)

**Comment by nicolae-stroncea** [comment] 2020-05-18 14:35
Similar issue happens if you go to a new workspace, go to the overview and return. On return, the active hint is now present on the empty workspace.

If you think this is a separate bug, let me know and I can file a new issue for it.

**Comment by Stup0r38** [comment] 2020-05-18 14:44
I don't have this bug, I suggest you to create a new issue for that

**Comment by sammyspark** [comment] 2020-06-26 01:37
I also have this issue, running on Ubuntu 20.04.

**Comment by jmmaranan** [comment] 2020-08-10 22:46
@mmstick - I think this is also a dupe of issues mentioned in #487 - can be closed?

**Closed** 2020-08-10 23:48 UTC
Labels: bug
