### ISSUE TITLE
Can't close activities section

### ISSUE THREAD

**Issue by ilteoood** [pop-os/shell#1086] opened 2021-07-15 10:53 UTC
**(1) Issue/Bug Description:**

With the latest update, installed this morning, once opened "Activities" section can't be closed.

**(2) Steps to reproduce (if you know):**

Open activities

**(3) Expected behavior:**

It can be opened and closed, both with mouse or super key

**(4) Distribution (run `cat /etc/os-release`):**
 
NAME="Pop!_OS"
VERSION="20.04 LTS"
ID=pop
ID_LIKE="ubuntu debian"
PRETTY_NAME="Pop!_OS 20.04 LTS"
VERSION_ID="20.04"
HOME_URL="https://pop.system76.com"
SUPPORT_URL="https://support.system76.com"
BUG_REPORT_URL="https://github.com/pop-os/pop/issues"
PRIVACY_POLICY_URL="https://system76.com/privacy"
VERSION_CODENAME=focal
UBUNTU_CODENAME=focal
LOGO=distributor-logo-pop-os

**(5) Gnome Shell version:**

GNOME Shell 3.36.7

**(6) Pop Shell version (run `apt policy pop-shell` or provide the latest commit if building locally):**

```
pop-shell:
  Installed: 1.1.0~1626203716~20.04~021c931
  Candidate: 1.1.0~1626203716~20.04~021c931
  Version table:
 *** 1.1.0~1626203716~20.04~021c931 1001
       1001 http://ppa.launchpad.net/system76/pop/ubuntu focal/main amd64 Packages
       1001 http://ppa.launchpad.net/system76/pop/ubuntu focal/main i386 Packages
        100 /var/lib/dpkg/status
```

**(7) Where was Pop Shell installed from:**

3 month ago, from USB image

**(8) Monitor Setup (2 x 1080p, 4K, Primary(Horizontal), Secondary(Vertical), etc):**

1x 1080p Primary monitor, horizontal

**(9) Other Installed/Enabled Extensions:**

alt-tab-raise-first-window@system76.com
always-show-workspaces@system76.com
clipboard-indicator@tudmotu.com
ding@rastersoft.com
netspeed@hedayaty.gmail.com
persistent-email-notifications@fthx
pop-shel
pop-shell
pop-shell@system76.com
pop-shop-details@system76.com
system76-power@system76.com
ubuntu-appindicators@ubuntu.com

**(10) Other Notes:**

The issue started from the updates installed this morning.

**Comment by ilteoood** [comment] 2021-07-15 10:59
Additional note: if I disable the pop-shell extension, everything start to work as expected.

**Comment by vsarin92** [comment] 2021-07-15 11:38
I was actually coming here to create the issue when I realized it was pop-shell

Hope this gets fixed soon!

The other issue that is actually the same as this is posted under pop:
https://github.com/pop-os/pop/issues/1814

Workaround is to use super + T to open up a terminal then `gnome-extensions disable pop-shell@system76.com`

Original link where I found the workaround: 
https://www.reddit.com/r/pop_os/comments/okoenl/activities_and_apps_menu_broken/

**Comment by kjcole** [comment] 2021-07-15 11:38
I am also experiencing the same problem. I launch an application, but the sidebars showing the common choices, the workspaces -- of which there are none, apparently, and the search form all remain visible and slightly grayed out. The launched application never appears, though the system believes it to be running somewhere.

**Comment by gustavoctadei** [comment] 2021-07-15 11:47
For me, opening the Extensions app and disabling "Show minimize to tray Windows" in the Pop Shell settings fixed the issue.

**Comment by Stalkerfish** [comment] 2021-07-15 12:31
> For me, opening the Extensions app and disabling "Show minimize to tray Windows" in the Pop Shell settings fixed the issue.

That worked for me! Thanks so much, I was thinking about hoping because of this.

**Comment by derpmatt** [comment] 2021-07-15 13:29
>For me, opening the Extensions app and disabling "Show minimize to tray Windows" in the Pop Shell settings fixed the issue.

Same here. Thanks.

**Comment by jacobgkau** [comment] 2021-07-15 13:35
This is a duplicate of https://github.com/pop-os/shell/issues/1072, so I'm closing as a duplicate. Please watch the other issue for updates.

**Closed by jacobgkau** 2021-07-15 13:35 UTC
