### ISSUE TITLE
Feature Request: I3 Like workspace management with multiple monitors

### ISSUE THREAD

**Issue by Geigerkind** [pop-os/shell#1130] opened 2021-08-06 17:00 UTC
Hello,
Currently the definition of a single workspace is all monitors. What I would love to see is that every monitor is his own workspace.

This is important to me, since my whole navigation was based on the workspaces. I had for every group of windows a workspace, which was nice. 
Having 3 monitors I loose much of my ability to navigate using workspace switching, since I will never need 30 different groups of windows.

The current navigation feels very clunky, its hard to navigate to a specific monitor in a specific workspace currently.

An added benefit is that with this feature my windows wont get randomly assigned to a workspace and switched around, when I detach monitors or go to or come back from work with my laptop.

**Comment by jacobgkau** [comment] 2021-08-06 17:03
Thank you for the request. This is a known desire and is on our radar. I'm closing as a duplicate of https://github.com/pop-os/shell/issues/823.

**Closed by jacobgkau** 2021-08-06 17:03 UTC

**Comment by Geigerkind** [comment] 2021-08-06 17:05
Oh, thank you, I didnt see that!
