### ISSUE TITLE
error TS2345 during build

### ISSUE THREAD

**Issue by yochananmarqos** [pop-os/shell#1155] opened 2021-08-30 19:17 UTC
**(1) Issue/Bug Description:**
`make` is failing after today's commits using Typescript 4.4.2.

```
UUID is "pop-shell@system76.com"
depcheck
rm -rf _build target
env PROJECTS="color_dialog floating_exceptions" ./scripts/transpile.sh
++ pwd
+ pwd=/build/pop-shell-git/src/shell
+ rm -rf _build
+ for proj in ${PROJECTS}
+ mkdir -p _build/color_dialog
+ glib-compile-schemas schemas
+ tsc --p src/color_dialog
+ for proj in ${PROJECTS}
+ mkdir -p _build/floating_exceptions
+ tsc --p src/floating_exceptions
+ tsc
src/settings.ts:25:24 - error TS2345: Argument of type 'unknown' is not assignable to parameter of type 'string'.

25             global.log(err)
                          ~~~


Found 1 error.

make: *** [Makefile:38: compile] Error 2

```

**(4) Distribution (run `cat /etc/os-release`):**
 
```
NAME="Manjaro Linux"
ID=manjaro
ID_LIKE=arch
BUILD_ID=rolling
PRETTY_NAME="Manjaro Linux"
ANSI_COLOR="32;1;24;144;200"
HOME_URL="https://manjaro.org/"
DOCUMENTATION_URL="https://wiki.manjaro.org/"
SUPPORT_URL="https://manjaro.org/"
BUG_REPORT_URL="https://bugs.manjaro.org/"
LOGO=manjarolinux
```

**(5) Gnome Shell version:**

40.4

**(6) Pop Shell version (run `apt policy pop-shell` or provide the latest commit if building locally):**

0484ffb

**(7) Where was Pop Shell installed from:**
My own [PKGBUILD](https://github.com/yochananmarqos/pkgbuilds/blob/master/pop-shell-git/PKGBUILD) based on the `gnome-shell-extension-pop-shell-git` AUR package.

**Comment by mmstick** [comment] 2021-08-31 16:00
Duplicate of #1156

**Closed by mmstick** 2021-08-31 16:00 UTC
