### ISSUE TITLE
Auto-tiling/gaps do not work on Arch linux

### ISSUE THREAD

**Issue by jrop** [pop-os/shell#502] opened 2020-08-15 04:08 UTC
**Distribution (run `cat /etc/os-release`):**

```
NAME="Arch Linux"
PRETTY_NAME="Arch Linux"
ID=arch
BUILD_ID=rolling
ANSI_COLOR="38;2;23;147;209"
HOME_URL="https://www.archlinux.org/"
DOCUMENTATION_URL="https://wiki.archlinux.org/"
SUPPORT_URL="https://bbs.archlinux.org/"
BUG_REPORT_URL="https://bugs.archlinux.org/"
LOGO=archlinux
``` 

**Related Application and/or Package Version (run `apt policy pop-shell` or provide the latest commit if building locally):**

`master_focal`: `69415ea`

**Issue/Bug Description:**

All keyboard shortcuts work (switching windows, focusing workspaces, moving windows to workspaces, resizing windows, moving windows, etc.), however, the auto-tiling feature, whether toggled on or off behaves as if does absolutely nothing.  Windows do not auto-tile, and have to be manually managed.

**Steps to reproduce (if you know):**

```
# Arch linux:
$ git clone ...
$ npm i -g typescript 3.8
$ cd pop-os/shell
$ sh rebuild.sh
```

**Expected behavior:**

Windows should auto-tile.

**Other Notes:**

```
$ pacman -Q | grep gnome-shell
gnome-shell 1:3.36.4-1
```

**Comment by mmstick** [comment] 2020-08-15 04:10
Are you using X11 or Wayland?

**Comment by jrop** [comment] 2020-08-15 06:02
@mmstick Wayland

**Comment by mogorman** [comment] 2020-08-15 10:02
having same issue on nixos with wayland as well
gnome 3.36.4

**Comment by mogorman** [comment] 2020-08-15 10:10
does this feature not work in wayland?
https://github.com/pop-os/shell/blob/55c40ce66a5a51e83c083063a704372e18ca49e5/src/extension.ts#L1216

**Comment by mogorman** [comment] 2020-08-15 10:12
yup seems to be the case after reading https://github.com/pop-os/shell/issues/166 this issue is probably just a dupe of that

**Closed** 2020-08-15 15:59 UTC
