### ISSUE TITLE
Firefox isn't fullscreen when I open it at the first time.

### ISSUE THREAD

**Issue by laichiaheng** [pop-os/shell#570] opened 2020-09-27 13:10 UTC
**(1) Issue/Bug Description:**
![2020-09-27 21-05-22 的螢幕擷圖](https://user-images.githubusercontent.com/9532105/94365667-58ba4a00-0105-11eb-8fcc-ad1ba130f5d8.png)

**(2) Steps to reproduce (if you know):**
Open Firefox after I turn on my PC.

**(3) Expected behavior:**
Fullscreen

**(4) Distribution (run `cat /etc/os-release`):**
 Manjaro

**(5) Gnome Shell version:**

3.36.6

**(6) Pop Shell version (run `apt policy pop-shell` or provide the latest commit if building locally):**

```
Name            : gnome-shell-extension-pop-shell-git
Version         : r540.9286532-1
Description     : Pop Shell - Tiling window management in Gnome (WIP)
Architecture    : any
URL             : https://github.com/pop-os/shell
Licenses        : GPLv3
Groups          : None
Provides        : None
Depends On      : gnome-shell  pop-shell-shortcuts-git
Optional Deps   : None
Required By     : None
Optional For    : None
Conflicts With  : gnome-shell-extension-pop-shell
Replaces        : None
Installed Size  : 798.04 KiB
Packager        : Unknown Packager
Build Date      : 
Install Date    : 
Install Reason  : Installed as a dependency for another package
Install Script  : No
Validated By    : None
```

**(7) Where was Pop Shell installed from:**

AUR

**(8) Monitor Setup (2 x 1080p, 4K, Primary(Horizontal), Secondary(Vertical), etc):**

1080p

**(9) Other Installed/Enabled Extensions:**
cpufreq, Freon, GameMode, GSConnect, KStatusNotifierItem/AppIndicator Support, Pamac Updates Indicator, Sound Input & Output Device Chooser, User Themes

**(10) Other Notes:**

**Comment by laichiaheng** [comment] 2020-10-07 05:57
@mmstick It is worse on Xorg: https://youtu.be/PAkYIKOq56M

**Comment by mmstick** [comment] 2020-10-07 20:11
Sadly, I can't personally replicate it on any of my systems. Still, I'll look for solutions.

**Comment by mmstick** [comment] 2021-01-12 23:56
Duplicate of #388

**Closed by mmstick** 2021-01-12 23:56 UTC
