### ISSUE TITLE
Error when toggling firefox window title bar with tiling enabled

### ISSUE THREAD

**Issue by Toyonut** [pop-os/shell#207] opened 2020-04-20 09:27 UTC
**Distribution (run `cat /etc/os-release`):**
Pop!_OS 20.04 Beta
 
**Related Application and/or Package Version (run `apt policy pop-shell` or provide the latest commit if building locally):**
0.1.0~1587070228~20.04~761cfc1

**Issue/Bug Description:**
Firefox cannot enable or disable the titlebar with pop-shell tiling enabled. 
There is an error Window (x,x) does not have an actor, and therefore cannot be moved

**Steps to reproduce (if you know):**
Enable tiling
Start Firefox
Open the customize tab
Enable or disable the title bar checkbox

**Expected behavior:**
Firefox titlebar should enable or disable without error. 

**Other Notes:**
Issue occurs in virtualized environment and hardware. 
Once the error occurs, there are also multiple close buttons on the titlebar and the tab bar.
Occurring after full update and computer reboot. 

![Screenshot from 2020-04-20 21-16-57](https://user-images.githubusercontent.com/1227118/79735742-d905a380-834c-11ea-86de-219ed4350750.png)

Please let me know if there is any more info you need to debug this.

**Comment by leviport** [comment] 2020-04-20 16:03
This is a duplicate of https://github.com/pop-os/shell/issues/32 so I'll close this one for now. Thanks for reporting though!

**Closed by leviport** 2020-04-20 16:03 UTC
