### ISSUE TITLE
Terminal windows always have gaps even if gaps set to 0. pop_os 20.04

### ISSUE THREAD

**Issue by alperenkaplan** [pop-os/shell#329] opened 2020-05-11 03:24 UTC
**Distribution (run `cat /etc/os-release`):**
 Pop!_OS 20.04
 
 
**Related Application and/or Package Version (run `apt policy pop-shell` or provide the latest commit if building locally):**

0.1.0~1588777613~20.04~387bebf

**Issue/Bug Description:**

Terminal windows have gaps on their right and bottom edges when Tile Windows turned on even if gaps set to 0. This does not happen for windows of other apps.

![Screenshot from 2020-05-11 06-23-09](https://user-images.githubusercontent.com/48252753/81521474-ff1cd300-934f-11ea-960d-e56e4b42186b.png)

**Steps to reproduce (if you know):**

Turn on Tile Windows. Set Gaps to 0. Open a terminal window.

**Expected behavior:**

This:
![Screenshot from 2020-05-11 06-23-20](https://user-images.githubusercontent.com/48252753/81521488-07750e00-9350-11ea-9873-0052086727fa.png)

**Other Notes:**

**Comment by FrederikP** [comment] 2020-05-11 06:47
This is a duplicate of this issue: https://github.com/pop-os/shell/issues/213
I switched to terminator and no gaps appear.

**Closed** 2020-05-11 14:16 UTC
