### ISSUE TITLE
COSMIC Touchpad Gestures Don't Follow Natural Scrolling Settings

### ISSUE THREAD

**Issue by 12buntu** [pop-os/shell#1098] opened 2021-07-20 17:48 UTC
**(1) Issue/Bug Description:**
The title says it all. I love the new touchpad gestures, however they don't follow the natural scrolling settings.

**(2) Steps to reproduce (if you know):**
(Have a touchpad)
Turn on natural scrolling in settings.
Use the 4 finger gesture to switch workspaces.

**(3) Expected behavior:**
With natural scrolling on, when you move 4 fingers "UP" (from closer to you to closer to the screen) it should move to a lower workspace. When you move 4 fingers "DOWN" it should move to a higher workspace.

**(4) Distribution (run `cat /etc/os-release`):**
 21.04

**(5) Gnome Shell version:**
3.38.5

**(6) Pop Shell version (run `apt policy pop-shell` or provide the latest commit if building locally):**

```pop-shell:
  Installed: 1.1.0~1626357201~21.04~c1f2ea4
  Candidate: 1.1.0~1626357201~21.04~c1f2ea4
  Version table:
 *** 1.1.0~1626357201~21.04~c1f2ea4 1001
       1001 http://ppa.launchpad.net/system76/pop/ubuntu hirsute/main amd64 Packages
       1001 http://ppa.launchpad.net/system76/pop/ubuntu hirsute/main i386 Packages
        100 /var/lib/dpkg/status
```

**Comment by leviport** [comment] 2021-07-20 17:59
Duplicate of https://github.com/pop-os/cosmic/issues/110

I found a workaround, and I'll post it in that issue

**Closed by leviport** 2021-07-20 18:00 UTC
