### ISSUE TITLE
Missing navigation granularity: stacks

### ISSUE THREAD

**Issue by inducer** [pop-os/shell#1348] opened 2022-02-07 23:59 UTC
Suppose I have two stacks of windows:

- Stack A
    - Window A.1
    - Window A.2
    - Window A.3
- Stack B (to the right of Stack A)
    - Window B.1
    - Window B.2
    - Window B.3

Suppose A.1 is focused. Suppose I'd like A.1 and B.3 visible. I'm aware of the Super+Direction navigation primitive. This will not let me achieve what I want: Suppose I Super+Right until I'm on A.3, then over to B.1, continue Super+Right to B.3. Super+Left (to get back to A.1) then changes the state of Stack B, counter to my intentions. I can use the mouse or another window switcher to get to stack A, but it'd be nice if I could directly switch between stacks without changing the state of the stack itself, using a navigation primitive "native" to Pop Shell.

**Comment by jacobgkau** [comment] 2022-02-08 00:05
Thank you for the feature request. I'm closing this as a duplicate of https://github.com/pop-os/shell/issues/655 because it sounds like you're describing the same thing. Please let me know if I'm mistaken.

**Closed by jacobgkau** 2022-02-08 00:05 UTC

**Comment by inducer** [comment] 2022-02-08 00:21
Yep, that sounds about right. Sorry I missed that when searching.
