### ISSUE TITLE
Hint Remains active on empty workspace

### ISSUE THREAD

**Issue by nicolae-stroncea** [pop-os/shell#366] opened 2020-05-18 14:51 UTC
**Distribution (run `cat /etc/os-release`):**
 
 Fedora 32, Gnome 3.36, Xorg
 
**Related Application and/or Package Version (run `apt policy pop-shell` or provide the latest commit if building locally):**

339817fd7eea8e1cf58e57b217630262f01614c0

**Steps to reproduce (if you know):**
1. Go to new workspace.
2. Go to the overview
3. `Esc` to return from overview
4. Empty workspace now has an active hint applied to it.

**Expected behavior:**

No active hint applied

**Comment by leviport** [comment] 2020-05-18 22:29
I can confirm this one. Looks like the active hint doesn't get destroyed if you switch to an empty workspace from the activities overview. I can also reproduce it by using <kbd>Ctrl</kbd> + <kbd>Super</kbd> + <kbd>Down Arrow</kbd> while in the overview, as shown in this recording.

![Peek 2020-05-18 16-25](https://user-images.githubusercontent.com/13512097/82265517-5f99aa80-9924-11ea-9e97-53429a1a90db.gif)

**Comment by jmmaranan** [comment] 2020-08-12 17:08
@jacobgkau - I am not able to replicate this after applying #487 - It seems to be replicable in `dev_focal` which does not contain that fix.

**Comment by jacobgkau** [comment] 2020-08-12 21:11
> @jacobgkau - I am not able to replicate this after applying #487 - It seems to be replicable in `dev_focal` which does not contain that fix.

Confirmed, thank you! Closed by #487.

**Closed by jacobgkau** 2020-08-12 21:11 UTC
Labels: bug
