### ISSUE TITLE
some apps' window is graphically stretched vertically upon opening the app 

### ISSUE THREAD

**Issue by Hujair** [pop-os/shell#1232] opened 2021-10-30 06:10 UTC
**(1) Issue/Bug Description:**

some apps' window is graphically streached vertically upon opening the app , the aspect ratio goes to normal only when I change the orientation of the window and then becomes normal in any orientation.

**(2) Steps to reproduce (if you know):**
by only opening blender or firefox  

**(3) Expected behavior:**

**(4) Distribution (run `cat /etc/os-release`):**
 
NAME="Manjaro Linux"
ID=manjaro
ID_LIKE=arch
BUILD_ID=rolling
PRETTY_NAME="Manjaro Linux"
ANSI_COLOR="32;1;24;144;200"
HOME_URL="https://manjaro.org/"
DOCUMENTATION_URL="https://wiki.manjaro.org/"
SUPPORT_URL="https://manjaro.org/"
BUG_REPORT_URL="https://bugs.manjaro.org/"
LOGO=manjarolinux

**(5) Gnome Shell version:**

GNOME Shell 40.5

**(6) Pop Shell version (run `apt policy pop-shell` or provide the latest commit if building locally):**

1.2.0+151+g5220303-1

**(7) Where was Pop Shell installed from:**

AUR

**(8) Monitor Setup (2 x 1080p, 4K, Primary(Horizontal), Secondary(Vertical), etc):**

2 x 1080, horizontal identical monitors 

**(9) Other Installed/Enabled Extensions:**

none

**(10) Other Notes:**

before I upgrade my gpu from amd to nvidia the problem was not present.

**Comment by wrestlerdude** [comment] 2021-11-02 16:25
I get the same issue, but only with the kitty terminal. To add some additional information, I use an optimus laptop setup, and only get this issue when I set dedicated graphics only (NVIDIA). I'm using Pop 21.10.

**Comment by jacobgkau** [comment] 2021-11-02 16:40
I think I can recreate this on an oryp8:

![Screenshot from 2021-11-02 10-38-58](https://user-images.githubusercontent.com/7199422/139907960-0ea9603e-de51-45ec-9157-01803f346902.png)

It looks like the window was sized as if it was going to fit between the top and bottom panels, but then stretched to fill the entire display instead.

**Comment by fnune** [comment] 2021-11-02 23:47
Just here to report that I'm facing the same issue on Arch Linux!

**Comment by wrestlerdude** [comment] 2021-11-03 11:50
> I think I can recreate this on an oryp8:
> 
> ![Screenshot from 2021-11-02 10-38-58](https://user-images.githubusercontent.com/7199422/139907960-0ea9603e-de51-45ec-9157-01803f346902.png)
> 
> It looks like the window was sized as if it was going to fit between the top and bottom panels, but then stretched to fill the entire display instead.

Same here, this is what it looks like for me:
![Screenshot from 2021-11-03 11-49-40](https://user-images.githubusercontent.com/26298518/140054929-646bfdbd-c583-4117-a90d-da0fa8e28ed2.png)

**Comment by fnune** [comment] 2021-11-03 12:47
I'm sorry that I don't have time to investigate this more, but this hasn't only happened to me with Kitty, it's also happened with Nautilus (Files).

**Comment by fnune** [comment] 2021-11-04 15:27
Possibly related: the Software app launches like this with gaps:

![image](https://user-images.githubusercontent.com/16181067/140353625-5f26782e-b1a5-47de-872b-d5385c60eb2c.png)

**Comment by fnune** [comment] 2021-11-04 15:28
Calendar sometimes open stretched, and sometimes correctly.

Stretched:
![image](https://user-images.githubusercontent.com/16181067/140354311-f2fe1d9c-5a49-4c59-a89a-6efd8e2a6fce.png)

Correctly:
![image](https://user-images.githubusercontent.com/16181067/140354444-7147a638-18ec-457d-a41f-508133b1ee0a.png)

**Comment by jacobgkau** [comment] 2021-11-04 15:33
> Possibly related: the Software app launches like this with gaps on `4`:
> 
> ![image](https://user-images.githubusercontent.com/16181067/140353625-5f26782e-b1a5-47de-872b-d5385c60eb2c.png)

This doesn't look like the Pop theme and Pop!_OS does not include GNOME Software. What distribution are you using? Are you saying GNOME Software is stretched in that screenshot, or are you just pointing out the gap issue? (Trying to figure out if this is the same issue as what's affecting Kitty on Pop!_OS NVIDIA or not.)

> @jacobgkau on your oryp8 are you using dedicated or hybrid graphics? This could narrow down the NVIDIA theory.

I switched to NVIDIA (and installed kitty) specifically to see if I could recreate the issue.

**Comment by fnune** [comment] 2021-11-04 16:05
> This doesn't look like the Pop theme and Pop!_OS does not include GNOME Software. What distribution are you using? Are you saying GNOME Software is stretched in that screenshot, or are you just pointing out the gap issue? (Trying to figure out if this is the same issue as what's affecting Kitty on Pop!_OS NVIDIA or not.)

I'm trying to figure out the same. I'm thinking the gap issue may or may not be the same problem as the window stretching. OBS certainly looks more like the stretched window problem.

I use Arch Linux and followed the instructions here to install `pop-shell`: https://support.system76.com/articles/pop-shell/

**Comment by fnune** [comment] 2021-11-04 16:08
Happening in Krita as well:

![image](https://user-images.githubusercontent.com/16181067/140376181-20e18b7d-1354-4dda-a623-9de1f099bd55.png)

**Comment by wrestlerdude** [comment] 2021-11-05 11:33
Just to report, I just encountered this issue for the first time with Telegram.

**Comment by Leleat** [comment] 2021-11-05 23:32
I am using Fedora 35 (GNOME Shell 41) and pop-shell from the dnf repo.

I can reliable reproduce this by starting kitty and GNOME Software in quick succession. I only use the Ryzen 3 3200u  without a dedicated GPU... so might not be related to NVIDIA.

Possibly a bug in combination with the new mutter / gnome-shell? There were a bunch of reports about windows extending under the top bar on GNOME's [gitlab](https://gitlab.gnome.org/GNOME/mutter/-/issues/1627) (see all referenced issues). Although the reports were all about Wayland, so I don't know...

**Comment by ehardesty** [comment] 2021-11-10 16:48
I am seeing this happen using an Intel GPU.

I have also seen it happen with Firefox among other apps but haven't been able to figure out how to reliably reproduce it. My workaround has been to toggle maximize on and off.

**Comment by BartleyTheShopkeeper** [comment] 2021-11-11 02:45
This happens to me no matter which distro. I've tested Debian and Fedora with Pop Shell. It also happens regardless if I use Nvidia. This only affects me once I update to GNOME 41, however. It also affects me whether or not I use Wayland or X11. At GNOME 40.4 I was perfectly fine.

I used 
`sudo apt-mark hold gnome-shell`
and
`sudo apt-mark hold mutter`
and then upgraded to the latest of Debian testing. I haven't experienced the issue since. I think bugs have been reported that are similar, but without any extensions, so I am guessing it is either gnome-shell or mutter.

**Comment by fnune** [comment] 2021-11-11 07:27
It happened to me both on GNOME 40 and 41.

**Comment by PixsaOJ** [comment] 2021-11-11 13:53
Happens to me after upgrading to 21.10, Gnome 40.4

**Comment by spaghetus** [comment] 2021-11-11 16:48
Also happens to me, I'm using GNOME 40.4 under NVIDIA and X11 on Fedora Silverblue 34.

**Comment by BartleyTheShopkeeper** [comment] 2021-11-11 16:48
> It happened to me both on GNOME 40 and 41.




> Also happens to me, I'm using GNOME 40.4 under NVIDIA and X11 on Fedora Silverblue 34.

Do you two use X11 or Wayland?

**Comment by fnune** [comment] 2021-11-11 17:43
> Do you two use X11 or Wayland?

X11, proprietary NVIDIA.

**Comment by PixsaOJ** [comment] 2021-11-11 18:18
X11, proprietary NVIDIA. Me too.

**Comment by PixsaOJ** [comment] 2021-11-12 07:35
I don't know if this helps, but it only happened on first launch so far. When I open another instance of browser, it does not do it.

![image](https://user-images.githubusercontent.com/12684017/141428088-6c383b49-8fbb-40cc-b6b8-6c2db31f4066.png)

**Comment by PixsaOJ** [comment] 2021-11-13 13:16
I think it only happens in tiling mode.

**Comment by dtgoitia** [comment] 2021-11-14 23:17
I get this issue intermittently on Arch Linux as well (has been going on for more than a month):

- Linux arch 5.15.2-arch1-1 #1 SMP PREEMPT
- Processor: Intel
- Graphics: Mesa Intel UHD Graphics 620 (WHL GT2)
- X11
- GNOME 41.1 right now, but the issue has happened with previous versions

The problem is gone when I disable the tilling mode - which has been my workaround when a window opened stretched for 3-4 times in a row. Often it works fine on the second/third attempt, but sometimes I can only get the right shape of the window by disabling the tilling, opening the desired window, and enabling back the tiling.

Happy to provide logs if you point me in the right direction

**Comment by mmstick** [comment] 2021-11-14 23:24
I think most helpful is bisecting the exact commit in Mutter or GNOME Shell where this started happening.

**Comment by PixsaOJ** [comment] 2021-11-17 08:21
> I get this issue intermittently on Arch Linux as well (has been going on for more than a month):
> 
>     * Linux arch 5.15.2-arch1-1
> 
>     * Processor: Intel
> 
>     * Graphics: Mesa Intel UHD Graphics 620 (WHL GT2)
> 
>     * X11
> 
>     * GNOME 41.1 right now, but the issue has happened with previous versions
> 
> 
> The problem is gone when I disable the tilling mode - which has been my workaround when a window opened stretched for 3-4 times in a row. Often it works fine on the second/third attempt, but sometimes I can only get the right shape of the window by disabling the tilling, opening the desired window, and enabling back the tiling.
> 
> Happy to provide logs if you point me in the right direction

If you are struggling with fixing it, you can just maximize and unmaximize the window.

**Comment by BartleyTheShopkeeper** [comment] 2021-11-23 07:03
> I think most helpful is bisecting the exact commit in Mutter or GNOME Shell where this started happening. Between 40.4 and 40.5.

I checked the debian package tracker, probably not the best source, but a source nonetheless.

Gnome-Shell:
> gnome-shell (40.5-1) unstable; urgency=medium
     **- Optimize rendering of fullscreen zoom**
     - Fix glitchy launch animations when leaving overview
     - Fix wrong separator position in dash
     - Fix OSK not registering button presses on X11
     **- Fix work area getting messed up by hidden panels**
     - Fix IM candidate popover position

Mutter:
> mutter (40.5-1) unstable; urgency=medium
     - Fix monitor screencast scanouts
     - Fix middle-click emulation support on X11

I doubt it has to do with mutter, but I bolded my guesses as to the possible source of the issue. Both in Gnome-Shell.

**Comment by BerenLuth** [comment] 2021-12-01 13:44
I have been facing the same issue on 3 different pcs, all with manjaro, both with gnome version 40.4 and also 41. 
I noticed it happens both in wayland and also X11.

The 3 pcs has very different hardware:
- dell xps 13, i5 5th generation with integrated gpu
- laptop toshiba with i7 8th generation with integrated gpu (almost fresh install, i barely used it)
- desktop pc, with ryzen 7 3700x and nvidia gpu

I haven't tested it deeply, but the issue seems to appear only when I'm in tiling mode.

When on X11, restarting the graphical session (alt+f2 and then type r and hit enter) seems to fix the issue for the opened windows, but then it keeps happening again when I'm opening something else.

**Comment by leviport** [comment] 2021-12-01 16:47
I'm starting to think this might have something to do with DPI scaling. On addw2 (4k display, 200% scaled by default), this is what Cura looks like when launched with tiling turned off, then I turn tiling back on after it's open:
![Screenshot from 2021-12-01 09-24-50](https://user-images.githubusercontent.com/13512097/144274434-01cf4764-1de9-4be0-9c00-258a65274942.png)

Here's what I first saw when launching Cura with tiling turned on:
![Screenshot from 2021-12-01 09-24-37](https://user-images.githubusercontent.com/13512097/144274937-dabe6c7e-1851-43bb-815e-c153dd0fe168.png)

Then after that, I turned scaling to 100%, then back to 200% and Cura stretched even more when I launched it with tiling on:
![Screenshot from 2021-12-01 09-28-01](https://user-images.githubusercontent.com/13512097/144275090-55e77deb-27fa-4046-8398-db07d7892e4f.png)

**Comment by mmstick** [comment] 2021-12-01 17:08
For what it's worth, I haven't encountered this at all lately with 100% scaling on any of my systems.

**Comment by BartleyTheShopkeeper** [comment] 2021-12-01 18:36
I have encountered this issue exclusively at 100% scaling. Haven't tested anything else.

**Comment by leviport** [comment] 2021-12-01 19:14
It seems pretty easily reproducible with Cura, so that might be worth testing. I just saw it on darp6 and in a VM. It usually only stretches a little, like in my second picture, but starting and closing Cura multiple times sometimes leads to it getting stretched a bunch like my third picture.

**Comment by jmmaranan** [comment] 2021-12-03 03:41
I think this is happening on windows that were previously maximized and pop-shell tries to unmax it but it is still moving/transitioning to the position. Perhaps maybe the speed improvements in gnome-shell 4x made this much visible.

**Comment by PixsaOJ** [comment] 2021-12-03 09:06
> I think this is happening on windows that were previously maximized and pop-shell tries to unmax it but it is still moving/transitioning to the position during tiling. Perhaps maybe the speed improvements in gnome-shell 4x made this much visible.

I am experimenting right now. It does not seem to matter if app was maximized before or not

**Comment by PixsaOJ** [comment] 2021-12-03 09:11
I also changed different scaling, and fractional scaling. No different results there. 

On scale 200% without fractional scaling, everything is bigger. It would not be wise to say that the bug resulted in bigger results.

**Comment by jmmaranan** [comment] 2021-12-03 16:14
> I am experimenting right now. It does not seem to matter if app was maximized before or not

Popshell and mutter/clutter might be playing tug of war on the window, it is easily reproduced on my end when the window was maximized, close it, tiling on if it wasn't before, open that window - seeing it on single or multi display running an i5/intel machine.

I added a PR hoping that fixes it. How and why it got introduced. Don't know. But that code I remember was there before.

**Closed** 2021-12-03 18:40 UTC

**Comment by PixsaOJ** [comment] 2021-12-04 15:08
> > I am experimenting right now. It does not seem to matter if app was maximized before or not
> 
> Popshell and mutter/clutter might be playing tug of war on the window, it is easily reproduced on my end when the window was maximized, close it, tiling on if it wasn't before, open that window - seeing it on single or multi display running an i5/intel machine.
> 
> I added a PR hoping that fixes it. How and why it got introduced. Don't know. But that code I remember was there before.

I agree, it should be pop-shell and mutter playing war on applying transforms.
Hope your commit fixes it.

However, I can confirm that the bug happens no matter if the window was maximized or was in tiling mode before.
It only happens when tiling mode is on, but maximizing does not matter.

**Comment by PixsaOJ** [comment] 2021-12-04 15:11
Just got update, it worked!

**Comment by jmmaranan** [comment] 2021-12-04 15:35
> Just got update, it worked!

Thanks for the update!

**Comment by flokli** [comment] 2023-05-02 15:57
It might be this issue is back - I opened #1621.
