### ISSUE TITLE
[Feature request] Make mouse follow behavior configurable on "focus" commands

### ISSUE THREAD

**Issue by thiagoa** [pop-os/shell#1203] opened 2021-10-06 13:08 UTC
When using the `focus-up`, `focus-down`, `focus-left`, and `focus-right` commands the mouse moves to the top left of the focused window. That's useful but for _some_ workflows, but not all possible workflows.

There are workflows where a user needs to switch between some applications but the mouse is only used on one of them. The user may even leave their cursor still in a strategic place but pop-shell will keep moving it across the screen, which may be annoying especially on larger monitors or when using smaller cursors.

That said, I suggest implementing a new setting like "Mouse follows focus" (boolean) to allow the user to turn off that behavior.

**Comment by MikulasVanousek** [comment] 2021-10-08 09:11
I think it would be amazing if pop shell saved the position of the mouse for each window separately. So if you switch to a window, your mouse will just appear where you last left it.

**Comment by jacobgkau** [comment] 2021-10-08 17:52
The request for a feature to disable moving the mouse cursor on keyboard focus change was made in https://github.com/pop-os/shell/issues/1188. I'm closing this as a duplicate of that one, and will rename it so it's easier to find.

Saving cursor position for every window individually sounds a lot more complicated, but anyone's free to open a separate feature request issue for that as well if they feel it should be tracked.

**Closed by jacobgkau** 2021-10-08 17:52 UTC
