### ISSUE TITLE
Fullscreen videos misaligned when entered from an auto tiled web browser window

### ISSUE THREAD

**Issue by andree-rehnberg** [pop-os/shell#267] opened 2020-05-03 21:19 UTC
**Distribution (run `cat /etc/os-release`):**

```
 NAME="Pop!_OS"
VERSION="20.04 LTS"
ID=pop
ID_LIKE="ubuntu debian"
PRETTY_NAME="Pop!_OS 20.04 LTS"
VERSION_ID="20.04"
HOME_URL="https://system76.com/pop"
SUPPORT_URL="http://support.system76.com"
BUG_REPORT_URL="https://github.com/pop-os/pop/issues"
PRIVACY_POLICY_URL="https://system76.com/privacy"
VERSION_CODENAME=focal
UBUNTU_CODENAME=focal
LOGO=distributor-logo-pop-os
```

**Related Application and/or Package Version (run `apt policy pop-shell` or provide the latest commit if building locally):**

```
pop-shell:
  Installed: 0.1.0~1588274983~20.04~586efcc
  Candidate: 0.1.0~1588274983~20.04~586efcc
  Version table:
 *** 0.1.0~1588274983~20.04~586efcc 1001
       1001 http://ppa.launchpad.net/system76/pop/ubuntu focal/main amd64 Packages
       1001 http://ppa.launchpad.net/system76/pop/ubuntu focal/main i386 Packages
        100 /var/lib/dpkg/status

```

**Issue/Bug Description:**

There's a gap above and a small one to the left side of a fullscreen video when the fullscreen mode is entered from a tiled web browser window.

![Screenshot from 2020-05-03 23-08-17](https://user-images.githubusercontent.com/2207753/80925887-cb600d00-8d93-11ea-8b5e-3284191ade9f.png)

**Steps to reproduce (if you know):**

* Enable window tiling
* Open web browser (Chrome in my case)
* Open a youtube video in fullscreen
* Video is now misaligned

**Expected behavior:**

The fullscreen video to be perfectly centered.

**Other Notes:**

\-

**Comment by matguidi** [comment] 2020-05-03 23:41
I confirm the bug on Manjaro, with pop-shell r397.586efcc-1. Also, I noticed that when a video is played fullscreen Gnome Shell's top bar disappears. Is this behaviour intended?

**Comment by laichiaheng** [comment] 2020-05-04 01:17
Same here on Manjaro Testing Branch.

**Comment by mmstick** [comment] 2020-05-04 13:12
Duplicate of #248

**Closed by mmstick** 2020-05-04 13:12 UTC
