### ISSUE TITLE
Launcher shortcut

### ISSUE THREAD

**Issue by xdursoc** [pop-os/shell#263] opened 2020-05-03 16:42 UTC
**Distribution (run `cat /etc/os-release`): Ubuntu 20.04
 
 
 
**Related Application and/or Package Version (run `apt policy pop-shell` or provide the latest commit if building locally):**

**Issue/Bug Description: The launcher shortcut does not work on **Italian keyboard** due to the fact the Super + / corresponds to Super + 7. In Linux systems based on ubuntu typing Super + number allow to launch an application from the dock corresponding to the number chosen. 

**Steps to reproduce (if you know):**

**Expected behavior:

**Other Notes:**

**Comment by andree-rehnberg** [comment] 2020-05-03 20:50
Also experiencing this on a Swedish keyboard.

**Comment by ThaSiouL** [comment] 2020-05-03 20:53
Seems like it's the same topic as #196.

**Comment by mmstick** [comment] 2020-05-04 13:14
Duplicate of #196

**Closed by mmstick** 2020-05-04 13:14 UTC
