### ISSUE TITLE
"Move window one monitor up" and "Move window one monitor down" keyboard shortcuts don't work with window tiling enabled.

### ISSUE THREAD

**Issue by wulfep** [pop-os/shell#541] opened 2020-09-10 20:32 UTC
**Distribution (run `cat /etc/os-release`):**
 NAME="Pop!_OS"
VERSION="20.04 LTS"
ID=pop
ID_LIKE="ubuntu debian"
PRETTY_NAME="Pop!_OS 20.04 LTS"
VERSION_ID="20.04"
HOME_URL="https://pop.system76.com"
SUPPORT_URL="https://support.system76.com"
BUG_REPORT_URL="https://github.com/pop-os/pop/issues"
PRIVACY_POLICY_URL="https://system76.com/privacy"
VERSION_CODENAME=focal
UBUNTU_CODENAME=focal
LOGO=distributor-logo-pop-os

 
 
**Related Application and/or Package Version (run `apt policy $PACKAGE NAME`):**

**Issue/Bug Description:**
"Move window one monitor up" and "Move window one monitor down" keyboard shortcuts don't work with window tiling enabled.  They work perfectly fine with it disabled, but when it is enabled, the window will move to the other monitor with the typical animation, then immediately go back to where it was.  Because of this, the only way to move a window from one monitor to the other is to manually drag it.  I do not know if it is the same with the left/right versions since I only have my monitors in a vertical configuration.

**Steps to reproduce (if you know):**
Enable window tiling and use the shortcut

**Expected behavior:**
The window moves to the other monitor and then is tiled with the windows there.

**Other Notes:**

**Comment by jacobgkau** [comment] 2020-09-10 20:34
Duplicate of https://github.com/pop-os/shell/issues/522.

**Closed by jacobgkau** 2020-09-10 20:34 UTC
