### ISSUE TITLE
Right Hand Side overflow

### ISSUE THREAD

**Issue by afolarin** [pop-os/shell#431] opened 2020-06-18 08:40 UTC
**Distribution (run `cat /etc/os-release`):**
DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=20.04
DISTRIB_CODENAME=focal
DISTRIB_DESCRIPTION="Ubuntu 20.04 LTS"
NAME="Ubuntu"
VERSION="20.04 LTS (Focal Fossa)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 20.04 LTS"
VERSION_ID="20.04"
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
VERSION_CODENAME=focal
UBUNTU_CODENAME=focal
 
**Related Application and/or Package Version (run `apt policy pop-shell` or provide the latest commit if building locally):**
commit 830dd7a9177d9ebebb0024d2fc5312caa485c099

**Issue/Bug Description:**
When launching windows, where there's a window that has a minimum horizontal size, these seem to overflow on the RHS of the screen -- even though the LHS window has lots of room to reduce. Not sure if this is a feature (it could be), but to me, it would seem more appropriate to automatically redistribute the screen realestate more evenly where there is too much contention on the RHS?

**Steps to reproduce (if you know):**
Keep adding windows then include some that have a min horizontal size e.g. the Settings, System Monitor, MS Teams [screenshot below]
Windows can be used to reproduce this bug. 

**Expected behavior:**
Where there's a RHS overflow off screen, adjust the central bifurcation to prevent this.

**Other Notes:**
![2020-06-18_09-23](https://user-images.githubusercontent.com/2489685/84997997-27fe6800-b147-11ea-86b9-36737ab8d485.png)

**Comment by mmstick** [comment] 2020-07-01 04:46
Duplicate of #85

**Closed by mmstick** 2020-07-01 04:46 UTC
