### ISSUE TITLE
Super + / doesn't work on non-English layout

### ISSUE THREAD

**Issue by weiss-d** [pop-os/shell#546] opened 2020-09-14 07:53 UTC
Hi!
When I'm using Russian keyboard layout all shortcuts with `Super` key seem to work except `Super + /`.

 ```bash
$ cat /etc/os-release
NAME="Pop!_OS"
VERSION="20.04 LTS"
ID=pop
ID_LIKE="ubuntu debian"
PRETTY_NAME="Pop!_OS 20.04 LTS"
VERSION_ID="20.04"
HOME_URL="https://pop.system76.com"
SUPPORT_URL="https://support.system76.com"
BUG_REPORT_URL="https://github.com/pop-os/pop/issues"
PRIVACY_POLICY_URL="https://system76.com/privacy"
VERSION_CODENAME=focal
UBUNTU_CODENAME=focal
LOGO=distributor-logo-pop-os
```
```xml
 $ cat /usr/share/gnome/gnome-version.xml
<?xml version="1.0"?>
<gnome-version>
 <platform>3</platform>
 <minor>36</minor>
 <micro>3</micro>
 <distributor>Ubuntu</distributor>
 <!--<date></date>-->
</gnome-version> 
```

```bash
$ apt policy pop-shell
pop-shell:
  Installed: 0.1.0~1599583364~20.04~017c92e
  Candidate: 0.1.0~1599583364~20.04~017c92e
  Version table:
 *** 0.1.0~1599583364~20.04~017c92e 1001
       1001 http://ppa.launchpad.net/system76/pop/ubuntu focal/main amd64 Packages
       1001 http://ppa.launchpad.net/system76/pop/ubuntu focal/main i386 Packages
        100 /var/lib/dpkg/status
```

**Comment by leviport** [comment] 2020-09-14 14:54
Duplicate of https://github.com/pop-os/gnome-shell/issues/38

**Closed by leviport** 2020-09-14 14:54 UTC
