### ISSUE TITLE
Tiliing goes out of frame

### ISSUE THREAD

**Issue by danarel** [pop-os/shell#206] opened 2020-04-19 23:44 UTC
Upgrade from 19.10 -> 20.10
(same issue reproduced on Majaro Linux as well)

Attached screenshot shows that my Terminal window (Kitty) is being pushed out of view at the bottom. (Ignore all the errors! - unless you can fix my Ruby issue too).

![gnome-shell-screenshot-SRE3I0](https://user-images.githubusercontent.com/46383059/79670232-5b883a80-8176-11ea-9aea-ccf60f068d56.png)

In another screenshot, I see the two tiled windows overlapping.

![Screenshot-20200418131640-959x658](https://user-images.githubusercontent.com/46383059/79670328-e9642580-8176-11ea-9900-84f455c2dbf2.png)

**Comment by danarel** [comment] 2020-04-20 20:07
This seems to happen most on Sublime Text and Kitty terminal. I don't see the same issue happening on more popular apps like Firefox.

**Comment by WatchMkr** [comment] 2020-04-21 18:44
I haven't seen this with simply launching and closing Kitty terminal with different layouts. This looks similar to an open multi-monitor and monitor hotplug bug. Are you using multiple monitors? If yes, posting a Displays screenshot will help.

**Comment by danarel** [comment] 2020-04-21 18:47
Yes, I am using 2 monitors. I will be sure to post a display screenshot soon.

**Comment by WatchMkr** [comment] 2020-04-21 19:35
Actually, that's okay. This looks like a duplicate of multi-display handling bugs we're tracking. Going to close and track with these.

https://github.com/pop-os/shell/issues/209
https://github.com/pop-os/shell/issues/172
https://github.com/pop-os/shell/issues/171

**Closed by WatchMkr** 2020-04-21 19:35 UTC
