### ISSUE TITLE
Mouse cursor changes location when switching workspaces with hotkey

### ISSUE THREAD

**Issue by rgegriff** [pop-os/shell#1488] opened 2022-06-29 14:57 UTC
**(1) Issue/Bug Description:**
If I switch workspaces using a keyboard combination (currently bound to mouse buttons) while the mouse cursor is on the primary display (the display that has workspaces) the mouse disappears from it's current location. It seems to get moved to the secondary screen.

**(2) Steps to reproduce (if you know):**
On my setup:
- have two displays
- have pop-shell extension enabled
- Workspaces don't span monitors (are only on primary monitor)
- use keybindings to switch next/previous workspace
- mouse cursor is on primary display when I trigger workspace change

**(3) Expected behavior:**
I expect the mouse cursor to remain in the exact same place in screen-space as it was prior to the switch

**(4) Distribution (run `cat /etc/os-release`):**
 ```
 NAME="Pop!_OS"
VERSION="22.04 LTS"
ID=pop
ID_LIKE="ubuntu debian"
PRETTY_NAME="Pop!_OS 22.04 LTS"
VERSION_ID="22.04"
HOME_URL="https://pop.system76.com"
SUPPORT_URL="https://support.system76.com"
BUG_REPORT_URL="https://github.com/pop-os/pop/issues"
PRIVACY_POLICY_URL="https://system76.com/privacy"
VERSION_CODENAME=jammy
UBUNTU_CODENAME=jammy
LOGO=distributor-logo-pop-os
```

**(5) Gnome Shell version:**
```
gnome-shell:
  Installed: 42.1-0ubuntu0.1pop1~1654265234~22.04~d8fe566
  Candidate: 42.1-0ubuntu0.1pop1~1654265234~22.04~d8fe566
```

**(6) Pop Shell version (run `apt policy pop-shell` or provide the latest commit if building locally):**
```
pop-shell:
  Installed: 1.1.0~1654875799~22.04~811201b
  Candidate: 1.1.0~1654875799~22.04~811201b
```

**(7) Where was Pop Shell installed from:**
System upgrade of PopOS!

**(8) Monitor Setup (2 x 1080p, 4K, Primary(Horizontal), Secondary(Vertical), etc):**
Output from `xrandr`
- eDP-1 connected 1920x1080+0+711 (normal left inverted right x axis y axis) 344mm x 194mm
- HDMI-1-0 connected primary 3440x1440+1920+0 (normal left inverted right x axis y axis) 797mm x 333mm

**(9) Other Installed/Enabled Extensions:**
```
'gnome-shell-screenshot@ttll.de', 
'sound-output-device-chooser@kgshank.net', 
'openweather-extension@jenslody.de', 
'pomodoro@arun.codito.in', 
'system-monitor@paradoxxx.zero.gmail.com', 
'gsconnect@andyholmes.github.io', 
'Vitals@CoreCoding.com', 
'walkpaper@walkpaper.blinkbp.github.com', 
'babar@fthx', 
'lockkeys@vaina.lt', 
'cosmic-workspaces@system76.com', 
'auto-move-windows@gnome-shell-extensions.gcampax.github.com'
```

**(10) Other Notes:**
The issue goes away if I disable pop-shell. But then so does the launcher.

**Comment by n3m0-22** [comment] 2022-06-29 15:17
Sound like you're having the same issue as described [here](https://github.com/pop-os/cosmic-workspaces/issues/76). Disabling this setting should fix the issue. 

![175560058-7b4ec7b5-a924-4132-bab8-c86e717440fc](https://user-images.githubusercontent.com/11048214/176473164-250b48e4-2e65-4371-9d4e-37129c919b58.png)

**Comment by leviport** [comment] 2022-06-29 15:18
Closing as a duplicate of https://github.com/pop-os/cosmic-workspaces/issues/76

**Closed as completed by leviport** 2022-06-29 15:18 UTC

**Comment by rgegriff** [comment] 2022-06-29 15:21
Beautiful. Thank you, @n3m0-22 My hero of the day!
