### ISSUE TITLE
Emacs (GUI) doesn't tile evenly when pop-shell's tiling mode is enabled..

### ISSUE THREAD

**Issue by argosatcore** [pop-os/shell#511] opened 2020-08-22 00:25 UTC
**Distribution (run `cat /etc/os-release`):**
 
 NAME="Pop!_OS"
VERSION="20.04 LTS"
ID=pop
ID_LIKE="ubuntu debian"
PRETTY_NAME="Pop!_OS 20.04 LTS"
VERSION_ID="20.04"
HOME_URL="https://pop.system76.com"
SUPPORT_URL="https://support.system76.com"
BUG_REPORT_URL="https://github.com/pop-os/pop/issues"
PRIVACY_POLICY_URL="https://system76.com/privacy"
VERSION_CODENAME=focal
UBUNTU_CODENAME=focal
LOGO=distributor-logo-pop-os

 
**Related Application and/or Package Version (run `apt policy pop-shell` or provide the latest commit if building locally):**

  Installed: 0.1.0~1598032836~20.04~8416328
  Candidate: 0.1.0~1598032836~20.04~8416328
  Version table:
 *** 0.1.0~1598032836~20.04~8416328 1001
       1001 http://ppa.launchpad.net/system76/pop/ubuntu focal/main amd64 Packages
       1001 http://ppa.launchpad.net/system76/pop/ubuntu focal/main i386 Packages
        100 /var/lib/dpkg/status

**Issue/Bug Description:**
Running vanilla Spacemacs on the Emacs (GUI) deb package doesn't tile evenly within a specified gap size.

**Steps to reproduce (if you know):**

1-Turn on window tiling on the pop-shell.
2-Open Emacs (GUI).

**Expected behavior:**

Emacs tiles acording to the gap size.

**Other Notes:**
Here are some screenshots in order to better illustrate my issue. See the lower right corner for the discrepancy between the tiled size of Emacs and other apps while using different gap sizes.

![Screenshot from 2020-08-21 18-13-55](https://user-images.githubusercontent.com/64110504/90944336-59134700-e3db-11ea-8467-6306eb53d547.png)

![Screenshot from 2020-08-21 18-14-26](https://user-images.githubusercontent.com/64110504/90944348-66c8cc80-e3db-11ea-9ff9-83d48b14c09e.png)

**Comment by mmstick** [comment] 2020-09-06 06:21
Duplicate of #85

**Closed by mmstick** 2020-09-06 06:21 UTC
