### ISSUE TITLE
Focus is sometimes lost when moving window between workspaces

### ISSUE THREAD

**Issue by jmbuhr** [pop-os/shell#1415] opened 2022-05-05 08:03 UTC
**Distribution (run `cat /etc/os-release`):**
```
NAME="Pop!_OS"
VERSION="22.04 LTS"
ID=pop
ID_LIKE="ubuntu debian"
PRETTY_NAME="Pop!_OS 22.04 LTS"
VERSION_ID="22.04"
HOME_URL="https://pop.system76.com"
SUPPORT_URL="https://support.system76.com"
BUG_REPORT_URL="https://github.com/pop-os/pop/issues"
PRIVACY_POLICY_URL="https://system76.com/privacy"
VERSION_CODENAME=jammy
UBUNTU_CODENAME=jammy
LOGO=distributor-logo-pop-os
```

**Issue/Bug Description:**
I previously encountere this issue only when activating "focus on hover", but now it appears to be back and this time it also appears with the default "click to focus" (https://github.com/pop-os/shell/issues/550)

**Steps to reproduce (if yoYu know):**
With multiple windows open on multiple workspaces attempt to move one window from the last to the first workspace by repeatedly pressing `shit+super+k/j`

**Expected behavior:**
Window stays focussed so that the same window is moved at every step.

**Other Notes:**

**Comment by Mindus-Amitiel-Debsin** [comment] 2022-05-05 18:07
I also have this issue - trying to move a window down multiple workspaces seems to be difficult and often the window will lose focus to another window.
I have my workspace movement buttons as L-Ctrl + Pg_Up to move one workspace up, and L-Ctrl + Pg_Dwn to move one workspace down. For moving windows, I use the Shift modifier on the workspace movement commands. 
I have found that using the shortcuts will also redirect my cursor to the top-left of the window, for example my Chrome (top-left option) close and minimize buttons, or on the top-left corner of my Steam friend's list.

While replicating this issue on screencast, I found that of three times I tried, the window only lost focus when I was going down Workspaces, IE with L-Shift + L-Ctrl + Pg_Dwn. 

I am using Pop!_OS 22.04 Intel version and just did a fresh install of it this morning.
Here is the 6MB Screencast video: https://drive.google.com/file/d/1KV65QeV33-eBdEzhW85s07TBazaOe94H/view?usp=sharing

> NAME="Pop!_OS"
VERSION="22.04 LTS"
ID=pop
ID_LIKE="ubuntu debian"
PRETTY_NAME="Pop!_OS 22.04 LTS"
VERSION_ID="22.04"
HOME_URL="https://pop.system76.com"
SUPPORT_URL="https://support.system76.com"
BUG_REPORT_URL="https://github.com/pop-os/pop/issues"
PRIVACY_POLICY_URL="https://system76.com/privacy"
VERSION_CODENAME=jammy
UBUNTU_CODENAME=jammy
LOGO=distributor-logo-pop-os

**Comment by qaa1** [comment] 2022-05-05 23:37
I'm not sure it's related or not, but alt-tab over workspace will also break focus.
Here is a vanilla popos on virtual machine just activated "Show Active Hint".
Files and Pop!_Shop are not focused during I've tried to select.

https://user-images.githubusercontent.com/69558739/167043609-a832184f-97d6-4aa7-b9ed-49bd60c05fa1.mp4

**Comment by MathieuDR** [comment] 2022-05-09 09:40
I'm also currently having this problem.

```
NAME="Pop!_OS"
VERSION="22.04 LTS"
ID=pop
ID_LIKE="ubuntu debian"
PRETTY_NAME="Pop!_OS 22.04 LTS"
VERSION_ID="22.04"
HOME_URL="https://pop.system76.com"
SUPPORT_URL="https://support.system76.com"
BUG_REPORT_URL="https://github.com/pop-os/pop/issues"
PRIVACY_POLICY_URL="https://system76.com/privacy"
VERSION_CODENAME=jammy
UBUNTU_CODENAME=jammy
LOGO=distributor-logo-pop-os
```

**Comment by MarcioFCMartins** [comment] 2022-05-09 18:14
I can confirm that I get this issue - every time I move a window between workspaces using the keyboard on 22.04

**Comment by obeobe** [comment] 2022-05-10 13:41
It also reproduces for me, and is quite annoying...

**Comment by obeobe** [comment] 2022-05-10 13:45
It seems that disabling the Pop Shell extension fixes it.

Inspired by: https://www.reddit.com/r/pop_os/comments/l4mqb7/comment/gkp8cvg/

**Comment by RafalSkolasinski** [comment] 2022-05-12 13:52
Disabling extensions is not a solution as one may require on it in their workflows. 
Has this bug been prioritized and/or is it known ETA on the fix?

**Comment by mmstick** [comment] 2022-05-12 13:54
The PR closing the issue is mentioned above. You must be patient for the fixes to pass the review process.

**Comment by obeobe** [comment] 2022-05-12 14:09
@RafalSkolasinski just to clarify, I'm not with System76, I'm just another user who encountered this issue... I just shared it as a workaround, not as a solution :)

**Comment by RafalSkolasinski** [comment] 2022-05-12 14:12
Totally :) - the information is also useful as it confirms issue is with extension.
I am glad that @mmstick already has a PR fixing it. It also seems to be fixing bunch of other issues. 

Can't wait to see it merged!

**Closed** 2022-05-13 17:39 UTC

**Comment by SquareWhite** [comment] 2022-05-14 08:25
Just pulled the latest version and it's working perfectly now. Thanks so much for your work!

**Comment by MarcioFCMartins** [comment] 2022-05-14 11:59
I also updated but am still getting the issue, when a window is moved across workspaces, the window which was previously in focus in that workspace is re-focused. I tried disabling non-pop extensions and it still happened, only me?

**Comment by mmstick** [comment] 2022-05-14 12:04
Updated with git?

**Comment by MarcioFCMartins** [comment] 2022-05-14 12:42
> Updated with git?

Ah, my bad. There was an update pushed to the repos this morning and I assumed it included this change. Hopefully soon, thanks for your work!

**Comment by mmstick** [comment] 2022-05-14 13:31
Although the pull request was merged an update won't be released until a final review on Monday.

**Comment by SquareWhite** [comment] 2022-05-16 09:06
It looks like the PR related to this issue has introduced a bug. I've described it here #1434
