### ISSUE TITLE
[FEATURE PROPOSAL] Save and load Sessions

### ISSUE THREAD

**Issue by hovo1990** [pop-os/shell#886] opened 2021-02-21 09:34 UTC
Hi, 
Thanks for the POP shell, it's a wonderful tool!

I have one feature proposal: It would be really awesome if it was possible to save and reload opened programs and the positions of their windows (stacking included).

**Comment by trevarj** [comment] 2021-02-21 16:51
Came here looking for this too. I wonder if it would something that can be done with a plugin.

**Comment by mmstick** [comment] 2021-02-21 22:23
Duplicate of #735

**Closed by mmstick** 2021-02-21 22:23 UTC
