### ISSUE TITLE
[bug] sending windows to other monitor doesn't work when `Tile Windows` option is enabled.

### ISSUE THREAD

**Issue by aasutossh** [pop-os/shell#124] opened 2020-03-29 02:31 UTC
I am using pop os 19.10 with all latest updates.
Typescript using `npm install` (the `node-typescript` was `3.6` something version, so I uninstalled it).

Two monitors, one Laptop's internal 1080p, one external (one on the right, 720p).
Installed `pop-os/shell` today.

When tiling is disabled the keybind (`super+shift+direction`) works but not when tiling is enabled. I can do `super+enter` then `direction` to move windows to monitors, but it has one issue.

The issue is the position of the cursor (when one monitor is empty), when the cursor is on 2nd monitor (which is empty) I can't move the window to 2nd monitor using `super+enter` `direction` keys, but if I move cursor to primary monitor (non empty), it works. 
In simplified terms, if one monitor is empty and cursor is on the empty monitor, then can't move windows using `super+enter` `direction` keys.

**Comment by mmstick** [comment] 2020-03-30 05:56
Duplicate of #105

**Closed by mmstick** 2020-03-30 05:56 UTC

**Comment by aasutossh** [comment] 2020-03-30 15:16
Okay.
