### ISSUE TITLE
Launcher does not work

### ISSUE THREAD

**Issue by dharmik2319** [pop-os/shell#1603] opened 2023-03-24 09:10 UTC
**(1) Issue/Bug Description:**
When pressing `super`, the launcher window does show up, but is empty, and does not show running apps, and also cannot search apps, or basically anything (like the calculator with the `=` key). Even `?` doesn't work, it still remains empty.

**(2) Steps to reproduce (if you know):**
press `super` or `super+/`

**(3) Expected behavior:**
Launcher shows all running apps and searchable apps and functions normally, as it would.

**(4) Distribution (run `cat /etc/os-release`):**
  ```
NAME="Pop!_OS"
VERSION="22.04 LTS"
ID=pop
ID_LIKE="ubuntu debian"
PRETTY_NAME="Pop!_OS 22.04 LTS"
VERSION_ID="22.04"
HOME_URL="https://pop.system76.com"
SUPPORT_URL="https://support.system76.com"
BUG_REPORT_URL="https://github.com/pop-os/pop/issues"
PRIVACY_POLICY_URL="https://system76.com/privacy"
VERSION_CODENAME=jammy
UBUNTU_CODENAME=jammy
LOGO=distributor-logo-pop-os
```

**(5) Gnome Shell version:**
`gnome-shell --version` reports `GNOME Shell 42.5`

**(6) Pop Shell/Launcher version (run `apt policy pop-shell` or provide the latest commit if building locally):**

```pop-shell:
  Installed: 1.1.0~1677211888~22.04~dcf17f3
  Candidate: 1.1.0~1677211888~22.04~dcf17f3
  Version table:
 *** 1.1.0~1677211888~22.04~dcf17f3 1001
       1001 http://apt.pop-os.org/release jammy/main amd64 Packages
       1001 http://apt.pop-os.org/release jammy/main i386 Packages
        100 /var/lib/dpkg/status
```
```
pop-launcher:
  Installed: 1.2.2~1678935224~22.04~717fd61
  Candidate: 1.2.2~1678935224~22.04~717fd61
  Version table:
 *** 1.2.2~1678935224~22.04~717fd61 1001
       1001 http://apt.pop-os.org/release jammy/main amd64 Packages
        100 /var/lib/dpkg/status
```

**(7) Where was Pop Shell installed from:**
Preinstalled and updated, not built from source

**(8) Monitor Setup (2 x 1080p, 4K, Primary(Horizontal), Secondary(Vertical), etc):**
Single 1360x768 monitor

**(9) Other Installed/Enabled Extensions:**
`gnome-extensions list --enabled` reports:
```
clipboard-indicator@tudmotu.com
dash-to-dock-cosmic-@halfmexicanhalfamazing@gmail.com
emoji-selector@maestroschan.fr
compiz-windows-effect@hermes83.github.com
cosmic-workspaces@system76.com
ding@rastersoft.com
pop-cosmic@system76.com
pop-shell@system76.com
system76-power@system76.com
screenshot-window-sizer@gnome-shell-extensions.gcampax.github.com
user-theme@gnome-shell-extensions.gcampax.github.com
```

**(10) Other Notes:**
`pop-launcher` reports:
```
[1]    33278 illegal hardware instruction (core dumped)  pop-launcher
```

The issue has been persisting since about a month or so.
I have created an issue in the launcher repo as [well](https://github.com/pop-os/launcher/issues/177)

Some screenshots:
![image](https://user-images.githubusercontent.com/126943942/227473936-900b8552-2076-4489-ba86-448edcbe1708.png)
![Screenshot from 2023-03-24 14-33-51](https://user-images.githubusercontent.com/126943942/227474102-14de5f16-67f5-4fb0-9555-2b425f115132.png)
![Screenshot from 2023-03-24 14-33-40](https://user-images.githubusercontent.com/126943942/227474120-c0f354bf-b74d-4a11-a06a-93ab51566944.png)
![Screenshot from 2023-03-24 14-33-18](https://user-images.githubusercontent.com/126943942/227474136-4bbc83f5-6924-40c4-9ce9-7ef1bfd4bdf1.png)

**Comment by leviport** [comment] 2023-03-24 13:59
Duplicate of https://github.com/pop-os/launcher/issues/177

Please only file one issue.

**Closed as completed by leviport** 2023-03-24 13:59 UTC

**Comment by dharmik2319** [comment] 2023-03-24 14:51
Okay, Thanks. I didn't know where to create the issue so i created at both the places.

**Comment by leviport** [comment] 2023-03-24 15:06
They can be transferred if they're in the wrong spot

**Comment by dharmik2319** [comment] 2023-03-24 15:55
Thanks for your support!
