### ISSUE TITLE
Natural Scrolling broken with 4 finger gesture between workspaces.

### ISSUE THREAD

**Issue by shamuraix** [pop-os/shell#1344] opened 2022-02-03 01:02 UTC
**(1) Issue/Bug Description:**

Setting "Natural Scrolling" on in Settings under "Mouse & Touchpad" results in expect behavior with scrolling in apps but when scrolling workspaces its still off.

**(2) Steps to reproduce (if you know):**

Set Natural Scrolling on.
Use four finger gesture to move between workspaces

**(3) Expected behavior:**

Natural Scrolling would result in a downwards motion going up a workspace and upwards motion going down a workspace.

**(4) Distribution (run `cat /etc/os-release`):**

 NAME="Pop!_OS"
VERSION="21.10"
ID=pop
ID_LIKE="ubuntu debian"
PRETTY_NAME="Pop!_OS 21.10"
VERSION_ID="21.10"
HOME_URL="https://pop.system76.com"
SUPPORT_URL="https://support.system76.com"
BUG_REPORT_URL="https://github.com/pop-os/pop/issues"
PRIVACY_POLICY_URL="https://system76.com/privacy"
VERSION_CODENAME=impish
UBUNTU_CODENAME=impish
LOGO=distributor-logo-pop-os

**(5) Gnome Shell version:**

GNOME Shell 40.5

**(6) Pop Shell version (run `apt policy pop-shell` or provide the latest commit if building locally):**

````
pop-shell:
  Installed: 1.1.0~1643736613~21.10~afb4f12
  Candidate: 1.1.0~1643736613~21.10~afb4f12
  Version table:
 *** 1.1.0~1643736613~21.10~afb4f12 1001
       1001 http://apt.pop-os.org/release impish/main amd64 Packages
       1001 http://apt.pop-os.org/release impish/main i386 Packages
        100 /var/lib/dpkg/status
````

**(7) Where was Pop Shell installed from:**

Official ISO

**(8) Monitor Setup (2 x 1080p, 4K, Primary(Horizontal), Secondary(Vertical), etc):**

1 x Built-In 3840x2160

**(9) Other Installed/Enabled Extensions:**

N/A

**Comment by leviport** [comment] 2022-02-03 16:27
Duplicate of https://github.com/pop-os/cosmic/issues/110

**Closed by leviport** 2022-02-03 16:27 UTC
