### ISSUE TITLE
Firefox window isn't fully extended in window mode.

### ISSUE THREAD

**Issue by laichiaheng** [pop-os/shell#608] opened 2020-10-07 01:05 UTC
**(1) Issue/Bug Description:**
The window isn't fully extended in window mode, but it doesn't happen every time.
![2020-10-07 09-00-07 的螢幕擷圖](https://user-images.githubusercontent.com/9532105/95275943-6fd30780-087c-11eb-834e-e028769aa733.png)

**(2) Steps to reproduce (if you know):**
Open Firefox

**(3) Expected behavior:**
The window is fully extended.

**(4) Distribution (run `cat /etc/os-release`):**
```
NAME="Manjaro Linux"
ID=manjaro
ID_LIKE=arch
BUILD_ID=rolling
PRETTY_NAME="Manjaro Linux"
ANSI_COLOR="32;1;24;144;200"
HOME_URL="https://manjaro.org/"
DOCUMENTATION_URL="https://wiki.manjaro.org/"
SUPPORT_URL="https://manjaro.org/"
BUG_REPORT_URL="https://bugs.manjaro.org/"
LOGO=manjarolinux
```

**(5) Gnome Shell version:**
3.38.1

**(6) Pop Shell version (run `apt policy pop-shell` or provide the latest commit if building locally):**

```
Name            : gnome-shell-extension-pop-shell-git
Version         : r564.d2f1f64-1
Description     : Pop Shell - Tiling window management in Gnome (WIP)
Architecture    : any
URL             : https://github.com/pop-os/shell
Licenses        : GPLv3
Groups          : None
Provides        : None
Depends On      : gnome-shell  pop-shell-shortcuts-git
Optional Deps   : None
Required By     : None
Optional For    : None
Conflicts With  : gnome-shell-extension-pop-shell
Replaces        : None
Installed Size  : 816.96 KiB
Packager        : Unknown Packager
Build Date      : Wed Oct 7 08:57:06 2020
Install Date    : Wed Oct 7 08:57:23 2020
Install Reason  : Explicitly installed
Install Script  : Yes
Validated By    : None
```

**(7) Where was Pop Shell installed from:**
AUR

**(8) Monitor Setup (2 x 1080p, 4K, Primary(Horizontal), Secondary(Vertical), etc):**
1 x 1080p

**(9) Other Installed/Enabled Extensions:**
`cpufreq` `GameMode` `GSConnect` `KStatusNotifierItem/AppIndicator Support` `Pamac Updates Indicator` `Sound Input & Output Device Chooser` `User Themes`

**(10) Other Notes:**

**Comment by mmstick** [comment] 2020-10-07 02:46
This is a duplicate, but does it happen if you have the latest version installed, and restart the shell after installing it?

**Comment by laichiaheng** [comment] 2020-10-07 03:29
> This is a duplicate, but does it happen if you have the latest version installed, and restart the shell after installing it?

Yes, I'm currently running the latest `gnome-shell-extension-pop-shell-git`.

**Comment by Kernel-Panic-Gaming** [comment] 2020-10-11 20:43
(1) Issue/Bug Description:
When Popshell is on sometimes the window doesn't extend fully to desktop.  I can press minimize and maximize buttons to fix the problem.  I've tried this many times.  I've tried different variations of keeping window maximized turning pop shell off and on again. I restarted pop shell and it still happens.  This bug doesn't happen every time, for me every other time I open firefox it will mess up.  I get two separate mess ups posted below. 
![Screenshot from 2020-10-11 16-21-38](https://user-images.githubusercontent.com/44524370/95689671-629d7c00-0be0-11eb-9c2c-1938620677a3.png)

![Screenshot from 2020-10-11 16-25-41](https://user-images.githubusercontent.com/44524370/95689676-65986c80-0be0-11eb-99ed-8c278db17584.png)




(2) Steps to reproduce (if you know):
Open Firefox

(3) Expected behavior:
The window should be fully extended

(4) Distribution (run cat /etc/os-release):

NAME="Pop!_OS"
VERSION="20.04 LTS"
ID=pop
ID_LIKE="ubuntu debian"
PRETTY_NAME="Pop!_OS 20.04 LTS"
VERSION_ID="20.04"
HOME_URL="https://pop.system76.com"
SUPPORT_URL="https://support.system76.com"
BUG_REPORT_URL="https://github.com/pop-os/pop/issues"
PRIVACY_POLICY_URL="https://system76.com/privacy"
VERSION_CODENAME=focal
UBUNTU_CODENAME=focal
LOGO=distributor-logo-pop-os


(5) Gnome Shell version:
3.36.3

(6) Pop Shell version (run apt policy pop-shell or provide the latest commit if building locally):

pop-shell:
  Installed: 0.1.0~1602257816~20.04~6fb9b76
  Candidate: 0.1.0~1602257816~20.04~6fb9b76
  Version table:
 *** 0.1.0~1602257816~20.04~6fb9b76 1001
       1001 http://ppa.launchpad.net/system76/pop/ubuntu focal/main amd64 Packages
       1001 http://ppa.launchpad.net/system76/pop/ubuntu focal/main i386 Packages
        100 /var/lib/dpkg/status


(7) Where was Pop Shell installed from:
Already install in Pop!_OS

(8) Monitor Setup 1080p 144hz

(9) Other Installed/Enabled Extensions:
GameMode  Sound Input & Output Device Chooser 

(10) Other Notes:

**Comment by mmstick** [comment] 2021-01-14 13:59
Duplicate of #388

**Closed by mmstick** 2021-01-14 13:59 UTC
