### ISSUE TITLE
BUG: Touchpad gestures do not obey natural scrolling

### ISSUE THREAD

**Issue by sdimovv** [pop-os/shell#1110] opened 2021-07-25 23:27 UTC
I am not sure if this is the best place to post this, please suggest an alternative if not.

**(1) Issue/Bug Description:**
It seems that selecting the "natural scrolling" option in the touchpad settings reverses the 2-finger scrolling direction but not the 4-finger scrolling direction (virtual desktop scrolling). I assume the same problem applies for 3-finger scroll (window scrolling), but I am not sure what the direction should be in either case so I cannot confirm that.

**(2) Steps to reproduce (if you know):**
1. Select natural scrolling from touchpad settings.
2. Test 2-finger scroll - it is reversed
3. Test 4-finger scroll - it is not

**(3) Expected behavior:**
2-finger, 3-finger, 4-finger scroll should always match direction

**(4) Distribution (run `cat /etc/os-release`):**
 
```
NAME="Pop!_OS"
VERSION="21.04"
ID=pop
ID_LIKE="ubuntu debian"
PRETTY_NAME="Pop!_OS 21.04"
VERSION_ID="21.04"
HOME_URL="https://pop.system76.com"
SUPPORT_URL="https://support.system76.com"
BUG_REPORT_URL="https://github.com/pop-os/pop/issues"
PRIVACY_POLICY_URL="https://system76.com/privacy"
VERSION_CODENAME=hirsute
UBUNTU_CODENAME=hirsute
LOGO=distributor-logo-pop-os
```

**(5) Gnome Shell version:**

```
GNOME Shell 3.38.4
```

**(6) Pop Shell version (run `apt policy pop-shell` or provide the latest commit if building locally):**
```
pop-shell:
  Installed: 1.1.0~1626728027~21.04~9616931
  Candidate: 1.1.0~1626728027~21.04~9616931
  Version table:
 *** 1.1.0~1626728027~21.04~9616931 1001
       1001 http://ppa.launchpad.net/system76/pop/ubuntu hirsute/main amd64 Packages
       1001 http://ppa.launchpad.net/system76/pop/ubuntu hirsute/main i386 Packages
        100 /var/lib/dpkg/status
```

**(7) Where was Pop Shell installed from:**

No custom installs, stock shell on PopOS 21.04

**(8) Monitor Setup (2 x 1080p, 4K, Primary(Horizontal), Secondary(Vertical), etc):**

1080p single monitor, horizontal

**(9) Other Installed/Enabled Extensions:**

None

**(10) Other Notes:**

NA

**Comment by mmstick** [comment] 2021-07-26 12:58
Duplicate of https://github.com/pop-os/cosmic/issues/110

**Closed by mmstick** 2021-07-26 12:58 UTC
