### ISSUE TITLE
Firefox displays incorrectly.

### ISSUE THREAD

**Issue by laichiaheng** [pop-os/shell#812] opened 2021-01-07 02:10 UTC
**(1) Issue/Bug Description:**
The first time I open it.
![2021-01-07 10-06-00 的螢幕擷圖](https://user-images.githubusercontent.com/9532105/103842133-263ec680-50d0-11eb-9937-fa2b5a4e65a6.png)
Unmaximize after maximize.
![2021-01-07 10-06-12 的螢幕擷圖](https://user-images.githubusercontent.com/9532105/103842136-28088a00-50d0-11eb-88f1-b81aebb24098.png)

**(2) Steps to reproduce (if you know):**
1. Open it.
2. Maximize it
3. Unmaximize it.
**(3) Expected behavior:**
The window is fully extended.

**(4) Distribution (run `cat /etc/os-release`):**
```
NAME="Manjaro Linux"
ID=manjaro
ID_LIKE=arch
BUILD_ID=rolling
PRETTY_NAME="Manjaro Linux"
ANSI_COLOR="32;1;24;144;200"
HOME_URL="https://manjaro.org/"
DOCUMENTATION_URL="https://wiki.manjaro.org/"
SUPPORT_URL="https://manjaro.org/"
BUG_REPORT_URL="https://bugs.manjaro.org/"
LOGO=manjarolinux
```

**(5) Gnome Shell version:**
3.38.2

**(6) Pop Shell version (run `apt policy pop-shell` or provide the latest commit if building locally):**

```
Name            : gnome-shell-extension-pop-shell-git
Version         : r641.c0e4226-1
Description     : Pop Shell - Tiling window management in Gnome (WIP)
Architecture    : any
URL             : https://github.com/pop-os/shell
Licenses        : GPLv3
Groups          : None
Provides        : None
Depends On      : gnome-shell  pop-shell-shortcuts-git
Optional Deps   : gnome-shell-extensions: native-window extension for improved window placement
                  [installed]
Required By     : None
Optional For    : None
Conflicts With  : gnome-shell-extension-pop-shell
Replaces        : None
Installed Size  : 1026.36 KiB
Packager        : Unknown Packager
Build Date      : Thu Jan 7 10:05:00 2021
Install Date    : Thu Jan 7 10:05:26 2021
Install Reason  : Explicitly installed
Install Script  : Yes
Validated By    : None
```

**(7) Where was Pop Shell installed from:**
AUR

**(8) Monitor Setup (2 x 1080p, 4K, Primary(Horizontal), Secondary(Vertical), etc):**
1 x 1080p

**(9) Other Installed/Enabled Extensions:**

**(10) Other Notes:**

**Comment by rivenirvana** [comment] 2021-01-07 03:14
I'm also experiencing a somewhat similar behavior with Firefox only when Smart Gaps is enabled and it is the first window I open in a workspace. The entire Firefox window only fills up ~80% of the screen from left to right (similar to the first picture). A few `<Super>+m` serves as a temporary workaround, though.

**Comment by laichiaheng** [comment] 2021-01-07 03:29
Thanks, after disabling smart gap, the problem is gone.

**Comment by mmstick** [comment] 2021-01-12 23:55
Duplicate of #388

**Closed by mmstick** 2021-01-12 23:55 UTC
