### ISSUE TITLE
[enhancement] Allow certain application / windows to be ignored (defaults to floating) in auto tiling mode.

### ISSUE THREAD

**Issue by yzhuang** [pop-os/shell#441] opened 2020-06-29 21:30 UTC
Certain windows (e.g. ephemeral pop-ups) should not be tiled in auto-tiling mode. For example, the pop up window from CopyQ (a clipboard history manager) gets auto-tiled, and the experience is poor.

It would be nice to add support for one of the following:
- Remember which windows / applications were set to float with super+G, and auto float that window the next time it shows up.
- Allow user to specify a list of applications / windows to automatically float in auto tiling mode.

**Comment by rgegriff** [comment] 2020-07-06 16:54
I have also been running to this as an issue. I have an IDE that kicks off a build in a new ephemeral window, and it disrupts the layout every time it runs. It would be really nice if I could configure it to default to floating.

**Comment by heartles** [comment] 2020-07-30 04:09
I have a couple games I run that have some weird window movement in borderless fullscreen mode because of this, it would be nice to configure pop shell to treat them as floating automatically.

**Comment by jacobgkau** [comment] 2020-08-05 14:50
This feature request is a duplicate of https://github.com/pop-os/shell/issues/254.

**Closed by jacobgkau** 2020-08-05 14:50 UTC
