### ISSUE TITLE
Switching to opened IntelliJ IDEA with standard key bindings isn't working (Alt+Tab; Win -> Ctrl+number) in tiling mode

### ISSUE THREAD

**Issue by art-tapin** [pop-os/shell#1318] opened 2022-01-13 15:35 UTC
**(1) Issue/Bug Description:**
When I open Intellij IDEA (IDE from JetBrains) and switch to another application I can't go back to IDE with standard key bindings like Alt+Tab or Win, Ctrl+number (from launcher), or even from the dock. The focus remains on the previous application.
I tried several JetBrains products and every one of them behaved like that.

**(2) Steps to reproduce (if you know):**
It started after updating to Pop_OS 21.10
1. Update
2. Install flatpak version of IntelliJ IDEA from Pop_shop
3. Enable tiling mode
3. Open IDEA
4. Open another application
5. Try to switch from that application to IDEA with Alt+Tab

**(3) Expected behavior:**
Switching to an app as usual - gaining focus on the app that you've selected

**(4) Distribution (run `cat /etc/os-release`):**
NAME="Pop!_OS"
VERSION="21.10"
ID=pop
ID_LIKE="ubuntu debian"
PRETTY_NAME="Pop!_OS 21.10"
VERSION_ID="21.10"
HOME_URL="https://pop.system76.com"
SUPPORT_URL="https://support.system76.com"
BUG_REPORT_URL="https://github.com/pop-os/pop/issues"
PRIVACY_POLICY_URL="https://system76.com/privacy"
VERSION_CODENAME=impish
UBUNTU_CODENAME=impish
LOGO=distributor-logo-pop-os

**(5) Gnome Shell version:**
DE: GNOME 40.5

**(6) Pop Shell version (run `apt policy pop-shell` or provide the latest commit if building locally):**
```
pop-shell:
  Installed: 1.1.0~1641595320~21.10~c3d93f8
  Candidate: 1.1.0~1641595320~21.10~c3d93f8
  Version table:
 *** 1.1.0~1641595320~21.10~c3d93f8 1001
       1001 http://apt.pop-os.org/release impish/main amd64 Packages
       1001 http://apt.pop-os.org/release impish/main i386 Packages
        100 /var/lib/dpkg/status
```

**(7) Where was Pop Shell installed from:**
I've updated it from Settings - OS Upgrade & Recover

**(8) Monitor Setup (2 x 1080p, 4K, Primary(Horizontal), Secondary(Vertical), etc):**
External monitor 2560*1080 (Landscape)

**(9) Other Installed/Enabled Extensions:**
Workrave

**(10) Additional Notes:**
I found that it happens only in tiling window mode

**Comment by mmstick** [comment] 2022-01-13 15:42
Duplicate of #1312

**Closed by mmstick** 2022-01-13 15:42 UTC
