### ISSUE TITLE
When a window is on the top of the screen, the active screen hint glitches

### ISSUE THREAD

**Issue by TahsinTariq** [pop-os/shell#1004] opened 2021-06-17 08:35 UTC
**(1) Issue/Bug Description:**
In the screenshot, I'm using guake to demonstrate the glitch, but it happens for any other window as well.

Look at the bottom part of the active window. The hint is a few pixels below where it should be. I put another terminal below to show the gap clearly.
![image](https://user-images.githubusercontent.com/62146852/122359808-b0d8fb00-cf77-11eb-8ddd-17778e0b3399.png)

**(2) Steps to reproduce (if you know):**
- Take any window and move it as high as you can without maximizing it.
- Put some different colored window under this window to see the gap. 

**(4) Distribution (run `cat /etc/os-release`):**
```
NAME="Pop!_OS"
VERSION="20.10"
ID=pop
ID_LIKE="ubuntu debian"
PRETTY_NAME="Pop!_OS 20.10"
VERSION_ID="20.10"
HOME_URL="https://pop.system76.com"
SUPPORT_URL="https://support.system76.com"
BUG_REPORT_URL="https://github.com/pop-os/pop/issues"
PRIVACY_POLICY_URL="https://system76.com/privacy"
VERSION_CODENAME=groovy
UBUNTU_CODENAME=groovy
LOGO=distributor-logo-pop-os
```

**(5) Gnome Shell version:** 3.38.3

**(6) Pop Shell version (run `apt policy pop-shell` or provide the latest commit if building locally):**

```
pop-shell:
  Installed: 1.1.0~1623101914~20.10~df8b27b
  Candidate: 1.1.0~1623101914~20.10~df8b27b
  Version table:
 *** 1.1.0~1623101914~20.10~df8b27b 1001
       1001 http://ppa.launchpad.net/system76/pop/ubuntu groovy/main amd64 Packages
       1001 http://ppa.launchpad.net/system76/pop/ubuntu groovy/main i386 Packages
        100 /var/lib/dpkg/status
```

**(8) Monitor Setup:** single 1080p horizontal

**(9) Other Installed/Enabled Extensions:** 
Running `gnome-extensions list --enabled`
```
alt-tab-raise-first-window@system76.com
always-show-workspaces@system76.com
ding@rastersoft.com
pop-shell@system76.com
pop-shop-details@system76.com
system76-power@system76.com
ubuntu-appindicators@ubuntu.com
drive-menu@gnome-shell-extensions.gcampax.github.com
native-window-placement@gnome-shell-extensions.gcampax.github.com
places-menu@gnome-shell-extensions.gcampax.github.com
screenshot-window-sizer@gnome-shell-extensions.gcampax.github.com
user-theme@gnome-shell-extensions.gcampax.github.com
windowsNavigator@gnome-shell-extensions.gcampax.github.com
workspace-indicator@gnome-shell-extensions.gcampax.github.com
```

**Comment by bflanagin** [comment] 2021-06-17 16:54
Looks like this is a duplicate of https://github.com/pop-os/shell/issues/990. We'll continue to track the issue there.

**Closed by bflanagin** 2021-06-17 16:54 UTC
