### ISSUE TITLE
Moving Windows from Overview also moves extra windows

### ISSUE THREAD

**Issue by isantop** [pop-os/shell#169] opened 2020-04-15 19:28 UTC
When dragging windows around different workspaces using the overview, Shell will often also move additional windows around as well. This can be highly confusing when one tries to move a window, and another random window also leaves. It can additionally negate the user's actual action, should there only be two windows on the workspace and both of them move. 

I've also seen occasional cases where I drag a window to a different workspace, but a different window (not the one I moved) moves. The window I dragged in this case stays where it is. This feels related to me, but I'm not sure if it's being caused by the same issue.

**Comment by mmstick** [comment] 2020-04-15 19:29
How did you get this to happen?

**Comment by isantop** [comment] 2020-04-15 19:31
By dragging a window from one workspace to another using the overview

**Comment by mmstick** [comment] 2020-04-15 19:32
Is there a certain layout that causes this? Because I haven't seen this happen before.

**Comment by isantop** [comment] 2020-04-15 19:38
I was able to replicate it during a screencast:

[Screencast from 04-15-2020 01:36:54 PM.zip](https://github.com/pop-os/shell/files/4483386/Screencast.from.04-15-2020.01.36.54.PM.zip)

**Comment by leviport** [comment] 2020-04-15 19:42
I often see some weirdness when dragging windows to a new workspace at the very beginning of the list in the overview. Maybe that is related?

**Comment by mmstick** [comment] 2020-04-15 19:58
I see. This is a duplicate of #139 and I'm not sure what can be done since GNOME Shell isn't telling us about the movements of windows. Technically what it is doing is creating a new workspace at the end, and then moving all the windows one workspace up, which causes everything to get retiled.

**Closed by mmstick** 2020-04-15 19:58 UTC
Labels: bug
