### ISSUE TITLE
is there any way to search gnome extension from pop shop?

### ISSUE THREAD

**Issue by nazar2sfive** [pop-os/shell#1062] opened 2021-07-05 15:26 UTC
**(1) Issue/Bug Description:**

**(2) Steps to reproduce (if you know):**

**(3) Expected behavior:**

**(4) Distribution (run `cat /etc/os-release`):**
 

**(5) Gnome Shell version:**

**(6) Pop Shell version (run `apt policy pop-shell` or provide the latest commit if building locally):**

**(7) Where was Pop Shell installed from:**

**(8) Monitor Setup (2 x 1080p, 4K, Primary(Horizontal), Secondary(Vertical), etc):**

**(9) Other Installed/Enabled Extensions:**

**(10) Other Notes:**

**Comment by jmmaranan** [comment] 2021-07-05 15:40
@nazar2sfive - please close this as a duplicate of 1063

**Closed** 2021-07-05 15:41 UTC
