### ISSUE TITLE
Use Launcher, and enable Chinese Input Method, and switch to Chinese Input Method,(IBUS-PINYIN), while randomly typing a few characters

### ISSUE THREAD

**Issue by czfadmin** [pop-os/shell#986] opened 2021-05-31 15:04 UTC
**(1) Issue/Bug Description:**
Launching Lanucher with Chinese input will cause the desktop environment to freeze and reload, and the fonts on the application and desktop will blur

**(2) Steps to reproduce (if you know):**
Use Launcher, and enable Chinese Input Method, and switch to Chinese Input Method,(IBUS-PINYIN), while randomly typing a few characters

**(3) Expected behavior:**
Font blurring appears in apps and desktop interfaces

**(4) Distribution (run `cat /etc/os-release`):**
NAME="Pop!_OS"
VERSION="20.10"
ID=pop
ID_LIKE="ubuntu debian"
PRETTY_NAME="Pop!_OS 20.10"
VERSION_ID="20.10"
HOME_URL="https://pop.system76.com"
SUPPORT_URL="https://support.system76.com"
BUG_REPORT_URL="https://github.com/pop-os/pop/issues"
PRIVACY_POLICY_URL="https://system76.com/privacy"
VERSION_CODENAME=groovy
UBUNTU_CODENAME=groovy
LOGO=distributor-logo-pop-os

**(5) Gnome Shell version:**
3.38.3

**(6) Pop Shell version (run `apt policy pop-shell` or provide the latest commit if building locally):**

**(7) Where was Pop Shell installed from:**

**(8) Monitor Setup (2 x 1080p, 4K, Primary(Horizontal), Secondary(Vertical), etc):**

**(9) Other Installed/Enabled Extensions:**

**(10) Other Notes:**

**Comment by mmstick** [comment] 2021-06-01 00:53
Duplicate of #967

**Closed by mmstick** 2021-06-01 00:53 UTC
