### ISSUE TITLE
Workspace shortcuts don't work

### ISSUE THREAD

**Issue by milhauzindahauz** [pop-os/shell#1138] opened 2021-08-13 10:41 UTC
**(1) Issue/Bug Description:**
Shortcuts for workspaces navigation don't work. 

`<Super><Shift> down` -> move current window to last workspace ( Not sure if this is intended)
`<Super><Ctrl> up/down` -> don't work
`<Super><Shift> up` -> don't work

**(2) Steps to reproduce (if you know):**
Do not know

**(3) Expected behavior:**
Shortcuts should work as intended. 

**(4) Distribution (run `cat /etc/os-release`):**
 NAME=Fedora
VERSION="34 (Workstation Edition)"
ID=fedora
VERSION_ID=34
VERSION_CODENAME=""
PLATFORM_ID="platform:f34"
PRETTY_NAME="Fedora 34 (Workstation Edition)"
ANSI_COLOR="0;38;2;60;110;180"
LOGO=fedora-logo-icon
CPE_NAME="cpe:/o:fedoraproject:fedora:34"
HOME_URL="https://fedoraproject.org/"
DOCUMENTATION_URL="https://docs.fedoraproject.org/en-US/fedora/34/system-administrators-guide/"
SUPPORT_URL="https://fedoraproject.org/wiki/Communicating_and_getting_help"
BUG_REPORT_URL="https://bugzilla.redhat.com/"
REDHAT_BUGZILLA_PRODUCT="Fedora"
REDHAT_BUGZILLA_PRODUCT_VERSION=34
REDHAT_SUPPORT_PRODUCT="Fedora"
REDHAT_SUPPORT_PRODUCT_VERSION=34
PRIVACY_POLICY_URL="https://fedoraproject.org/wiki/Legal:PrivacyPolicy"
VARIANT="Workstation Edition"
VARIANT_ID=workstation

**(5) Gnome Shell version:**
```
<?xml version="1.0"?>
<gnome-version>
 <platform>40</platform>
 <minor>1</minor>
 <micro>0</micro>
 <distributor>GNOME.Org</distributor>
 <date>2021-05-05</date>
</gnome-version>
```

**(6) Pop Shell version (run `apt policy pop-shell` or provide the latest commit if building locally):**

```
Name         : gnome-shell-extension-pop-shell
Version      : 1.2.0^2.9616931
Release      : 1.fc34
Architecture : noarch
Size         : 1.1 M
Source       : gnome-shell-extension-pop-shell-1.2.0^2.9616931-1.fc34.src.rpm
Repository   : @System
From repo    : updates
```

**(7) Where was Pop Shell installed from:**
fedora rpms:
https://src.fedoraproject.org/fork/atim/rpms/gnome-shell-extension-pop-shell

**(8) Monitor Setup (2 x 1080p, 4K, Primary(Horizontal), Secondary(Vertical), etc):**
4k - Horizontal + 1080p Horizontal

**(9) Other Installed/Enabled Extensions:**
None

**Comment by mmstick** [comment] 2021-08-13 10:50
Duplicate of #1128

**Closed by mmstick** 2021-08-13 10:50 UTC
